import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {buildAshesPayload,createAshesReaderController} from "../src/mass/reader-ashes.js";
const load=p=>JSON.parse(readFileSync(new URL(p,import.meta.url),"utf8"));
const payload=load("../data/presentation/reader-ashes.v1.json");
const graph=load("../data/mass/special-days-extension.v1.3.json").graphs.ASH;
const built=buildAshesPayload({graph,payload});
assert.equal(built.cards.length,6);
assert.equal(built.cards[1].paragraphs.length,4);
assert.match(built.cards[3].paragraphs.at(-1).latin,/Memento, homo/);
assert.equal(built.cards.at(-1).handoff,"INTROIT");
const c=createAshesReaderController({graph,payload});
c.goTo("ASH-R04");
assert.equal(c.project().recipientPosture,null);
c.setRecipientState("RECEIVE_ASHES");
assert.equal(c.project().recipientPosture,"KNEEL");
c.setRecipientState("ASHES_RECEIVED");
assert.equal(c.project().recipientPosture,"STAND_WALK");
c.goTo("ASH-R06");
assert.equal(c.project().ordinaryOpeningSuppressed,true);
console.log("native Ash Wednesday payload: PASS — four prayers, personal reception and Introit handoff.");
