// The Mass hub and Tenebrae borrow the LIVE ribbon, focus and liturgical
// typography principles; neither hijacks the certified R17 reader CSS.
const ID="ao-mass-hub-style-v1";
export function installMassHubStyles(doc=globalThis.document){
 if(!doc?.createElement||doc.getElementById(ID))return false;
 const el=doc.createElement("style");el.id=ID;
 el.textContent=[
 "#ao-mass-modular-root{position:fixed;inset:0 0 60px;z-index:var(--ao-z-surface,2147481800);overflow-y:auto;overscroll-behavior:contain;background:var(--ao-bg,#080c12);color:var(--ao-text-primary,#ede5d7);font:400 14px/1.6 var(--ao-font-ui,system-ui,sans-serif);isolation:isolate;scrollbar-width:thin}",
 "#ao-mass-modular-root[hidden]{display:none!important}",
 "#ao-mass-modular-root button,#ao-mass-modular-root select{touch-action:manipulation;cursor:pointer}",
 "#ao-mass-modular-root .aoMassHubRibbon{display:grid;grid-template-columns:50px minmax(0,1fr) 50px;align-items:center;min-height:64px;padding:8px clamp(12px,3vw,28px);gap:8px;position:sticky;top:0;z-index:6;border-bottom:1px solid var(--ao-rule,rgba(204,179,136,.26));background:#0b111a;backdrop-filter:blur(16px)}",
 "#ao-mass-modular-root .aoMassHubRibbonTitle{font:500 clamp(14px,2.6vw,19px)/1.3 Georgia,serif;letter-spacing:.09em;text-align:center;color:var(--ao-text-primary,#e7decf)}",
 "#ao-mass-modular-root .aoMassHubBack{height:44px;width:44px;border:1px solid rgba(199,167,119,.25);border-radius:11px;color:#e4d6c0;background:transparent;font-size:23px}",
 "#ao-mass-modular-root .aoMassHubStateRibbon{display:grid;grid-template-columns:minmax(0,1fr) minmax(100px,1.4fr) minmax(0,1fr);gap:10px;align-items:center;min-height:56px;padding:12px clamp(14px,4vw,36px);border-bottom:1px solid rgba(204,179,136,.2);background:#111923;color:#dcc7a4;font:500 clamp(10px,1.5vw,13px)/1.3 var(--ao-font-ui,system-ui,sans-serif);letter-spacing:.045em}",
 "#ao-mass-modular-root .aoMassHubStateRibbon span:nth-child(2){text-align:center;color:#f0dfc2;font-family:Georgia,serif;letter-spacing:.1em}",
 "#ao-mass-modular-root .aoMassHubStateRibbon span:last-child{text-align:right}",
 "#ao-mass-modular-root .aoMassHubProgress{height:3px;background:rgba(204,179,136,.12)}",
 "#ao-mass-modular-root .aoMassHubProgress span{display:block;height:100%;width:0;background:var(--ao-liturgical-accent,#c4a671);transition:width .15s ease}",
 "#ao-mass-modular-root .aoMassHubMain{max-width:950px;margin:auto;padding:clamp(17px,4vw,42px) clamp(14px,3vw,28px) 50px}",
 "#ao-mass-modular-root .aoMassHubIntro{margin:0 0 25px}",
 "#ao-mass-modular-root .aoMassHubKicker{font:600 10px/1.3 var(--ao-font-ui,system-ui,sans-serif);letter-spacing:.16em;color:var(--ao-liturgical-accent,#c6aa79)}",
 "#ao-mass-modular-root h1,#ao-mass-modular-root h2{font-family:Georgia,serif;font-weight:400;letter-spacing:.005em}",
 "#ao-mass-modular-root .aoMassHubIntro h1{font-size:clamp(28px,4vw,44px);line-height:1.15;margin:10px 0 12px}",
 "#ao-mass-modular-root .aoMassHubIntro p{max-width:690px;color:#acaeaa;margin:0;line-height:1.65}",
 "#ao-mass-modular-root .aoMassHubCurrent{border:1px solid var(--ao-rule,rgba(194,174,144,.3));border-radius:12px;background:linear-gradient(135deg,rgba(202,171,120,.09),transparent 80%);padding:clamp(16px,3vw,26px);margin-bottom:27px}",
 "#ao-mass-modular-root .aoMassHubCurrentHeading{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;color:#c6ad8b;letter-spacing:.12em}",
 "#ao-mass-modular-root .aoMassHubCurrent h2{font-size:clamp(20px,3vw,28px);margin:9px 0}",
 "#ao-mass-modular-root .aoMassHubCurrent p{font-size:12px;color:#b6b0a5;margin:0;overflow-wrap:anywhere}",
 "#ao-mass-modular-root .aoMassHubOptions,#ao-mass-modular-root .aoMassHubChoices{margin:0 0 27px}",
 "#ao-mass-modular-root .aoMassHubOptions h2,#ao-mass-modular-root .aoMassHubChoices h2{font-size:clamp(19px,3vw,23px);margin:0 0 13px}",
 "#ao-mass-modular-root .aoMassHubFormOptions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}",
 "#ao-mass-modular-root .aoMassHubSelect{border:1px solid rgba(200,174,137,.27);border-radius:10px;min-height:48px;padding:10px;color:#c7c7bf;background:#101820;font:500 12px/1.35 var(--ao-font-ui,system-ui,sans-serif)}",
 "#ao-mass-modular-root .aoMassHubSelect[aria-pressed=true]{color:#f0e3cb;border-color:#bf9f6d;background:rgba(198,170,121,.12)}",
 "#ao-mass-modular-root .aoMassHubModeRow{display:grid;grid-template-columns:minmax(70px,1fr) repeat(3,minmax(0,1fr));gap:6px;align-items:center;margin-top:16px}",
 "#ao-mass-modular-root .aoMassHubModeRow strong{color:#bcb7aa;font-weight:500;font-size:12px}",
 "#ao-mass-modular-root .aoMassHubCardGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}",
 "#ao-mass-modular-root .aoMassHubCard{position:relative;display:flex;flex-direction:column;gap:4px;min-height:106px;text-align:left;border:1px solid rgba(200,174,137,.26);border-radius:12px;padding:14px 32px 14px 16px;color:#eadfcd;background:#101820;overflow-wrap:anywhere}",
 "#ao-mass-modular-root .aoMassHubCard strong{font:500 clamp(16px,2.5vw,20px)/1.35 Georgia,serif}",
 "#ao-mass-modular-root .aoMassHubCard small{color:#a9aca9;font:400 11px/1.5 var(--ao-font-ui,system-ui,sans-serif)}",
 "#ao-mass-modular-root .aoMassHubArrow{position:absolute;top:10px;right:14px;color:#bea476}",
 "#ao-mass-modular-root .aoMassHubCard:hover{border-color:#b99b71;background:#17202a}",
 "#ao-mass-modular-root .aoMassHubOffice{padding:18px 20px;margin:27px 0 0;border-top:1px solid rgba(198,170,121,.25);border-bottom:1px solid rgba(198,170,121,.25);background:rgba(198,170,121,.035)}",
 "#ao-mass-modular-root .aoMassHubOffice h2{margin:10px 0;font-size:23px}",
 "#ao-mass-modular-root .aoMassHubOffice p{color:#b1b0a9;font-size:13px;margin:0 0 16px}",
 "#ao-mass-modular-root .aoMassHubAction{border:1px solid #c4aa7a;border-radius:9px;color:#e6d6b9;background:rgba(196,170,122,.09);padding:11px 18px;min-height:44px;font:500 13px/1.3 var(--ao-font-ui,system-ui,sans-serif)}",
 "#ao-mass-modular-root .aoMassHubFooter{max-width:950px;margin:auto;padding:14px 22px 34px;border-top:1px solid rgba(198,170,121,.14);color:#a9a9a1;font-size:11px}",
 "#ao-mass-modular-root .aoMassHubError{color:#edbbb3;background:rgba(124,44,42,.12);padding:11px;border:1px solid rgba(218,132,126,.28);border-radius:8px}",
 "#ao-mass-modular-root .aoMassHubTenebraeView{min-height:100%}",
 "#ao-mass-modular-root .aoTenebraeControls{max-width:960px;margin:14px auto 0;padding:0 14px;display:grid;gap:9px}",
 "#ao-mass-modular-root .aoTenebraeDays,#ao-mass-modular-root .aoTenebraeHours,#ao-mass-modular-root .aoTenebraeModes{display:flex;gap:5px}",
 "#ao-mass-modular-root .aoTenebraeControls button{flex:1 1 0;min-width:0;min-height:44px;padding:7px 5px;border:1px solid rgba(200,174,137,.25);border-radius:7px;background:#101820;color:#afafa6;font:500 12px/1.25 var(--ao-font-ui,system-ui,sans-serif)}",
 "#ao-mass-modular-root .aoTenebraeControls button[aria-pressed=true]{color:#eedaaf;border-color:#b79c6e;background:rgba(196,170,122,.1)}",
 "#ao-mass-modular-root .aoTenebraeJump{min-width:0;width:100%;max-width:600px;margin:auto;min-height:44px;padding:7px 10px;color:#e8ddc9;background:#101821;border:1px solid rgba(198,170,122,.3);border-radius:9px;font:500 13px/1.3 Georgia,serif}",
 "#ao-mass-modular-root .aoTenebraeFocus{max-width:810px;margin:0 auto;min-height:46vh;padding:25px clamp(16px,4vw,38px) 28px}",
 "#ao-mass-modular-root .aoTenebraeKicker{color:#b4a181;font-size:11px;letter-spacing:.13em}",
 "#ao-mass-modular-root .aoTenebraeHeading{color:#efdfc5;margin:10px 0 18px;font-size:clamp(22px,4vw,30px)}",
 "#ao-mass-modular-root .aoTenebraeCard{border:1px solid rgba(198,170,122,.18);border-radius:12px;background:rgba(13,20,29,.64);padding:clamp(18px,4vw,32px)}",
 "#ao-mass-modular-root .aoTenebraeKind{display:block;font-size:10px;letter-spacing:.14em;text-transform:uppercase;color:#b1a082;margin-bottom:16px}",
 "#ao-mass-modular-root .aoTenebraeReading{display:block;border:0;padding:0;text-align:left;white-space:pre-line;overflow-wrap:anywhere;width:100%;background:transparent;color:#f0e5d6;font:400 clamp(17px,2.8vw,22px)/1.8 Georgia,serif}",
 "#ao-mass-modular-root .aoTenebraeReading[lang=la]{color:#e8d7b9}",
 "#ao-mass-modular-root .aoTenebraeParallel{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:clamp(12px,3vw,34px)}",
 "#ao-mass-modular-root .aoTenebraeParallel>div{white-space:pre-line;overflow-wrap:anywhere;font:400 clamp(15px,2.4vw,19px)/1.7 Georgia,serif}",
 "#ao-mass-modular-root .aoTenebraeLatin{color:#e9dbc2}",
 "#ao-mass-modular-root .aoTenebraeTranslation{color:#bcc3c7}",
 "#ao-mass-modular-root .aoTenebraeMove{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:18px 0 0;color:#a4a69e;font-size:12px}",
 "#ao-mass-modular-root .aoTenebraeMove button{min-height:44px;padding:9px 12px;border-radius:8px;border:1px solid rgba(198,170,122,.28);background:transparent;color:#ded1b8}",
 "#ao-mass-modular-root .aoTenebraeMove button:disabled{opacity:.3}",
 "#ao-mass-modular-root .aoTenebraeProvenance{max-width:800px;margin:0 auto 36px;padding:12px 20px;color:#aca69a;font-size:12px;border-top:1px solid rgba(198,170,122,.24)}",
 "#ao-mass-modular-root .aoTenebraeProvenance summary{cursor:pointer;min-height:38px;color:#cfb58a}",
 "#ao-mass-modular-root :is(button,select):focus-visible{outline:2px solid #c9ad82;outline-offset:3px}",
 "#ao-mass-modular-root [hidden]{display:none!important}",
 "@media(max-width:470px){#ao-mass-modular-root .aoMassHubStateRibbon{font-size:9px;gap:5px;padding-inline:10px}#ao-mass-modular-root .aoMassHubCardGrid{grid-template-columns:1fr}#ao-mass-modular-root .aoMassHubFormOptions{gap:5px}#ao-mass-modular-root .aoMassHubModeRow{grid-template-columns:1fr repeat(3,minmax(0,1fr))}#ao-mass-modular-root .aoTenebraeParallel{grid-template-columns:1fr}#ao-mass-modular-root .aoTenebraeLatin{border-bottom:1px solid rgba(198,170,122,.2);padding-bottom:14px}#ao-mass-modular-root .aoTenebraeControls button{font-size:11px}}",
 "@media(prefers-reduced-motion:reduce){#ao-mass-modular-root *{transition:none!important;scroll-behavior:auto!important}}",
 ].join("\n");
 (doc.head??doc.documentElement).append(el);
 return true;
}
