export const CSE_DEBATES_070_104=Object.freeze({
"CSE070":{
  opposition:["If one spouse insists on contraception, the other either cooperates or destroys the marriage by refusing sex. It seems unfair to burden the unwilling spouse with the other’s choice.","Si un conjoint impose la contraception, l’autre doit soit coopérer, soit risquer de détruire le mariage en refusant les relations. Il paraît injuste de faire porter au conjoint réticent le poids du choix de l’autre."],
  appeal:["The case is genuinely difficult because marital duties, coercion, peace of the household and personal moral responsibility can collide.","Le cas est réellement difficile parce que devoirs conjugaux, contrainte, paix du foyer et responsabilité morale personnelle peuvent entrer en conflit."],
  concession:["The spouses’ responsibility is not automatically identical. The one who chooses contraception bears a responsibility the reluctant spouse may not share.","La responsabilité des époux n’est pas automatiquement identique. Celui qui choisit la contraception porte une responsabilité que le conjoint réticent peut ne pas partager."],
  breakpoint:["The mistake is assuming that any participation equals approval. Moral cooperation depends on intention, what each spouse actually chooses, and what can reasonably be avoided.","L’erreur est de supposer que toute participation équivaut à une approbation. La coopération morale dépend de l’intention, de ce que chacun choisit réellement et de ce qui peut raisonnablement être évité."],
  catholicCase:["Casti Connubii §59 explicitly distinguishes the spouse who chooses the disorder from one who, for a grave reason, reluctantly tolerates what is not approved. The reluctant spouse must not intend the contraceptive choice and should not simply confirm the other in it.","Casti Connubii §59 distingue explicitement le conjoint qui choisit le désordre de celui qui, pour une raison grave, tolère à contrecœur ce qu’il n’approuve pas. Le conjoint réticent ne doit pas vouloir le choix contraceptif ni simplement y confirmer l’autre."],
  counter:["Doesn’t this become a loophole allowing contraception whenever the marriage is tense?","Cela ne devient-il pas une échappatoire permettant la contraception chaque fois que le mariage est tendu ?"],
  response:["No. The exception concerns the responsibility of the non-choosing spouse, not the moral goodness of contraception. Grave reasons, reluctance and absence of approval matter; the contraceptive act itself is not reclassified as good.","Non. L’exception concerne la responsabilité du conjoint qui ne choisit pas, non la bonté morale de la contraception. Les raisons graves, la réticence et l’absence d’approbation comptent ; l’acte contraceptif lui-même n’est pas reclassé comme bon."],
  bottom:["Casti Connubii §59 addresses the reluctant spouse's responsibility under a grave reason, unwilling tolerance and an obligation of charity to seek to dissuade the partner. It does not license contraception or exempt every form of cooperation; serious cases require pastoral discernment.","Casti Connubii (§59) traite de la responsabilité du conjoint réticent en présence d’une raison grave, d’une tolérance à contrecœur et du devoir de charité de chercher à détourner l’autre du mal. Ce passage ne rend pas la contraception licite et n’excuse pas toute forme de coopération ; les situations graves exigent un discernement pastoral."]
},
"CSE071":{
  opposition:["Masturbation is private, common and apparently victimless. Calling it gravely wrong seems disproportionate, especially when it relieves tension without involving another person.","La masturbation est privée, fréquente et apparemment sans victime. La qualifier de gravement mauvaise paraît disproportionné, surtout lorsqu’elle soulage une tension sans impliquer autrui."],
  appeal:["Masturbation lacks some additional wrongs found in adultery, coercion or exploitation.","La masturbation ne comporte pas certains maux supplémentaires de l’adultère, de la contrainte ou de l’exploitation."],
  concession:["Its object differs from adultery, coercion or exploitation. An act's objective moral gravity must also be distinguished from the person's culpability: immaturity, anxiety, acquired habit or psychological factors may reduce deliberation. Neither automatic mortal guilt nor automatic absence of serious responsibility follows.","Son objet diffère de l’adultère, de la contrainte ou de l’exploitation. Il faut distinguer la gravité morale objective de la culpabilité personnelle : immaturité, angoisse, habitude acquise ou facteurs psychologiques peuvent diminuer le consentement réfléchi. Il ne s’ensuit ni culpabilité mortelle automatique ni absence systématique de responsabilité grave."],
  breakpoint:["The absence of an injured third party does not make an act morally neutral. Catholic sexual ethics also evaluates the use of the sexual faculty itself and whether sexual pleasure is integrated into conjugal self-giving.","L’absence d’une tierce victime ne rend pas un acte moralement neutre. La morale sexuelle catholique évalue aussi l’usage même de la faculté sexuelle et demande si le plaisir sexuel est intégré au don conjugal."],
  catholicCase:["Masturbation deliberately seeks sexual release outside that conjugal context. The judgment concerns the act’s object; responsibility in a particular occurrence is a separate question.","La masturbation recherche délibérément la décharge sexuelle hors de ce contexte conjugal. Le jugement porte sur l’objet de l’acte ; la responsabilité dans une occurrence particulière est une question distincte."],
  counter:["Why must sexual pleasure always be tied to marriage? Eating pleasure is not limited to one relationship.","Pourquoi le plaisir sexuel doit-il toujours être lié au mariage ? Le plaisir de manger n’est pas limité à une seule relation."],
  response:["Sexual pleasure belongs to a faculty whose human meaning is relational and generative in a way nutrition is not. The substantive disagreement is therefore whether sexuality has that objective relational and generative meaning.","Le plaisir sexuel appartient à une faculté dont la signification humaine est relationnelle et générative d’une manière que la nutrition ne l’est pas. Le désaccord de fond porte donc sur la question de savoir si la sexualité possède cette signification objective, relationnelle et générative."],
  bottom:["The Church judges deliberate masturbation objectively disordered, while Persona Humana §9 expressly requires individual assessment of freedom and habits. Frequency alone neither proves that the act is good nor measures a person's guilt.","L’Église juge la masturbation délibérée objectivement désordonnée, tout en exigeant, selon Persona Humana (§9), d’évaluer concrètement liberté et habitudes. La fréquence ne prouve ni la bonté de l’acte ni la culpabilité d’une personne."]
},
"CSE074":{
  opposition:["If adults freely consent to produce and view pornography, and coercion and harmful depictions are guarded against, why should the activity itself be wrong? Could the concern be exploitation and degrading use rather than every erotic depiction?","Si des adultes consentent librement à produire et regarder de la pornographie, et que la contrainte ainsi que les représentations nuisibles sont combattues, pourquoi l’activité elle-même serait-elle mauvaise ? Le problème ne serait-il pas plutôt l’exploitation et l’usage dégradant que toute représentation érotique ?"],
  appeal:["Coercion and exploitation are real and often serious evils in pornography, so focusing on consent is understandable.","La contrainte et l’exploitation sont des maux réels et souvent graves dans la pornographie ; se concentrer sur le consentement est donc compréhensible."],
  concession:["Consent removes one important possible wrong. Non-consensual or trafficked pornography is worse precisely because additional injustices are present.","Le consentement supprime un mal possible important. La pornographie non consentie ou issue de la traite est pire précisément parce que des injustices supplémentaires sont présentes."],
  breakpoint:["The inference from “consensual production” to “morally good use” does not follow. Pornography is also chosen as sexual spectacle for third-party arousal.","L’inférence de « production consentie » à « usage moralement bon » ne suit pas. La pornographie est aussi choisie comme spectacle sexuel destiné à l’excitation de tiers."],
  catholicCase:["Catholic teaching objects not only to coercion but to deliberate lust, exposure of sexual intimacy and treatment of persons or images as objects of sexual consumption.","L’enseignement catholique objecte non seulement à la contrainte mais aussi à la convoitise délibérée, à l’exposition de l’intimité sexuelle et au traitement des personnes ou images comme objets de consommation sexuelle."],
  counter:["What if the performers themselves enjoy exhibition and feel no degradation?","Et si les interprètes aiment eux-mêmes s’exhiber et ne se sentent pas dégradés ?"],
  response:["Subjective satisfaction does not settle the moral object. The question remains whether intentionally displaying sexual acts for others’ arousal respects the good of sexuality and personal dignity.","La satisfaction subjective ne tranche pas l’objet moral. La question demeure de savoir si l’exposition intentionnelle d’actes sexuels pour exciter autrui respecte le bien de la sexualité et la dignité personnelle."],
  bottom:["Consent matters greatly, but it does not transform sexual exhibition for consumption into a morally neutral act.","Le consentement compte beaucoup, mais il ne transforme pas l’exposition sexuelle destinée à la consommation en acte moralement neutre."]
},
"CSE076":{
  opposition:["The Catechism §2354 defines pornography by displaying real or simulated sexual acts to third parties. Private material created exclusively by spouses poses a different question: does recording intimacy remain prudent and respectful if it is never shared?","Le Catéchisme (§2354) définit la pornographie par l'exposition à des tiers d'actes sexuels réels ou simulés. Du matériel créé exclusivement par les époux pose une autre question : enregistrer leur intimité demeure-t-il prudent et respectueux sans aucune diffusion ?"],
  appeal:["The case is genuinely different from third-party pornography because no outside performer is being consumed and the sexual relationship itself is legitimate.","Le cas est réellement différent de la pornographie impliquant des tiers parce qu’aucun interprète extérieur n’est consommé et que la relation sexuelle elle-même est légitime."],
  concession:["It should not simply be labelled identical to commercial pornography. The Church has not issued a specific universal ruling on every form of private digital material between spouses.","Il ne faut pas simplement l’étiqueter comme identique à la pornographie commerciale. L’Église n’a pas donné de règle universelle spécifique sur toute forme de matériel numérique privé entre époux."],
  breakpoint:["The opposite error is assuming marital legitimacy makes every medium prudent or morally harmless.","L’erreur inverse serait de supposer que la légitimité matrimoniale rend tout média prudent ou moralement inoffensif."],
  catholicCase:["The analysis should ask whether the material remains integrated into marital intimacy, whether it objectifies the spouse, and whether creating a permanent, copyable sexual image exposes the spouse to serious privacy risks.","L’analyse doit demander si le matériel demeure intégré à l’intimité conjugale, s’il objectifie le conjoint et si la création d’une image sexuelle permanente et copiable expose le conjoint à de graves risques pour la vie privée."],
  counter:["If both spouses understand the risks and still consent, why should prudence become a moral issue?","Si les deux époux comprennent les risques et consentent quand même, pourquoi la prudence deviendrait-elle une question morale ?"],
  response:["Because knowingly creating a serious and unnecessary risk to a spouse’s dignity or privacy can itself be imprudent. Consent does not eliminate every duty of care.","Parce que créer sciemment un risque sérieux et inutile pour la dignité ou la vie privée du conjoint peut être imprudent. Le consentement n’élimine pas tout devoir de prudence."],
  bottom:["Displaying sexual acts to third parties falls under the clear prohibition of pornography. Private spousal images require distinct prudential judgment about chastity, dignity and privacy; the definition in §2354 does not itself decide every private digital practice.","L'exposition d'actes sexuels à des tiers relève de l'interdiction claire de la pornographie. Les images privées entre époux exigent un jugement prudentiel distinct sur la chasteté, la dignité et l'intimité ; la définition du §2354 ne tranche pas chaque pratique numérique privée."]
},
"CSE083":{
  opposition:["Margaret Farley argues that same-sex relationships and sexual activity may be evaluated by the same relational criteria as heterosexual ones (Just Love, p. 295, quoted in the CDF's 2012 Notification). If mutual love, fidelity and justice matter, why exclude a faithful same-sex couple?","Margaret Farley soutient que les relations et actes sexuels entre personnes de même sexe peuvent être jugés selon les mêmes critères relationnels que les autres (Just Love, p. 295, cité dans la Notification de la CDF de 2012). Si amour, fidélité et justice comptent, pourquoi exclure un couple fidèle de même sexe ?"],
  appeal:["Affection, loyalty, sacrifice and other relational goods can be genuinely present and should not be denied or mocked.","L’affection, la loyauté, le sacrifice et d’autres biens relationnels peuvent être réellement présents et ne doivent être ni niés ni ridiculisés."],
  concession:["Affection, loyalty and self-sacrifice are real goods wherever they occur. Fidelity makes a relationship morally different from promiscuity.","L’affection, la loyauté et le sacrifice de soi sont de vrais biens partout où ils se trouvent. La fidélité rend une relation moralement différente de la promiscuité."],
  breakpoint:["The disputed premise is that these goods exhaust the moral meaning of sexual acts. Catholicism says the bodily form of the act and its relation to marriage and generation also matter.","La prémisse disputée est que ces biens épuisent le sens moral des actes sexuels. Le catholicisme affirme que la forme corporelle de l’acte et son rapport au mariage et à la génération comptent aussi."],
  catholicCase:["The CDF's 1986 letter and Persona Humana §8 distinguish attraction, which is not a personal sin by itself, from deliberately chosen sexual acts. Genuine affection and fidelity are not denied; the specific Catholic argument is that sexual union is ordered to male-female conjugal communion, and those relational goods do not change the act's moral object.","La lettre de la CDF de 1986 et Persona Humana (§8) distinguent l'attirance, qui n'est pas en elle-même un péché personnel, des actes sexuels librement choisis. L'affection et la fidélité véritables ne sont pas niées ; l'argument catholique tient que l'union sexuelle est ordonnée à la communion conjugale homme-femme et que ces biens relationnels ne changent pas l'objet moral de l'acte."],
  counter:["Isn’t that just privileging biology over love?","Cela ne revient-il pas à privilégier la biologie sur l’amour ?"],
  response:["Embodied sexuality is part of human love rather than raw biology added from outside. If the body’s sexual structure is morally meaningful, love cannot simply redefine it.","La sexualité incarnée fait partie de l’amour humain au lieu d’être une biologie brute ajoutée de l’extérieur. Si la structure sexuelle du corps possède une signification morale, l’amour ne peut simplement la redéfinir."],
  bottom:["The Church need not deny the relationship’s genuine goods to maintain that those goods do not by themselves make every sexual expression morally ordered.","L’Église n’a pas besoin de nier les biens réels de la relation pour maintenir que ces biens ne rendent pas, à eux seuls, toute expression sexuelle moralement ordonnée."]
},
"CSE084":{
  opposition:["A serious challenge to the procreative account of marriage is that sterile heterosexual spouses can marry although they cannot conceive. If actual fertility is not required, why exclude a same-sex couple on procreative grounds? This particular analogy is illustrative, not a verified quotation from Margaret Farley.","Une objection sérieuse au fondement procréatif du mariage constate que des époux stériles peuvent se marier sans pouvoir concevoir. Si la fécondité effective n'est pas requise, pourquoi exclure un couple de même sexe au nom de la procréation ? Cette analogie est illustrative : elle n'est pas une citation vérifiée de Margaret Farley."],
  appeal:["Actual conception is not required for every marriage or every conjugal act.","La conception effective n’est pas requise pour chaque mariage ni pour chaque acte conjugal."],
  concession:["A marriage may be permanently infertile and remain fully valid.","Un mariage peut être définitivement stérile et rester pleinement valide."],
  breakpoint:["Inability to achieve an outcome is not the same as absence of the type of bodily union naturally ordered to that outcome.","L’incapacité à atteindre un résultat n’est pas la même chose que l’absence du type d’union corporelle naturellement ordonné à ce résultat."],
  catholicCase:["CIC can. 1084 §3 explicitly states that sterility neither prohibits nor invalidates marriage, whereas §1 separately addresses antecedent and perpetual incapacity for intercourse. The Catholic account concerns a male-female conjugal kind of union, not a fertility test or the value of the spouses as persons.","Le CIC (can. 1084 §3) affirme expressément que la stérilité n'empêche ni n'invalide le mariage, tandis que le §1 traite séparément de l'incapacité antécédente et perpétuelle à l'acte conjugal. L'argument catholique porte sur le type d'union conjugale homme-femme, non sur un examen de fécondité ni sur la valeur personnelle des époux."],
  counter:["But why should “type of act” matter if the result is known to be impossible?","Pourquoi le « type d’acte » devrait-il compter si l’on sait que le résultat est impossible ?"],
  response:["Because moral meaning is not determined solely by outcome. We routinely distinguish acts by what they are, even when circumstances prevent their ordinary effects. Catholic marriage applies the same action-theory distinction here.","Parce que la signification morale n’est pas déterminée uniquement par le résultat. Nous distinguons couramment les actes selon ce qu’ils sont, même lorsque les circonstances empêchent leurs effets ordinaires. Le mariage catholique applique ici la même distinction de théorie de l’action."],
  bottom:["Sterility is failure of an outcome within a generative kind of union; it is not the absence of that kind of union.","La stérilité est l’échec d’un résultat au sein d’un type d’union générative ; elle n’est pas l’absence de ce type d’union."]
},
"CSE087":{
  opposition:["The American Psychological Association condemns stigma, discrimination and violence against sexual minorities and reports that such prejudice can harm mental health. If religious language is used to stigmatize gay people, is the Church sufficiently confronting the consequences of that language?","L'American Psychological Association condamne la stigmatisation, la discrimination et les violences contre les minorités sexuelles et relève leurs conséquences possibles sur la santé psychique. Si un langage religieux sert à stigmatiser des personnes homosexuelles, l'Église en affronte-t-elle suffisamment les conséquences ?"],
  appeal:["The concern is serious because moral language can be weaponized, and people have suffered contempt, rejection and violence under religious pretexts.","La préoccupation est sérieuse parce que le langage moral peut être utilisé comme arme, et des personnes ont subi mépris, rejet et violence sous des prétextes religieux."],
  concession:["Cruelty, violence and unjust discrimination are wrong. The 1986 CDF letter explicitly rejects violent malice and insists on personal dignity.","La cruauté, la violence et la discrimination injuste sont mauvaises. La lettre de 1986 de la CDF rejette explicitement la malveillance violente et insiste sur la dignité personnelle."],
  breakpoint:["The further inference is that a moral judgment about an act is therefore itself hatred. That would make many forms of moral disagreement impossible in principle.","L’inférence supplémentaire est qu’un jugement moral sur un acte serait donc lui-même haineux. Cela rendrait en principe impossible de nombreuses formes de désaccord moral."],
  catholicCase:["The 1986 CDF letter §10 condemns hostile speech, violence and attacks on dignity; Dignitas Infinita §55 again condemns unjust discrimination, imprisonment, torture and killing because of sexual orientation. These obligations coexist with the Church's sexual ethics. Neither moral disagreement nor a claim about conscience excuses mistreatment.","La lettre de la CDF de 1986 (§10) condamne les propos malveillants, la violence et l'atteinte à la dignité ; Dignitas Infinita (§55) condamne aussi les discriminations injustes, l'emprisonnement, la torture et la mise à mort fondés sur l'orientation sexuelle. Ces obligations subsistent avec la morale sexuelle de l'Église. Ni le désaccord moral ni la conscience ne justifient de maltraiter autrui."],
  counter:["But in practice the distinction often feels hollow when the teaching denies recognition to a person’s relationship.","Mais en pratique la distinction paraît souvent vide lorsque l’enseignement refuse de reconnaître la relation d’une personne."],
  response:["That pastoral failure can be real and should be confronted. It does not settle the underlying moral argument. The correct test is whether the teaching can be defended without contempt and whether communities actually treat persons according to the dignity they profess.","Cet échec pastoral peut être réel et doit être affronté. Il ne tranche pas l’argument moral sous-jacent. Le bon test est de savoir si l’enseignement peut être défendu sans mépris et si les communautés traitent réellement les personnes selon la dignité qu’elles professent."],
  bottom:["Moral disagreement does not license dehumanization. Nor does the existence of stigma by itself prove the moral judgment false.","Le désaccord moral n’autorise pas la déshumanisation. L’existence de stigmatisation ne prouve pas non plus, à elle seule, que le jugement moral soit faux."]
},
"CSE088":{
  opposition:["The American Psychological Association explicitly says same-sex orientation is not a mental disorder and opposes efforts that promise to change orientation. Does a traditional moral account need to change if it once depended on assumptions that homosexuality is a psychiatric disease or that orientation is freely chosen?","L'American Psychological Association affirme expressément que l'orientation homosexuelle n'est pas un trouble mental et rejette les interventions promettant de la modifier. Une morale traditionnelle doit-elle être révisée si elle s'appuyait sur la maladie psychiatrique ou sur le choix volontaire de cette orientation ?"],
  appeal:["Scientific corrections matter. A moral argument that depends on false claims about pathology or voluntariness must be revised.","Les corrections scientifiques comptent. Un argument moral fondé sur de fausses affirmations concernant la pathologie ou le caractère volontaire doit être révisé."],
  concession:["Psychology can correct mistaken assumptions about development, choice, distress and mental health. Same-sex attraction should not be treated as personal guilt merely because it exists.","La psychologie peut corriger des présupposés erronés sur le développement, le choix, la détresse et la santé mentale. L’attirance envers le même sexe ne doit pas être traitée comme culpabilité personnelle du seul fait qu’elle existe."],
  breakpoint:["The moral judgment on sexual acts does not depend on classifying a sexual orientation as a psychiatric disease.","Le jugement moral sur les actes sexuels ne dépend pas de la classification d’une orientation sexuelle comme maladie psychiatrique."],
  catholicCase:["A same-sex orientation is not a psychiatric diagnosis or, by itself, a personally culpable choice. The Church's evaluation of sexual acts invokes its account of marriage and their moral object rather than an alleged medical disease. Empirical corrections are binding for factual pastoral claims: clinicians should not promise orientation change or treat a person as ill for an orientation.","Une orientation homosexuelle n'est pas un diagnostic psychiatrique ni, en elle-même, un choix personnellement coupable. Le jugement de l'Église sur les actes sexuels repose sur sa compréhension du mariage et de leur objet moral, non sur une prétendue maladie. Les corrections empiriques s'imposent aux affirmations pastorales factuelles : il ne faut ni promettre un changement d'orientation ni pathologiser une personne à cause de son orientation."],
  counter:["But if psychology shows same-sex orientation is stable and unchosen, doesn’t requiring celibacy become unreasonable?","Mais si la psychologie montre qu’une orientation homosexuelle est stable et non choisie, exiger la continence ne devient-il pas déraisonnable ?"],
  response:["Unchosen inclination does not by itself determine which acts are morally permissible. Catholicism asks all unmarried people, whatever their attractions, to practice chastity. The pastoral burden may differ, but the moral principle is not inferred from whether the attraction was chosen.","Une inclination non choisie ne détermine pas à elle seule quels actes sont moralement permis. Le catholicisme demande à toutes les personnes non mariées, quelles que soient leurs attirances, de vivre la chasteté. Le fardeau pastoral peut différer, mais le principe moral ne découle pas du fait que l’attirance soit choisie ou non."],
  bottom:["Psychology can and should correct factual errors. It does not by itself replace the moral anthropology on which the Catholic judgment rests.","La psychologie peut et doit corriger les erreurs factuelles. Elle ne remplace pas à elle seule l’anthropologie morale sur laquelle repose le jugement catholique."]
},
"CSE089":{
  opposition:["Margaret Farley argued that legal recognition of civil unions and same-sex marriage could help combat stigma and provide comparable social recognition (Just Love, p. 293, quoted in the CDF's 2012 Notification). Why should a civil state with citizens of different religions reject that equal-recognition case?","Margaret Farley défendait la reconnaissance juridique des unions civiles et du mariage entre personnes de même sexe pour lutter contre la stigmatisation et favoriser une reconnaissance sociale comparable (Just Love, p. 293, cité dans la Notification de la CDF de 2012). Pourquoi un État composé de citoyens de religions diverses devrait-il écarter cet argument d'égalité ?"],
  appeal:["Private religious rules and the coercive power of civil law are distinct; legal restrictions require reasons appropriate to the common good and public justice.","Les règles religieuses privées et le pouvoir coercitif de la loi civile sont distincts ; les restrictions juridiques exigent des raisons propres au bien commun et à la justice publique."],
  concession:["A civil-law argument cannot simply be “the Church forbids it.” It must explain what public institution marriage is and why its definition matters.","Un argument de droit civil ne peut se réduire à « l’Église l’interdit ». Il doit expliquer ce qu’est l’institution publique du mariage et pourquoi sa définition compte."],
  breakpoint:["The dispute is not whether one same-sex wedding directly damages one heterosexual marriage. It is whether marriage law merely registers private affection or publicly defines an institution connected to sexual difference, family and generation.","Le désaccord ne porte pas sur le fait qu’un mariage de même sexe endommagerait directement un mariage hétérosexuel. Il porte sur la question de savoir si le droit du mariage enregistre seulement une affection privée ou définit publiquement une institution liée à la différence sexuelle, à la famille et à la génération."],
  catholicCase:["The CDF’s 2003 reasoning is institutional: changing the legal definition changes what the state recognizes as marriage. Its force therefore depends on the public significance attributed to sexual difference and parenthood.","Le raisonnement de la CDF en 2003 est institutionnel : modifier la définition juridique change ce que l’État reconnaît comme mariage. Sa force dépend donc de la signification publique attribuée à la différence sexuelle et à la parentalité."],
  counter:["But the state already recognizes infertile and childless marriages, so procreation cannot be the public purpose.","Mais l’État reconnaît déjà les mariages stériles et sans enfants ; la procréation ne peut donc être le but public."],
  response:["A serious civil-law argument cannot rest on 'the Church prohibits it.' The CDF's 2003 case is that law gives public meaning to the institution of marriage and its orientation toward family and generation. Farley's competing claims about recognition and anti-discrimination must be answered on public-law grounds, not dismissed as if they denied the existence of family goods.","Un argument de droit civil sérieux ne peut se limiter à « l'Église l'interdit ». La CDF (2003) soutient que la loi définit publiquement le mariage et son orientation familiale et procréative. Les arguments contraires de Farley sur la reconnaissance et la non-discrimination demandent une réponse sur le terrain du bien commun et du droit, non le soupçon qu'ils ignorent les biens familiaux."],
  bottom:["The Catholic civil argument is about the public definition of marriage, not the claim that a same-sex couple directly harms a particular other marriage.","L’argument civil catholique porte sur la définition publique du mariage, non sur l’idée qu’un couple de même sexe nuirait directement à un mariage particulier."]
},
"CSE093":{
  opposition:["The APA distinguishes biological sex from culturally variable gender roles and recognizes atypical development of sex characteristics. If these concepts differ, which parts of the traditional account describe bodily reality and which merely describe social expectations?","L'APA distingue le sexe biologique des rôles de genre variables selon les cultures et reconnaît des développements atypiques des caractères sexuels. Si ces notions diffèrent, qu'est-ce qui, dans la tradition, décrit le corps et qu'est-ce qui n'est qu'attente sociale ?"],
  appeal:["Many expectations attached to men and women are cultural rather than biologically necessary.","De nombreuses attentes attachées aux hommes et aux femmes sont culturelles plutôt que biologiquement nécessaires."],
  concession:["Gender roles, dress, occupations and social expectations can vary and can contain unjust stereotypes.","Les rôles de genre, les vêtements, les professions et les attentes sociales peuvent varier et contenir des stéréotypes injustes."],
  breakpoint:["Clothing, temperament and occupations do not determine whether someone is male or female. The moral significance of embodied reproductive differences must be distinguished from historically contingent social expectations. Neither cultural variation nor atypical sex development by itself settles a normative judgment.","Les vêtements, le tempérament et les professions ne déterminent pas le sexe d’une personne. La portée morale des différences corporelles liées à la reproduction doit être distinguée des attentes sociales historiquement contingentes. Ni la diversité culturelle ni un développement sexuel atypique ne tranchent à eux seuls un jugement normatif."],
  catholicCase:["Dignitas Infinita §§55–59 expressly distinguishes biological sex from socially constructed roles while insisting that they cannot be treated as wholly unrelated. The moral argument should not mistake clothing, occupations or temperament for the sexed body. People with differences of sex development merit individualized respectful care, not forced classification from stereotypes.","Dignitas Infinita (§§55–59) distingue explicitement le sexe biologique des rôles sociaux construits tout en refusant de les rendre entièrement étrangers l'un à l'autre. Il ne faut pas confondre vêtements, métiers ou tempérament avec le corps sexué. Les personnes présentant des variations du développement sexuel méritent des soins personnalisés et respectueux, non une classification imposée par des stéréotypes."],
  counter:["But biology itself contains atypical development and ambiguity.","Mais la biologie elle-même comporte des développements atypiques et des ambiguïtés."],
  response:["Variations in sex development complicate some classifications and call for careful individualized medical assessment. They do not establish that bodily sex generally is created by social agreement. Nor should any person with atypical sex characteristics be reduced to a diagnosis or used merely as an example in an ideological dispute.","Les variations du développement sexuel peuvent compliquer certaines classifications et demandent une évaluation médicale individualisée et rigoureuse. Elles ne démontrent pas que le sexe corporel serait généralement créé par convention sociale. Il ne faut pas davantage réduire une personne présentant des caractéristiques sexuelles atypiques à un diagnostic ou en faire un simple exemple dans une querelle idéologique."],
  bottom:["Cultural gender roles can be flexible without making embodied sex a social invention.","Les rôles culturels de genre peuvent être flexibles sans faire du sexe corporel une invention sociale."]
},
"CSE094":{
  opposition:["The APA's 2024 policy supports noncoercive, individualized, evidence-based care for people experiencing gender dysphoria, including access to gender-affirming services, while recognizing limits in current knowledge. How should that clinical position be weighed against Catholic teaching about the significance of bodily sex?","La politique de l'APA (2024) défend des soins non coercitifs, individualisés et fondés sur les preuves pour les personnes souffrant de dysphorie de genre, y compris l'accès à des soins d'affirmation, tout en reconnaissant les limites actuelles du savoir. Comment confronter cette position clinique à l'enseignement catholique sur le sexe corporel ?"],
  appeal:["The suffering is real and should never be dismissed as mere ideology. Clinical outcomes matter.","La souffrance est réelle et ne doit jamais être rejetée comme simple idéologie. Les résultats cliniques comptent."],
  concession:["People experiencing serious distress deserve respect, competent care and protection from ridicule or neglect.","Les personnes éprouvant une détresse grave méritent respect, soins compétents et protection contre la moquerie ou l’abandon."],
  breakpoint:["The moral conclusion does not follow solely from the existence of distress. Treatment still requires a judgment about what the body means and what interventions genuinely heal rather than merely conform the body to a self-conception.","La conclusion morale ne découle pas de la seule existence de la détresse. Le traitement exige encore un jugement sur la signification du corps et sur les interventions qui guérissent réellement plutôt que de conformer le corps à une conception de soi."],
  catholicCase:["Catholic anthropology treats the body as part of the person, not as raw material external to identity. That makes bodily sex morally relevant while leaving empirical medicine responsible for evaluating distress, risks and outcomes.","L’anthropologie catholique considère le corps comme partie de la personne, non comme une matière brute extérieure à l’identité. Le sexe corporel est donc moralement pertinent, tandis que la médecine empirique reste chargée d’évaluer la détresse, les risques et les résultats."],
  counter:["But if an intervention demonstrably reduces suffering, why should anthropology override clinical benefit?","Mais si une intervention réduit manifestement la souffrance, pourquoi l’anthropologie devrait-elle l’emporter sur le bénéfice clinique ?"],
  response:["Relieving genuine distress matters, as do informed consent, clinical effectiveness, contraindications, uncertainty and follow-up. Dignitas Infinita §60 makes a distinct moral argument about the unity of body and person. Neither citing 'compassion' nor invoking a medical society settles every treatment choice; serious cases call for skilled clinical and, if desired, competent Catholic ethical care without humiliation or neglect.","Soulager une souffrance réelle importe, de même que le consentement éclairé, l'efficacité clinique, les contre-indications, l'incertitude et le suivi. Dignitas Infinita (§60) avance un argument moral distinct sur l'unité du corps et de la personne. Ni la seule « compassion » ni l'autorité d'une société médicale ne tranchent chaque traitement ; les situations difficiles demandent des soins compétents et, si souhaité, un conseil moral catholique, sans humiliation ni abandon."],
  bottom:["Compassion requires serious care for distress. It does not by itself settle the disputed anthropology or the morality of every proposed intervention.","La compassion exige une prise en charge sérieuse de la détresse. Elle ne tranche pas à elle seule l’anthropologie disputée ni la moralité de toute intervention proposée."]
},
"CSE095":{
  opposition:["The APA's clinical guidance emphasizes affirming care and warns that rejection and discrimination can compound distress. Does respectful everyday language sometimes require accommodation, even where the speaker does not share every philosophical assumption about gender identity?","Les recommandations cliniques de l'APA soulignent l'importance de soins affirmatifs et mettent en garde contre l'aggravation de la détresse par le rejet et la discrimination. Le respect dans la conversation peut-il exiger des accommodements, même sans partager toute l'anthropologie de l'identité de genre ?"],
  appeal:["Language can wound, and gratuitous confrontation or humiliation is contrary to charity.","Le langage peut blesser, et la confrontation gratuite ou l’humiliation sont contraires à la charité."],
  concession:["Catholics should avoid mockery, cruelty and reducing a person to a disputed identity claim. Context and relationship matter greatly in how one speaks.","Les catholiques doivent éviter la moquerie, la cruauté et la réduction d’une personne à une revendication identitaire disputée. Le contexte et la relation comptent beaucoup dans la manière de parler."],
  breakpoint:["The disputed inference is that respect requires intellectual assent to the underlying claim about identity and bodily sex.","L’inférence disputée est que le respect exige un assentiment intellectuel à l’affirmation sous-jacente sur l’identité et le sexe corporel."],
  catholicCase:["Catholic ethics distinguishes respect for the person from agreement with every proposition the person holds about himself or herself. Charity can require tact without requiring falsehood.","La morale catholique distingue le respect de la personne de l’accord avec toute proposition qu’elle tient sur elle-même. La charité peut exiger du tact sans exiger le mensonge."],
  counter:["But refusing affirmation may have foreseeable psychological costs.","Mais refuser l’affirmation peut avoir des coûts psychologiques prévisibles."],
  response:["The Church's duty of truth does not oblige anyone to provoke confrontations, reveal private medical information or deny ordinary courtesy. The moral evaluation of a particular word, form of address or accommodation depends on what is actually asserted, intended and understood, and on the person's vulnerability. Dignitas Infinita §§55–60 does not itself issue a universal pronoun rule.","Le devoir de vérité n'oblige ni à provoquer des confrontations, ni à révéler des données médicales privées, ni à refuser la courtoisie ordinaire. Le jugement sur un mot, une formule d'adresse ou un accommodement dépend de ce qu'il affirme réellement, de l'intention, de la compréhension et de la vulnérabilité de la personne. Dignitas Infinita (§§55–60) n'édicte pas de règle universelle sur les pronoms."],
  bottom:["Respect never requires contempt; neither does it necessarily require assent. The challenge is truthful charity, not maximal confrontation.","Le respect n’exige jamais le mépris ; il n’exige pas nécessairement non plus l’assentiment. Le défi est une charité véridique, non la confrontation maximale."]
},
"CSE096":{
  opposition:["WPATH's Standards of Care Version 8 offers clinical criteria for individualized gender-related medical treatment and emphasizes informed decision-making. A serious opposing case rests on the treatment of persistent distress and potential quality-of-life benefits, not merely on unrestricted consumer autonomy.","Les Standards of Care, version 8, de WPATH présentent des critères cliniques pour des soins liés au genre individualisés et insistent sur la décision éclairée. L'argument adverse sérieux invoque le traitement d'une détresse persistante et les bénéfices éventuels pour la qualité de vie, non la seule autonomie illimitée d'un consommateur."],
  appeal:["Adult autonomy is important, and not every medical intervention must restore a diseased organ in a narrow sense.","L’autonomie adulte est importante, et toute intervention médicale ne doit pas nécessairement restaurer un organe malade au sens étroit."],
  concession:["Medical ethics legitimately considers suffering and quality of life, not only survival.","L’éthique médicale considère légitimement la souffrance et la qualité de vie, non seulement la survie."],
  breakpoint:["Autonomy does not by itself make every requested intervention therapeutic. Medicine still asks what counts as health, what harms are imposed and whether the intervention treats a pathology or alters healthy sexual characteristics to conform to an asserted identity.","L’autonomie ne rend pas à elle seule thérapeutique toute intervention demandée. La médecine demande encore ce qui compte comme santé, quels dommages sont imposés et si l’intervention traite une pathologie ou modifie des caractères sexuels sains pour les conformer à une identité affirmée."],
  catholicCase:["Dignitas Infinita §60 holds that sex-change interventions as ordinarily understood risk undermining the dignity of the sexed body; it explicitly excludes medically indicated treatment of genital abnormalities present at birth or arising later from that category. This principle is not a substitute for diagnosis, clinical risk assessment, distinctions among treatments, or evaluation of particular medical circumstances.","Dignitas Infinita (§60) estime que les interventions de changement de sexe, au sens retenu dans ce texte, risquent en règle générale d'atteindre la dignité du corps sexué ; il exclut expressément de cette catégorie les soins destinés à résoudre des anomalies génitales présentes à la naissance ou apparues ensuite. Ce principe ne remplace ni le diagnostic, ni l'évaluation clinique des risques, ni la distinction entre traitements et circonstances médicales particulières."],
  counter:["Why privilege the original body if changing it produces a more livable life?","Pourquoi privilégier le corps d’origine si le modifier produit une vie plus vivable ?"],
  response:["Because Catholic anthropology does not treat the body as external material owned by an inner self. The body participates in personal identity. A critic must therefore challenge that anthropology rather than appeal to autonomy alone.","Parce que l’anthropologie catholique ne traite pas le corps comme une matière extérieure possédée par un moi intérieur. Le corps participe à l’identité personnelle. Le critique doit donc contester cette anthropologie plutôt que faire appel à la seule autonomie."],
  bottom:["Autonomy, quality of life and relief of distress are important clinical considerations. The Catholic judgment requires a separate analysis of the intervention's object and bodily effects under Dignitas Infinita §60, including its explicit exception for treatment of genital abnormalities; no single blanket conclusion follows for every clinical scenario.","Autonomie, qualité de vie et soulagement de la souffrance sont des critères cliniques importants. Le jugement catholique exige d'examiner séparément l'objet et les effets corporels de chaque intervention à la lumière de Dignitas Infinita (§60), y compris l'exception explicite concernant les anomalies génitales ; tous les cas cliniques ne se résolvent pas par une affirmation générale."]
},
"CSE101":{
  opposition:["Infertility treatment seeks to help patients have children, and informed reproductive choices deserve careful counseling. Does the good of becoming parents justify IVF even when fertilization takes place outside the spouses’ own act?","Le traitement de l’infertilité cherche à aider les personnes à avoir des enfants et les décisions reproductives demandent une information attentive. Le bien de devenir parents justifie-t-il la FIV même lorsque la fécondation se produit hors de l’acte propre des époux ?"],
  appeal:["The desire for a child is good, infertility can be deeply painful and medical assistance is not wrong merely because it is technologically advanced.","Le désir d’un enfant est bon, l’infertilité peut être profondément douloureuse et l’aide médicale n’est pas mauvaise simplement parce qu’elle est technologiquement avancée."],
  concession:["Catholic teaching explicitly permits many treatments that restore fertility or assist the marital act. It does not reject technology as such.","L’enseignement catholique permet explicitement de nombreux traitements qui restaurent la fertilité ou assistent l’acte conjugal. Il ne rejette pas la technologie en tant que telle."],
  breakpoint:["The crucial distinction is between assisting the spouses’ own conjugal act and replacing it as the cause of conception.","La distinction décisive est celle entre assister l’acte conjugal propre aux époux et le remplacer comme cause de la conception."],
  catholicCase:["Donum Vitae judges IVF morally illicit even apart from embryo loss, because laboratory fertilization replaces the spouses’ conjugal act rather than assisting it. Dignitas Personae §§12–16 confirms that technology assisting fertility can be permitted, while procedures substituting for the conjugal act are excluded. Additional practices—surplus embryos, freezing and selection—raise further grave concerns.","Donum Vitae juge la FIV moralement illicite même indépendamment de la perte d’embryons, car la fécondation en laboratoire se substitue à l’acte conjugal des époux au lieu de l’assister. Dignitas Personae (§§12–16) confirme que les techniques aidant la fertilité peuvent être permises, tandis que celles qui remplacent l’acte conjugal sont exclues. Les embryons surnuméraires, leur congélation et leur sélection soulèvent d’autres graves difficultés."],
  counter:["But why should the manner of conception matter if the child is loved and the parents are married?","Pourquoi le mode de conception devrait-il compter si l’enfant est aimé et que les parents sont mariés ?"],
  response:["Because a good result does not make every means equivalent. Catholicism argues that procreation has a personal meaning: the child should arise from the spouses’ mutual bodily self-gift rather than be produced by a third-party technical act.","Parce qu’un bon résultat ne rend pas tous les moyens équivalents. Le catholicisme affirme que la procréation possède une signification personnelle : l’enfant devrait naître du don corporel mutuel des époux plutôt que d’être produit par un acte technique de tiers."],
  bottom:["IVF is not rejected out of hostility to children or medicine. The moral concerns are the substitution of technique for the conjugal act and, often, additional wrongs toward embryos.","La FIV n’est rejetée ni par hostilité envers les enfants ni envers la médecine. Les difficultés morales concernent la substitution de la technique à l’acte conjugal et, souvent, des torts supplémentaires envers les embryons."]
},
"CSE104":{
  opposition:["Surrogacy can be an act of generosity. If a woman freely carries a child for an infertile couple without exploitation or payment, why condemn her sacrifice?","La gestation pour autrui peut être un acte de générosité. Si une femme porte librement un enfant pour un couple stérile sans exploitation ni paiement, pourquoi condamner son sacrifice ?"],
  appeal:["Altruistic surrogacy avoids payment and may reduce some commercial pressures, but unpaid arrangements can still involve family pressure, power imbalances or conflict over medical decisions. Sincere compassion for an infertile family can be real without eliminating those risks.","La gestation pour autrui altruiste exclut la rémunération et peut réduire certaines pressions commerciales, mais des arrangements non rémunérés peuvent encore comporter des pressions familiales, des rapports de pouvoir inégaux ou des conflits sur les décisions médicales. Une compassion sincère envers une famille infertile peut exister sans supprimer ces risques."],
  concession:["The good intention of helping an infertile couple can be real. Payment is not the sole issue, and even a well-safeguarded unpaid arrangement requires examining the intentional separation of gestation, birth and upbringing.","La bonne intention d’aider un couple infertile peut être réelle. La rémunération n’est pas le seul enjeu et, même avec des garanties dans un arrangement bénévole, il reste à examiner la séparation intentionnelle entre gestation, naissance et éducation."],
  breakpoint:["The inference is that absence of payment removes every moral issue. Surrogacy also deliberately separates gestation from the woman who will rear the child and subjects pregnancy to an agreement that the child will be handed over.","L’inférence est que l’absence de paiement supprime tout problème moral. La gestation pour autrui sépare aussi délibérément la grossesse de la femme qui élèvera l’enfant et soumet la grossesse à un accord prévoyant la remise de l’enfant."],
  catholicCase:["Donum Vitae II.A.3 rejects surrogate motherhood because its planned separation of gestation and the child's parental origin contradicts marital unity and the obligations owed to the child. The ASRM Ethics Committee's 2023 defense of gestational carriers, with informed consent and protective safeguards, meets concerns about coercion but does not answer the distinct Catholic objection to designing that separation in the first place.","Donum Vitae, II.A.3, rejette la gestation pour autrui parce que la séparation organisée entre gestation et origine parentale de l’enfant contredit l’unité matrimoniale et les devoirs envers l’enfant. Le comité d’éthique de l’ASRM (2023) invoque le consentement éclairé et des garanties contre la contrainte ; ces protections n'annulent cependant pas la séparation délibérée entre gestation et parenté qui rend l'arrangement moralement illicite."],
  counter:["But adoption also separates biological and social parenthood.","Mais l’adoption sépare elle aussi parentalité biologique et sociale."],
  response:["Adoption responds to an existing deprivation after the child already exists; surrogacy intentionally creates the separation as part of the plan for conception and birth. That difference between remedying a loss and designing it is morally significant.","L’adoption répond à une privation déjà existante après que l’enfant existe ; la gestation pour autrui crée intentionnellement la séparation comme partie du projet de conception et de naissance. Cette différence entre réparer une perte et la planifier est moralement significative."],
  bottom:["Altruistic motive can remove commercial exploitation, but it does not remove the intentional fragmentation of gestation, motherhood and parenthood.","Un motif altruiste peut supprimer l’exploitation commerciale, mais il ne supprime pas la fragmentation intentionnelle de la gestation, de la maternité et de la parentalité."]
}
});
