export const CSE_DEBATES_035_064=Object.freeze({
"CSE035":{
  opposition:["Couples may wish to learn daily habits and financial compatibility before a permanent commitment. In Pew's 2019 US survey, 23% of cohabiters cited testing the relationship as a major reason for moving in. Does that practical motive justify cohabitation?","Les couples peuvent vouloir connaître leurs habitudes et leur compatibilité financière avant un engagement définitif. Dans l'enquête américaine Pew de 2019, 23 % des cohabitants citaient la mise à l'épreuve de la relation parmi leurs raisons majeures. Ce motif pratique justifie-t-il la cohabitation ?"],
  appeal:["Learning compatibility is genuinely important, and the Pew survey describes people's motives. It does not demonstrate that cohabitation causes better marital outcomes.","Connaître sa compatibilité est réellement important ; l'enquête Pew décrit les motifs déclarés, mais ne démontre pas que la cohabitation améliore causalement le devenir d'un mariage."],
  concession:["Couples should learn one another’s habits, expectations, weaknesses and practical compatibility before marriage.","Les couples doivent apprendre à connaître les habitudes, les attentes, les faiblesses et la compatibilité pratique de l’autre avant le mariage."],
  breakpoint:["Simulating married life is not established as the best or necessary way to discern marriage. Sexual relations, shared housing, scandal and practical dependence are also distinct moral questions and should not be collapsed into one.","Simuler la vie conjugale n’est pas établi comme le meilleur ni le seul moyen de discerner le mariage. Les relations sexuelles, le logement commun, le scandale et la dépendance pratique sont aussi des questions morales distinctes qui ne doivent pas être confondues."],
  catholicCase:["If cohabitation includes sex, Catholic teaching judges the sexual relations as outside marriage. If it is genuinely continent, sharing a residence is not itself fornication, but the couple must still assess proximate occasion, scandal and whether financial or emotional entanglement makes discernment less free.","Si la cohabitation comprend des relations sexuelles, l’enseignement catholique les juge comme ayant lieu hors mariage. Si elle est réellement continente, partager un logement n’est pas en soi une fornication, mais il faut encore évaluer l’occasion prochaine, le scandale et le risque qu’une dépendance financière ou affective rende le discernement moins libre."],
  counter:["But many married couples discover incompatibilities only after living together. Isn’t cohabitation simply prudent risk reduction?","Mais beaucoup de couples découvrent des incompatibilités seulement après avoir vécu ensemble. La cohabitation n’est-elle pas simplement une réduction prudente du risque ?"],
  response:["Prudence requires learning enough before marriage, but not every risk-reduction strategy is morally neutral. Discernment can occur through time, family life, conflict, finances, expectations and chastity without treating marital rights as already possessed.","La prudence exige de suffisamment connaître l’autre avant le mariage, mais toute stratégie de réduction du risque n’est pas moralement neutre. Le discernement peut se faire dans le temps, la vie familiale, les conflits, les finances, les attentes et la chasteté sans traiter les droits matrimoniaux comme déjà acquis."],
  bottom:["Cohabitation is not one moral category. Sexual cohabitation is direct; chaste co-residence requires prudential case analysis rather than slogans.","La cohabitation n’est pas une seule catégorie morale. La cohabitation sexuelle pose un problème direct ; une co-résidence chaste exige une analyse prudentielle du cas."]
},
"CSE043":{
  opposition:["Margaret Farley argues that legal recognition of same-sex partnerships and marriages can counter social rejection (Just Love, p.293, quoted in the CDF's 2012 Notification). Her position raises a substantive challenge: if two people of the same sex can show love, fidelity and commitment, why should civil and ecclesial understandings of marriage differ?","Margaret Farley soutient que la reconnaissance juridique des unions et mariages de même sexe peut contribuer à combattre le rejet social (Just Love, p.293, cité dans la Notification de la CDF de 2012). Son argument pose une difficulté réelle : si deux personnes du même sexe peuvent manifester amour, fidélité et engagement, pourquoi les conceptions civile et ecclésiale du mariage devraient-elles différer ?"],
  appeal:["Affection, loyalty, sacrifice and stable commitment are genuine relational goods.","L’affection, la loyauté, le sacrifice et l’engagement stable sont de véritables biens relationnels."],
  concession:["A same-sex relationship can contain real friendship, fidelity and self-sacrifice.","Une relation de même sexe peut contenir une véritable amitié, fidélité et sacrifice de soi."],
  breakpoint:["The unresolved premise is that these goods alone define marriage. Catholicism argues that marriage also has a bodily form: the union of man and woman, naturally ordered to generation and family life.","La prémisse non démontrée est que ces biens suffisent à définir le mariage. Le catholicisme affirme que le mariage possède aussi une forme corporelle : l’union de l’homme et de la femme, naturellement ordonnée à la génération et à la vie familiale."],
  catholicCase:["Marriage is not simply the strongest possible friendship. Its sexual union is male-female in kind, and that kind of union is the one through which children naturally come into being and receive a mother and father.","Le mariage n’est pas simplement l’amitié la plus forte possible. Son union sexuelle est de type homme-femme, et c’est par ce type d’union que les enfants viennent naturellement à l’existence et reçoivent une mère et un père."],
  counter:["But many heterosexual marriages never have children.","Mais beaucoup de mariages hétérosexuels n’ont jamais d’enfants."],
  response:["Catholic law does not require a couple to conceive a child: canon 1084 §3 states that sterility does not impede marriage. Canon 1084 §1 separately treats antecedent and perpetual inability to accomplish the conjugal act. Marriage is a bodily and faithful union of man and woman naturally ordered to family life, even if conception never occurs.","Le droit catholique n'exige pas que les époux conçoivent un enfant : selon le canon 1084 §3, la stérilité n'empêche pas le mariage. Le canon 1084 §1 traite séparément de l'incapacité antécédente et perpétuelle d'accomplir l'acte conjugal. Le mariage est une union corporelle et fidèle de l'homme et de la femme naturellement ordonnée à la vie familiale, même sans conception effective."],
  bottom:["The disagreement is not about whether same-sex couples can love. It is about whether love and commitment exhaust the definition of marriage.","Le désaccord ne porte pas sur la capacité des couples de même sexe à aimer. Il porte sur la question de savoir si l’amour et l’engagement épuisent la définition du mariage."]
},
"CSE044":{
  opposition:["If infertile heterosexual couples can marry, procreation clearly cannot be essential to marriage. Excluding same-sex couples on procreative grounds is therefore inconsistent.","Si des couples hétérosexuels stériles peuvent se marier, la procréation ne peut manifestement pas être essentielle au mariage. Exclure les couples de même sexe pour des raisons procréatives est donc incohérent."],
  appeal:["Actual ability to conceive is not a condition for marriage; Catholic law itself does not exclude sterile couples.","La capacité effective de concevoir n’est pas une condition du mariage ; le droit catholique lui-même n’exclut pas les couples stériles."],
  concession:["Actual fertility is not required for a valid marriage, and infertility can occur through age or pathology without fault.","La fécondité effective n’est pas requise pour la validité du mariage, et l’infertilité peut résulter de l’âge ou d’une pathologie sans faute."],
  breakpoint:["Not producing a child is not equivalent to not being the kind of union ordered to generation; those are different claims.","Ne pas produire d’enfant n’équivaut pas à ne pas être le type d’union ordonné à la génération ; ce sont deux affirmations différentes."],
  catholicCase:["Canon 1084 §3 does not prohibit or invalidate marriage on account of sterility. Section 1 instead addresses antecedent, perpetual inability to complete the conjugal act. The ability to enter a conjugal union and the outcome of conception are different matters.","Le canon 1084 §3 n'interdit ni n'invalide le mariage en raison de la stérilité. Le §1 concerne au contraire l'impuissance antécédente et perpétuelle à accomplir l'acte conjugal. La capacité d'union conjugale et le résultat de la fécondation ne sont pas la même chose."],
  counter:["Isn’t “kind of union” just a way of defining the conclusion into the premise?","Le « type d’union » n’est-il pas simplement une manière de placer la conclusion dans la prémisse ?"],
  response:["Only if no account is given of why the distinction matters. The Catholic account points to the bodily complementarity of the act and its natural relation to generation, independent of whether that relation succeeds in each instance.","Seulement si aucune raison n’est donnée pour expliquer pourquoi la distinction compte. L’explication catholique invoque la complémentarité corporelle de l’acte et son rapport naturel à la génération, indépendamment du fait que ce rapport aboutisse dans chaque cas."],
  bottom:["Infertility concerns outcome; the marriage argument concerns the structure of the union. Confusing those two produces the apparent inconsistency.","L’infertilité concerne le résultat ; l’argument sur le mariage concerne la structure de l’union. Confondre les deux produit l’apparente incohérence."]
},
"CSE045":{
  opposition:["Marriage today is mainly about love, companionship and mutual support. Making procreation central imposes an outdated biological model on a personal relationship.","Aujourd’hui, le mariage concerne surtout l’amour, la compagnie et le soutien mutuel. Faire de la procréation un élément central impose un modèle biologique dépassé à une relation personnelle."],
  appeal:["Companionship and mutual love are obviously central to a good marriage, and a purely reproductive account would be impoverished.","La compagnie et l’amour mutuel sont manifestement centraux dans un bon mariage, et une conception purement reproductive serait appauvrissante."],
  concession:["Catholic teaching strongly affirms mutual love, help, sanctification and companionship.","L’enseignement catholique affirme fortement l’amour mutuel, l’aide, la sanctification et la compagnie."],
  breakpoint:["The false choice is between personal love and procreation. Catholic marriage includes both rather than reducing marriage to either one.","Le faux dilemme oppose l’amour personnel et la procréation. Le mariage catholique inclut les deux au lieu de réduire le mariage à l’un ou l’autre."],
  catholicCase:["Casti Connubii §§11–17 treat procreation and education; §§19–25 also address fidelity, conjugal love, mutual help and growth in virtue. This expresses the ends of the marriage covenant, not a guarantee that every marriage will have children; infertility never makes the spouses' love worthless.","Casti Connubii (§§11–17) traite de la procréation et de l'éducation ; les §§19–25 enseignent aussi la fidélité, l'amour conjugal, l'aide mutuelle et le progrès dans la vertu. Il s'agit des fins de l'alliance, non de la garantie que chaque mariage aura des enfants ; la stérilité ne rend jamais l'amour des époux sans valeur."],
  counter:["But a childless marriage may be deeply loving and complete as a relationship.","Mais un mariage sans enfant peut être profondément aimant et complet comme relation."],
  response:["Yes. Lack of children does not make a marriage unreal or loveless. The claim is not that every marriage must achieve every good, but that the institution itself is ordered to goods larger than companionship alone.","Oui. L’absence d’enfants ne rend pas un mariage irréel ou sans amour. L’affirmation n’est pas que chaque mariage doit réaliser tous les biens, mais que l’institution elle-même est ordonnée à des biens plus larges que la seule compagnie."],
  bottom:["Catholic marriage is neither merely reproductive nor merely companionate. It joins faithful spousal love with the generative and educational goods of family life.","Le mariage catholique n’est ni purement reproductif ni purement compagnonnique. Il unit l’amour fidèle des époux aux biens génératifs et éducatifs de la vie familiale."]
},
"CSE049":{
  opposition:["Margaret Farley argues that even a nearly unconditional marital promise can cease to bind after profound, unforeseen changes in the spouses or their relationship (Just Love, pp.304–305, excerpted in the CDF's 2012 Notification). Why should a permanent commitment remain binding when what the couple originally promised to share seems to have disappeared?","Margaret Farley soutient que même une promesse matrimoniale presque inconditionnelle peut cesser d'obliger après des changements profonds et imprévus des époux ou de leur relation (Just Love, p.304–305, cité dans la Notification de la CDF de 2012). Pourquoi un engagement permanent devrait-il continuer d'obliger lorsque ce que les époux entendaient partager semble avoir disparu ?"],
  appeal:["Abandonment, grave conflict and abuse can make continued common life seriously harmful or unsafe; Catholic teaching permits separation in proportionate cases.","L’abandon, le conflit grave et les abus peuvent rendre la vie commune gravement nuisible ou dangereuse ; l’enseignement catholique permet la séparation dans des cas proportionnés."],
  concession:["Separation can be justified, and civil measures may be necessary to protect spouses, children or property.","La séparation peut être justifiée, et des mesures civiles peuvent être nécessaires pour protéger les époux, les enfants ou les biens."],
  breakpoint:["Ending common life and dissolving the matrimonial bond are distinct acts. Failure of the relationship does not by itself establish that the covenant has ceased to exist.","Mettre fin à la vie commune et dissoudre le lien matrimonial sont deux actes distincts. L’échec de la relation n’établit pas à lui seul que l’alliance a cessé d’exister."],
  catholicCase:["Christ's command and CIC can. 1141 teach that a valid, ratified and consummated sacramental marriage cannot be dissolved by any human power. This is not an assertion that every valid marriage is equally indissoluble: cann. 1142–1150 govern exceptional dissolutions of certain non-consummated or non-sacramental bonds. Relationship breakdown does not itself dissolve marriage.","Le commandement du Christ et le CIC (can. 1141) enseignent qu'un mariage sacramentel valide, ratifié et consommé ne peut être dissous par aucune puissance humaine. Cela ne signifie pas que tout mariage valide soit indissoluble au même degré : les canons 1142–1150 prévoient la dissolution exceptionnelle de certains liens non consommés ou non sacramentels. L'échec de la vie commune ne dissout pas en soi le mariage."],
  counter:["If the spouses could not foresee a radical and harmful change when they gave consent, why must the bond itself survive that change, even when they can no longer live together?","Si les époux ne pouvaient prévoir un changement radical et préjudiciable au moment de leur consentement, pourquoi le lien devrait-il subsister lorsque la vie commune n'est plus possible ?"],
  response:["CIC can. 1153 explicitly permits separation where a spouse or child faces grave mental or physical danger, including departure without awaiting a decree if delay poses danger. The duty to preserve a bond must never be confused with a requirement to endure abusive cohabitation.","Le CIC (can. 1153) permet expressément la séparation lorsqu'un époux ou un enfant subit un danger grave physique ou psychique, y compris sans attendre de décret si le retard est dangereux. Préserver le lien ne doit jamais être confondu avec l'obligation de subir une cohabitation violente."],
  bottom:["Indissolubility does not mean compulsory cohabitation under every condition. It means that grave failure does not by itself dissolve a valid marital bond.","L’indissolubilité ne signifie pas cohabitation obligatoire en toute circonstance. Elle signifie qu’un échec grave ne dissout pas par lui-même un lien matrimonial valide."]
},
"CSE050":{
  opposition:["Margaret Farley argues that a marriage leaves a lasting history and, sometimes, continuing parental obligations, but that this residual bond need not prohibit a later marriage (Just Love, p.310, quoted in the CDF's 2012 Notification). Why should the former bond always bar a new marriage after separation or civil divorce?","Margaret Farley affirme qu'un mariage laisse une histoire durable et, parfois, des responsabilités parentales persistantes, mais que ce lien résiduel ne doit pas nécessairement empêcher un autre mariage (Just Love, p.310, cité dans la Notification de la CDF de 2012). Pourquoi l'ancien lien devrait-il toujours faire obstacle à un nouveau mariage après la séparation ou le divorce civil ?"],
  appeal:["The burden can be severe, especially for an abandoned spouse who did not cause the breakdown.","Le fardeau peut être très lourd, surtout pour un conjoint abandonné qui n’a pas causé la rupture."],
  concession:["Catholic teaching does not deny the injustice or loneliness an innocent spouse may suffer, and it permits separation where necessary.","L’enseignement catholique ne nie ni l’injustice ni la solitude que peut subir un conjoint innocent, et il permet la séparation lorsque nécessaire."],
  breakpoint:["A failed common life does not by itself equal a dissolved matrimonial bond; Catholic teaching distinguishes those realities.","Une vie commune échouée n’équivaut pas à elle seule à un lien matrimonial dissous ; l’enseignement catholique distingue ces réalités."],
  catholicCase:["Civil divorce alone does not create freedom to remarry while a prior valid bond persists (CIC can. 1085). Nullity judges that a valid marriage never arose. Separately, canons 1142–1150 permit narrowly limited dissolutions of certain valid but non-consummated or non-sacramental bonds: these are not declarations of nullity.","Le divorce civil ne donne pas à lui seul la liberté de se remarier tant qu'un lien valide subsiste (CIC, can. 1085). La nullité constate qu'un mariage valide n'a pas existé dès l'origine. Séparément, les canons 1142–1150 permettent la dissolution très limitée de certains liens valides non consommés ou non sacramentels : ce ne sont pas des déclarations de nullité."],
  counter:["If the Church can declare that a marriage was null after years of common life, how is that different in substance from granting a divorce?","Si l'Église peut déclarer nul un mariage après des années de vie commune, en quoi cela diffère-t-il, au fond, de l'octroi d'un divorce ?"],
  response:["No in principle: divorce ends a recognized marriage; nullity judges that a valid bond was absent from the start because an essential requirement was missing. Whether tribunals apply that distinction well in a particular case is a separate question.","Non en principe : le divorce met fin à un mariage reconnu ; la nullité juge qu’un lien valide n’existait pas dès le début faute d’une condition essentielle. La question de savoir si les tribunaux appliquent bien cette distinction dans un cas concret est distincte."],
  bottom:["Marital breakdown alone gives no right to remarry; the actual status of a prior bond must be established. Nullity, separation and exceptional canonical dissolution are distinct matters.","L'échec conjugal ne donne pas à lui seul le droit de se remarier ; il faut établir le statut réel du lien antérieur. Nullité, séparation et dissolution canonique exceptionnelle sont des réalités distinctes."]
},
"CSE051":{
  opposition:["If both spouses freely agree and neither is pressured, it can seem that no further restriction is necessary. Why should marital intimacy be subject to rules beyond mutual consent?","Si les deux époux consentent librement sans aucune pression, il peut sembler qu’aucune autre limite ne soit nécessaire. Pourquoi l’intimité conjugale devrait-elle obéir à d’autres règles que le consentement mutuel ?"],
  appeal:["Freely given consent protects each spouse against unwanted sexual activity and is indispensable even within marriage. It is therefore understandable that many regard agreement as the decisive safeguard.","Le consentement libre protège chaque époux contre une activité sexuelle non voulue et demeure indispensable dans le mariage. Il est donc compréhensible que beaucoup voient dans l’accord la garantie décisive."],
  concession:["Marriage genuinely changes the moral context of sexual activity, and spouses have a wide sphere of legitimate affection and intimacy.","Le mariage change réellement le contexte moral de l’activité sexuelle, et les époux disposent d’un large espace d’affection et d’intimité légitimes."],
  breakpoint:["The inference from “marriage permits sex” to “marriage sanctifies every sexual choice” does not follow. Consent cannot authorize what contradicts fidelity, justice or the integrity of the marital act.","L’inférence de « le mariage permet la sexualité » à « le mariage sanctifie tout choix sexuel » ne suit pas. Le consentement ne peut autoriser ce qui contredit la fidélité, la justice ou l’intégrité de l’acte conjugal."],
  catholicCase:["Casti Connubii §§19–22 identifies conjugal fidelity as exclusive: marital rights cannot be shared with a third person, and one spouse cannot permit what contradicts divine law. Humanae Vitae §§12–14 further requires respect for the integrity of the conjugal act. Free agreement is necessary but does not convert every choice into a morally conjugal act.","Casti Connubii, §§19–22, définit la fidélité conjugale comme exclusive : les droits matrimoniaux ne peuvent être partagés avec un tiers, et un conjoint ne peut permettre ce qui contredit la loi divine. Humanae Vitae, §§12–14, demande également de respecter l’intégrité de l’acte conjugal. L’accord libre est nécessaire, mais il ne transforme pas tout choix en acte conjugal moralement bon."],
  counter:["But if neither spouse is harmed and both desire the act, what remaining moral problem is there?","Mais si aucun conjoint n’est lésé et que les deux désirent l’acte, quel problème moral reste-t-il ?"],
  response:["The same issue as in consent generally: the moral object cannot be reduced to mutual willingness. The act must still be compatible with marital fidelity, chastity and the meaning of conjugal union.","Le même problème que pour le consentement en général : l’objet moral ne peut être réduit à la volonté mutuelle. L’acte doit encore être compatible avec la fidélité, la chasteté et la signification de l’union conjugale."],
  bottom:["Marriage makes conjugal sexuality legitimate; it does not make every consensual sexual choice good.","Le mariage rend légitime la sexualité conjugale ; il ne rend pas bon tout choix sexuel consensuel."]
},
"CSE054":{
  opposition:["Traditional talk of the “marital debt” implies that marriage gives each spouse a right to sex, so refusing a spouse may itself be unjust. Modern claims about marital coercion therefore seem inconsistent with older teaching.","Le langage traditionnel du « devoir conjugal » implique que le mariage donne à chaque conjoint un droit aux relations sexuelles ; refuser peut donc être injuste. Les affirmations modernes sur la coercition conjugale semblent ainsi incompatibles avec l’enseignement ancien."],
  appeal:["Catholic tradition recognizes real and reciprocal conjugal rights and duties; neither spouse is free to disregard the other's good without proportionate reason.","La tradition catholique reconnaît des droits et des devoirs conjugaux réels et réciproques ; aucun époux ne peut négliger le bien de l’autre sans raison proportionnée."],
  concession:["Without proportionate reason, persistent refusal of legitimate conjugal relations can sometimes be unjust; the tradition does acknowledge reciprocal duties. But Aquinas himself limits what may be demanded: an exaction against a spouse's bodily welfare is unjust (Supplement, q.64 a.1, reply to objection 2). A moral duty never authorizes force.","Sans raison proportionnée, le refus persistant de relations conjugales légitimes peut parfois être injuste ; la tradition reconnaît bien des devoirs réciproques. Cependant, saint Thomas limite lui-même ce qui peut être exigé : une demande contraire à la santé et au bien corporel du conjoint est injuste (Supplément, q.64, a.1, réponse à la deuxième objection). Un devoir moral n'autorise jamais la contrainte."],
  breakpoint:["A right to request a marital act is not a right to force one. Moral obligation and coercive entitlement are different concepts.","Un droit à demander l’acte conjugal n’est pas un droit à l’imposer par la force. L’obligation morale et le pouvoir coercitif sont des concepts différents."],
  catholicCase:["Conjugal rights do not establish ownership of a spouse's body. Humanae Vitae §13 rejects an imposed act that disregards a spouse's condition and reasonable wishes. Serious coercion or abuse calls for protection and, where needed, separation under CIC can. 1153.","Les droits conjugaux ne rendent personne propriétaire du corps de son conjoint. Humanae Vitae (§13) rejette l'acte imposé sans égard à l'état et aux désirs légitimes de l'époux. Une contrainte grave ou des violences justifient la recherche d'une protection et, si nécessaire, la séparation prévue au CIC (can. 1153)."],
  counter:["Then does the marital obligation have any practical meaning?","Le devoir conjugal a-t-il alors encore un sens pratique ?"],
  response:["Yes. It means spouses should not treat sexuality as purely individual property or use refusal manipulatively. But a moral duty is fulfilled through free human action, not violence or domination.","Oui. Cela signifie que les époux ne doivent pas traiter la sexualité comme une propriété purement individuelle ni utiliser le refus comme moyen de manipulation. Mais un devoir moral s’accomplit par un acte humain libre, non par violence ou domination."],
  bottom:["Marital rights are real and reciprocal; coercion is not one of those rights.","Les droits matrimoniaux sont réels et réciproques ; la coercition n’en fait pas partie."]
},
"CSE056":{
  opposition:["If both spouses agree to non-monogamy, adultery should no longer apply because no one is being deceived. Fidelity can be defined by the couple however they choose.","Si les deux époux acceptent la non-monogamie, l’adultère ne devrait plus s’appliquer puisqu’il n’y a aucune tromperie. Le couple peut définir la fidélité comme il l’entend."],
  appeal:["Secrecy and betrayal add serious wrongs to adultery, and consensual non-monogamy removes some of those additional wrongs.","Le secret et la trahison ajoutent des maux graves à l’adultère, et la non-monogamie consensuelle supprime certains de ces maux supplémentaires."],
  concession:["An openly agreed arrangement differs morally from a secret affair because deception is absent.","Un arrangement ouvertement accepté diffère moralement d’une liaison secrète parce que la tromperie en est absente."],
  breakpoint:["The unresolved claim is that exclusivity is merely an optional private rule. Catholic marriage treats exclusivity as part of what matrimonial consent establishes, not as a clause spouses may later delete.","L’affirmation non démontrée est que l’exclusivité serait une simple règle privée facultative. Le mariage catholique considère l’exclusivité comme partie de ce qu’établit le consentement matrimonial, non comme une clause que les époux peuvent supprimer ensuite."],
  catholicCase:["The marital covenant is a mutual, exclusive gift. A spouse cannot authorize the other to treat a third person as a sexual partner without contradicting the form of that covenant.","L’alliance matrimoniale est un don mutuel et exclusif. Un conjoint ne peut autoriser l’autre à traiter une tierce personne comme partenaire sexuel sans contredire la forme de cette alliance."],
  counter:["But why can’t adults redefine their own covenant by mutual agreement?","Pourquoi des adultes ne pourraient-ils pas redéfinir leur propre alliance d’un commun accord ?"],
  response:["Because Catholicism holds that marriage has an objective structure prior to private preference. The same reason spouses cannot mutually agree to make the bond temporary while still calling it Catholic marriage applies to exclusivity.","Parce que le catholicisme soutient que le mariage possède une structure objective antérieure à la préférence privée. La même raison pour laquelle les époux ne peuvent convenir de rendre le lien temporaire tout en l’appelant mariage catholique vaut pour l’exclusivité."],
  bottom:["Mutual permission removes deception, not the contradiction with marital exclusivity.","La permission mutuelle supprime la tromperie, non la contradiction avec l’exclusivité matrimoniale."]
},
"CSE061":{
  opposition:["Charles Curran's 1987 essay criticizes the 'physicalism' he sees in an absolute ban on contraception. He argues that the goods of persons and marriage can sometimes warrant intervention in biological processes; he does not deny the importance of love and fidelity. Why must every individual conjugal act retain its procreative ordering?","Dans son article de 1987, Charles Curran critique le « physicalisme » qu'il voit dans l'interdiction absolue de la contraception. Selon lui, le bien des personnes et du mariage peut parfois justifier une intervention biologique ; il ne nie pas l'importance de l'amour et de la fidélité. Pourquoi chaque acte conjugal devrait-il garder son ordination procréatrice ?"],
  appeal:["Curran identifies a genuine question: moral theology should not mistake a biological description for a complete account of human acts and the good of marriage.","Curran soulève une véritable question : la théologie morale ne doit pas confondre une description biologique avec une appréciation complète des actes humains et du bien du mariage."],
  concession:["Responsible parenthood can require postponing pregnancy, sometimes for a long period.","La responsabilité parentale peut exiger de différer une grossesse, parfois longtemps."],
  breakpoint:["Criticism of a merely biological analysis does not establish that deliberately contracepted intercourse has a good moral object. Intentionally frustrating the procreative meaning of the chosen conjugal act remains morally distinct from treating an illness or refraining from intercourse.","Critiquer une analyse purement biologique ne démontre pas que contracepter délibérément l’union possède un objet moral bon. Frustrer intentionnellement la signification procréatrice de l’acte conjugal choisi reste moralement distinct du traitement d’une maladie ou de l’abstinence."],
  catholicCase:["Casti Connubii §§53–56 condemns deliberately frustrating the generative capacity of marital intercourse. Humanae Vitae §§11–14 explains this through the relationship between the unitive and procreative meanings and specifies contraception as an action intended to prevent procreation, as an end or a means. The claim therefore concerns the deliberate choice, not the proposition that every biological intervention is immoral.","Casti Connubii, §§53–56, condamne la frustration délibérée de la faculté génératrice de l’union conjugale. Humanae Vitae, §§11–14, explicite le rapport entre ses significations unitive et procréatrice et qualifie de contraception l’action destinée à empêcher la procréation comme fin ou comme moyen. L’argument porte donc sur le choix délibéré, non sur l’idée que toute intervention biologique serait immorale."],
  counter:["But why should the biological structure of an act determine morality?","Pourquoi la structure biologique d’un acte devrait-elle déterminer la morale ?"],
  response:["Contraception involves the deliberate choice to suppress the procreative meaning of intercourse, not merely an intervention in a biological process (Humanae Vitae §§12–14). The spouses' broader circumstances remain morally relevant, but a serious reason to avoid pregnancy does not in itself make deliberate contraception lawful.","La contraception implique le choix délibéré de supprimer la signification procréatrice de l’union, et non une simple intervention sur un processus biologique (Humanae Vitae, §§12–14). Les circonstances des époux gardent leur importance morale, mais une raison grave d’éviter une grossesse ne rend pas pour autant la contraception licite."],
  bottom:["The controversy is not whether avoiding pregnancy can be responsible. It is whether deliberately contracepting intercourse is a morally neutral means of doing so.","La controverse ne porte pas sur le fait qu’éviter une grossesse puisse être responsable. Elle porte sur la question de savoir si contracepter délibérément l’union est un moyen moralement neutre."]
},
"CSE063":{
  opposition:["NFP and contraception aim at the same result: sex without pregnancy. Calling one moral and the other immoral looks like a word game based on technology rather than intention.","La PFN et la contraception visent le même résultat : des relations sans grossesse. Dire que l’une est morale et l’autre immorale ressemble à un jeu de mots fondé sur la technique plutôt que sur l’intention."],
  appeal:["The remote intention can be identical: both couples may deliberately intend to avoid conception.","L’intention lointaine peut être identique : les deux couples peuvent vouloir délibérément éviter la conception."],
  concession:["NFP is not morally different because its users secretly want pregnancy. They may very clearly intend to avoid it.","La PFN n’est pas moralement différente parce que ses utilisateurs voudraient secrètement une grossesse. Ils peuvent très clairement vouloir l’éviter."],
  breakpoint:["The missing distinction is between the further intention and the act chosen as the means. Same end does not make different means the same moral act.","La distinction manquante est celle entre l’intention ultérieure et l’acte choisi comme moyen. Une même fin ne rend pas des moyens différents moralement identiques."],
  catholicCase:["Periodic continence chooses not to have intercourse during fertile periods. Contraception chooses to have intercourse while deliberately acting to render that intercourse infertile. Pius XII and Humanae Vitae explicitly distinguish those choices.","La continence périodique choisit de ne pas avoir de relations pendant les périodes fécondes. La contraception choisit d’avoir des relations tout en agissant délibérément pour rendre cette union inféconde. Pie XII et Humanae Vitae distinguent explicitement ces choix."],
  counter:["But abstaining only because conception might occur is still a deliberate anti-conception strategy. Isn’t that contraception by omission?","Mais s’abstenir uniquement parce qu’une conception pourrait survenir reste une stratégie délibérément anti-conception. N’est-ce pas une contraception par omission ?"],
  response:["Refraining from an act and performing it while altering it are not identical choices merely because they serve the same goal. Moral reasoning makes that distinction elsewhere as well. Moreover, periodic abstinence is not automatically virtuous: using it for selfish or disproportionate reasons can itself be morally defective.","S’abstenir d’un acte et l’accomplir tout en le modifiant ne sont pas des choix identiques simplement parce qu’ils servent la même fin. Le raisonnement moral fait cette distinction ailleurs aussi. De plus, la continence périodique n’est pas automatiquement vertueuse : l’employer pour des raisons égoïstes ou disproportionnées peut elle-même être moralement défectueuse."],
  bottom:["Same intention does not mean same act. The Catholic distinction concerns what the couple chooses to do to the marital act itself.","Même intention ne signifie pas même acte. La distinction catholique porte sur ce que le couple choisit de faire à l’acte conjugal lui-même."]
},
"CSE064":{
  opposition:["NFP is just Catholic contraception with a natural method. Couples track fertility specifically to prevent pregnancy, so the moral distinction seems cosmetic.","La PFN est simplement une contraception catholique utilisant une méthode naturelle. Les couples suivent la fécondité précisément pour empêcher une grossesse ; la distinction morale paraît cosmétique."],
  appeal:["The phrase is rhetorically effective because it focuses on intention and outcome, which often are the same.","La formule est rhétoriquement efficace parce qu’elle se concentre sur l’intention et le résultat, souvent identiques."],
  concession:["NFP can be used with a contraceptive mentality in the ordinary-language sense of selfishly refusing parenthood. Catholic teaching does not declare every use of periodic abstinence virtuous.","La PFN peut être utilisée avec une mentalité contraceptive au sens courant d’un refus égoïste de la parentalité. L’enseignement catholique ne déclare pas vertueux tout usage de la continence périodique."],
  breakpoint:["But the technical moral meaning of contraception concerns the act chosen, not merely the wish to avoid a child. Periodic abstinence does not render an act infertile; it chooses when not to perform the act.","Mais le sens moral technique de la contraception concerne l’acte choisi, non le seul désir d’éviter un enfant. La continence périodique ne rend pas un acte infécond ; elle choisit quand ne pas accomplir l’acte."],
  catholicCase:["That is why Pius XII can both permit recourse to infertile periods for serious reasons and reject direct contraception. The distinction predates contemporary NFP marketing.","C’est pourquoi Pie XII peut à la fois permettre le recours aux périodes infécondes pour de sérieuses raisons et rejeter la contraception directe. La distinction est antérieure au marketing contemporain de la PFN."],
  counter:["Isn’t this still overly focused on the physical act?","Cela ne reste-t-il pas excessivement centré sur l’acte physique ?"],
  response:["Only if moral object is reduced to anatomy. The claim is about what the will chooses to do: abstain, or perform intercourse while deliberately suppressing its fertility. That is an intentional difference, not merely a physical one.","Seulement si l’objet moral est réduit à l’anatomie. L’affirmation porte sur ce que la volonté choisit de faire : s’abstenir, ou accomplir l’union tout en supprimant délibérément sa fécondité. C’est une différence intentionnelle, non seulement physique."],
  bottom:["NFP can be used badly, but it is not contraception in the Catholic moral sense because the chosen means is different.","La PFN peut être mal utilisée, mais elle n’est pas une contraception au sens moral catholique parce que le moyen choisi est différent."]
}
});
