export const CSE_DEBATES_001_031=Object.freeze({
"CSE006":{
  opposition:["A familiar liberty-based objection holds that adults should not face state coercion for private sexual choices that do not harm others. John Stuart Mill argues particularly against coercive social authority; a further argument is needed to claim that every unharming choice is morally good.","Une objection courante fondée sur la liberté soutient que les adultes ne devraient pas subir de contrainte étatique pour des choix sexuels privés qui ne nuisent pas à autrui. John Stuart Mill conteste surtout l’autorité sociale coercitive ; il faut un argument supplémentaire pour conclure que tout choix sans dommage est moralement bon."],
  appeal:["This is attractive because it protects liberty and correctly treats unjust harm as morally serious. It also guards against intrusive rules based only on disgust or convention.","Cette position séduit parce qu’elle protège la liberté et reconnaît à juste titre que le tort injuste est moralement grave. Elle protège aussi contre des règles intrusives fondées seulement sur le dégoût ou la convention."],
  concession:["Causing unjust harm is a major moral consideration, and not every private preference should be regulated.","Causer un tort injuste est une considération morale majeure, et toute préférence privée ne doit pas être réglementée."],
  breakpoint:["The illicit inference is from limits on public coercion to the claim that avoiding harm exhausts personal morality. Whether the state may prohibit an act is distinct from whether someone should choose it. Fidelity, self-mastery and freely assumed obligations require moral examination even where civil prohibition would be unjustified.","Le saut illégitime consiste à déduire des limites de la contrainte publique que l’absence de dommage épuise la morale personnelle. Que l’État puisse interdire un acte est distinct de la question de savoir si quelqu’un devrait le choisir. Fidélité, maîtrise de soi et obligations librement assumées demandent un examen moral même si une interdiction civile serait injustifiée."],
  catholicCase:["Catholic ethics asks not only who is harmed, but what kind of act is deliberately chosen and which human goods it respects or contradicts. Sexuality is judged in relation to chastity, marriage, fidelity and procreation, not by a harm test alone.","La morale catholique demande non seulement qui est lésé, mais quel type d’acte est délibérément choisi et quels biens humains il respecte ou contredit. La sexualité est jugée en relation avec la chasteté, le mariage, la fidélité et la procréation, non par le seul critère du dommage."],
  counter:["Mill himself allows persuasion and moral education without coercion. But why should a non-Catholic accept the specifically Catholic account of sexuality?","Mill lui-même admet la persuasion et l’éducation morale sans coercition. Mais pourquoi un non-catholique accepterait-il la conception spécifiquement catholique de la sexualité ?"],
  response:["Fidelity, rational self-mastery, marriage and care for children are intelligible human goods, not duties arising only from Church membership (Aquinas, I-II q.94 a.2). Whether a particular choice contradicts them depends on the moral object deliberately chosen (Veritatis Splendor §78). Even conduct judged morally wrong does not automatically warrant civil prohibition.","La fidélité, la maîtrise rationnelle de soi, le mariage et le soin des enfants sont des biens humains intelligibles, non des devoirs nés de la seule appartenance à l’Église (saint Thomas, I-II, q.94, a.2). Qu’un choix particulier les contredise dépend de l’objet moral délibérément choisi (Veritatis Splendor, §78). Même une conduite jugée moralement mauvaise ne justifie pas automatiquement son interdiction civile."],
  bottom:["Harm matters, but it is not the whole of morality. The decisive question is whether the chosen act respects the goods that make human sexuality intelligible.","Le dommage compte, mais il n’épuise pas la morale. La question décisive est de savoir si l’acte choisi respecte les biens qui donnent sens à la sexualité humaine."]
},
"CSE007":{
  opposition:["Planned Parenthood treats sexual consent as voluntary, informed and reversible. If two competent adults understand what they are doing, choose it freely and harm no one, why should their private sexual conduct require a further moral justification?","Planned Parenthood insiste sur un consentement libre, éclairé et révocable. Si deux adultes capables comprennent leur décision, la prennent librement et ne nuisent à personne, pourquoi leur conduite sexuelle privée aurait-elle besoin d'une justification morale supplémentaire ?"],
  appeal:["Coercive sex is gravely wrong, and free consent is indispensable in any just relationship.","La sexualité coercitive est gravement mauvaise, et le consentement libre est indispensable à toute relation juste."],
  concession:["Consent is necessary. Without it, the injustice can be severe.","Le consentement est nécessaire. Sans lui, l’injustice peut être grave."],
  breakpoint:["Consent is necessary, but agreement does not by itself make the chosen act just. Two consenting persons can betray an existing spouse, exploit vulnerability, or agree to something contrary to a serious duty. The moral object and obligations remain relevant (Veritatis Splendor §§78–80).","Le consentement est nécessaire, mais l’accord ne rend pas à lui seul l’acte choisi juste. Deux personnes consentantes peuvent trahir un conjoint, exploiter une vulnérabilité ou convenir de quelque chose de contraire à un devoir grave. L’objet moral et les obligations demeurent déterminants (Veritatis Splendor, §§78–80)."],
  catholicCase:["Two people can consent to adultery, to an exploitative commercial arrangement, or to conduct that violates a prior promise. Catholic ethics therefore asks two questions: Was it freely chosen? And what exactly was chosen?","Deux personnes peuvent consentir à l’adultère, à un arrangement commercial exploiteur ou à une conduite qui viole une promesse antérieure. La morale catholique pose donc deux questions : l’acte a-t-il été librement choisi ? Et qu’a-t-on exactement choisi ?"],
  counter:["But those examples add betrayal or exploitation. What if two unattached adults consent and no other duty is violated?","Mais ces exemples ajoutent trahison ou exploitation. Et si deux adultes sans engagement consentent et qu’aucun autre devoir n’est violé ?"],
  response:["Then the dispute moves from consent to the nature of sexual union itself: whether sexual acts have goods and meanings that are not created solely by agreement. Catholicism says they do, especially through their relation to marriage and generation.","Le débat se déplace alors du consentement vers la nature même de l’union sexuelle : les actes sexuels ont-ils des biens et des significations qui ne sont pas créés uniquement par l’accord ? Le catholicisme répond oui, notamment en raison de leur rapport au mariage et à la génération."],
  bottom:["Consent is indispensable, but it cannot make every chosen act good. It answers who chose; it does not by itself answer whether the choice was good.","Le consentement est indispensable, mais il ne peut rendre bon tout acte choisi. Il répond à la question de savoir qui a choisi ; il ne suffit pas à dire si le choix était bon."]
},
"CSE008":{
  opposition:["Joseph Fletcher treats deliberate, self-giving agape, not romantic feeling, as the only unconditional moral norm. His Situation Ethics (1966, propositions 1–5) holds that love seeks the neighbour's good, justice distributes that care, and a normally prohibited means can be right when it best serves love. Why must an absolute prohibition prevail even in a tragic case?","Joseph Fletcher fait de l'agapè désintéressée, non du simple sentiment, l'unique norme morale inconditionnelle. Selon Situation Ethics (1966, propositions 1–5), l'amour recherche le bien d'autrui, la justice en répartit les exigences et un moyen normalement interdit peut devenir juste s'il sert le mieux cet amour. Pourquoi maintenir un interdit absolu même dans un cas tragique ?"],
  appeal:["Fletcher's concern is serious: moral rules must serve persons, and ignoring the neighbour's real needs can become a form of legalism. Good intentions and circumstances genuinely belong in the assessment of an act.","La préoccupation de Fletcher est sérieuse : les règles morales doivent servir les personnes, et négliger les besoins réels du prochain peut devenir du légalisme. L’intention bonne et les circonstances entrent réellement dans l’appréciation d’un acte."],
  concession:["Catholic morality fully agrees that intention is one essential part of a human act and can increase or lessen responsibility.","La morale catholique reconnaît pleinement que l’intention est une dimension essentielle de l’acte humain et peut augmenter ou diminuer la responsabilité."],
  breakpoint:["The error is making intention the only source of moral goodness. A good end does not automatically make the chosen means good.","L’erreur consiste à faire de l’intention l’unique source de bonté morale. Une bonne fin ne rend pas automatiquement bon le moyen choisi."],
  catholicCase:["The tradition distinguishes the object chosen, the further intention and the circumstances. A person can sincerely seek a good end and still choose a means that contradicts another serious good.","La tradition distingue l’objet choisi, l’intention ultérieure et les circonstances. Une personne peut sincèrement rechercher une bonne fin tout en choisissant un moyen qui contredit un autre bien grave."],
  counter:["But in real life the object and intention are often inseparable. Isn’t this distinction artificial?","Mais dans la vie réelle, l’objet et l’intention sont souvent inséparables. Cette distinction n’est-elle pas artificielle ?"],
  response:["They are connected but not identical. The same desired end can be pursued by different means, and moral reasoning routinely distinguishes between them. Wanting to save a relationship, avoid pregnancy or relieve distress does not tell us which act was chosen to achieve that end.","Ils sont liés mais non identiques. La même fin désirée peut être poursuivie par des moyens différents, et le raisonnement moral les distingue constamment. Vouloir sauver une relation, éviter une grossesse ou soulager une détresse ne dit pas quel acte a été choisi pour y parvenir."],
  bottom:["Good intentions matter greatly, but they do not erase the moral character of the means deliberately chosen.","Les bonnes intentions comptent beaucoup, mais elles n’effacent pas le caractère moral des moyens délibérément choisis."]
},
"CSE010":{
  opposition:["Fletcher distinguishes agape from sentiment: the neighbour's good in a concrete situation is his criterion. In Situation Ethics (propositions 1, 4–6), love alone is unconditionally good, the loving end can justify an otherwise forbidden means, and moral decisions depend on circumstances. Can a chosen kind of act nevertheless be wrong in every case?","Fletcher distingue l'agapè du sentiment : le bien d'autrui dans la situation concrète est son critère. Dans Situation Ethics (propositions 1, 4–6), seul l'amour est inconditionnellement bon, une fin aimante peut justifier un moyen autrement interdit et les décisions dépendent des circonstances. Un type d'acte choisi peut-il néanmoins demeurer mauvais dans tous les cas ?"],
  appeal:["Circumstances clearly matter, and simple rules can be applied badly when they ignore coercion, fear, ignorance or competing duties.","Les circonstances comptent manifestement, et des règles simples peuvent être mal appliquées lorsqu’elles ignorent la contrainte, la peur, l’ignorance ou des devoirs concurrents."],
  concession:["Catholic morality agrees that circumstances and culpability can radically change how responsible a person is.","La morale catholique reconnaît que les circonstances et la culpabilité peuvent modifier radicalement la responsabilité d’une personne."],
  breakpoint:["Fletcher correctly notes that circumstances affect the morality of choices; his stronger claim that love can override every negative precept is incompatible with intrinsically evil acts. Veritatis Splendor §§79–81 locates their wrongness in the object freely chosen, not in a failure to calculate the most loving result.","Fletcher relève à juste titre que les circonstances comptent dans les choix ; mais l’idée que l’amour puisse écarter toute interdiction morale contredit l’existence d’actes intrinsèquement mauvais. Veritatis Splendor (§§79–81) situe leur malice dans l’objet librement choisi, non dans l’absence d’un calcul du résultat le plus aimant."],
  catholicCase:["An intrinsically evil act is one whose chosen object is incompatible with the good of the person in every case. The doctrine concerns the act’s moral species, not a claim that every person who commits it is equally guilty.","Un acte intrinsèquement mauvais est un acte dont l’objet choisi est incompatible avec le bien de la personne dans tous les cas. La doctrine concerne l’espèce morale de l’acte, non l’affirmation que toute personne qui le commet est également coupable."],
  counter:["Doesn’t that simply define the answer in advance?","Cela ne revient-il pas simplement à définir la réponse d’avance ?"],
  response:["Only if no argument is offered for why the object is always incompatible with the good. The real work is identifying the moral object correctly and showing why it cannot be ordered to a good end. “Intrinsic evil” is the conclusion of that analysis, not a substitute for it.","Seulement si aucun argument n’est donné pour montrer pourquoi l’objet est toujours incompatible avec le bien. Le vrai travail consiste à identifier correctement l’objet moral et à montrer pourquoi il ne peut être ordonné à une bonne fin. « Intrinsèquement mauvais » est la conclusion de l’analyse, non son substitut."],
  bottom:["Absolute norms do not deny complexity. They distinguish the objective character of a choice from the often much more complex question of personal culpability.","Les normes absolues ne nient pas la complexité. Elles distinguent le caractère objectif d’un choix de la question, souvent bien plus complexe, de la culpabilité personnelle."]
},
"CSE012":{
  opposition:["The Gospels do not name contraception, IVF or many modern practices. If Christ did not discuss a technique expressly, why should Christians accept a later moral judgment about it?","Les Évangiles ne nomment ni la contraception, ni la FIV, ni bien des pratiques modernes. Si le Christ n’a pas évoqué expressément une technique, pourquoi les chrétiens devraient-ils accepter un jugement moral ultérieur ?"],
  appeal:["Later Christian formulations should not be presented as though Jesus had spoken those exact words in the Gospels.","Les formulations chrétiennes ultérieures ne doivent pas être présentées comme si Jésus avait prononcé exactement ces mots dans les Évangiles."],
  concession:["Many modern practices are not named in the Gospels, and a serious Christian argument cannot pretend otherwise.","De nombreuses pratiques modernes ne sont pas nommées dans les Évangiles, et un argument chrétien sérieux ne peut prétendre le contraire."],
  breakpoint:["The hidden premise is that Christian morality is limited to a list of behaviors explicitly named by Jesus. The New Testament itself does not work that way.","La prémisse cachée est que la morale chrétienne se limite à une liste de comportements explicitement nommés par Jésus. Le Nouveau Testament lui-même ne fonctionne pas ainsi."],
  catholicCase:["Christ condemns adultery and deliberate lust (Mt 5:27–28) and teaches the lasting significance of marriage (Mt 19:3–9). St Paul reasons from the body's belonging to Christ when treating sexual conduct (1 Cor 6:12–20). These texts provide enduring premises, while distinct arguments must still show how each modern intervention relates to them; Scripture does not name IVF or contraception as technologies.","Le Christ condamne l’adultère et la convoitise délibérée (Mt 5, 27–28) et enseigne la portée durable du mariage (Mt 19, 3–9). Saint Paul fonde ses enseignements sexuels sur l’appartenance du corps au Christ (1 Co 6, 12–20). Ces textes offrent des principes durables, mais une argumentation distincte doit montrer leur application à chaque intervention moderne ; l’Écriture ne nomme pas la FIV ni la contraception comme techniques."],
  counter:["But how do we know later Christians are applying Jesus rather than importing their own prejudices?","Mais comment savoir si les chrétiens ultérieurs appliquent Jésus plutôt qu’ils n’importent leurs propres préjugés ?"],
  response:["An act's absence from the Gospel vocabulary cannot prove permission or prohibition. Its object must be identified and assessed through Scripture, natural law and the precise subsequent teaching concerning that act; a general appeal to Jesus is not a substitute for this demonstration.","L’absence du nom d’un acte dans les Évangiles ne prouve ni sa permission ni son interdiction. Il faut identifier son objet et l’examiner à la lumière de l’Écriture, de la loi naturelle et des enseignements précis qui le concernent ; une référence générale à Jésus ne remplace pas cette démonstration."],
  bottom:["“Jesus never used this word” is not enough. The real question is whether the later norm follows from the moral principles Christianity actually received.","« Jésus n’a jamais utilisé ce mot » ne suffit pas. La vraie question est de savoir si la norme ultérieure découle des principes moraux réellement reçus par le christianisme."]
},
"CSE013":{
  opposition:["Paul was an ancient man shaped by Jewish and Greco-Roman assumptions. His sexual prohibitions may reflect his culture rather than permanent moral truth.","Paul était un homme de l’Antiquité façonné par des présupposés juifs et gréco-romains. Ses interdictions sexuelles peuvent refléter sa culture plutôt qu’une vérité morale permanente."],
  appeal:["Historical context matters, and Christians can misread ancient texts when they ignore language, genre and social assumptions.","Le contexte historique compte, et les chrétiens peuvent mal lire les textes anciens lorsqu’ils ignorent la langue, le genre et les présupposés sociaux."],
  concession:["Paul wrote in a particular culture, so exegesis must distinguish local custom from the reasons he gives for a moral norm.","Paul écrivait dans une culture particulière ; l’exégèse doit donc distinguer les usages locaux des raisons qu’il donne pour une norme morale."],
  breakpoint:["A cultural setting by itself does not make a moral teaching culturally relative. One must show that Paul’s stated reasons depend on a premise we now know to be false or merely local.","Un contexte culturel ne rend pas à lui seul un enseignement moral culturellement relatif. Il faut montrer que les raisons données par Paul dépendent d’une prémisse que nous savons aujourd’hui fausse ou purement locale."],
  catholicCase:["In 1 Corinthians 6:13–20, St Paul argues from union with Christ, the Holy Spirit's dwelling in the body and the body's redemption. In 1 Thessalonians 4:3–8, he appeals to sanctification and God's call. These are theological premises, not simply a demand to imitate the social etiquette of his century; creation-language arguments elsewhere require their own textual references.","Dans 1 Corinthiens 6, 13–20, saint Paul raisonne à partir de l’union au Christ, de la présence de l’Esprit Saint dans le corps et de la rédemption du corps. Dans 1 Thessaloniciens 4, 3–8, il invoque la sanctification et l’appel de Dieu. Ce sont des prémisses théologiques, non de simples prescriptions d’étiquette antique ; les arguments tirés de la création dans d’autres passages exigent leurs propres références."],
  counter:["But even theological reasoning can be shaped by mistaken ancient anthropology.","Mais même un raisonnement théologique peut être façonné par une anthropologie antique erronée."],
  response:["Historical exegesis can reveal culturally conditioned assumptions. To overturn a particular moral conclusion, however, one must identify the relevant premise, establish that it is culturally contingent or false, and show that the conclusion depends upon it. The age of Paul's letter is not itself such a demonstration.","L’exégèse historique peut révéler des présupposés conditionnés par la culture. Pour renverser une conclusion morale déterminée, il faut toutefois identifier la prémisse décisive, établir son caractère contingent ou erroné et montrer que la conclusion en dépend. L’ancienneté d’une lettre de Paul ne suffit pas à cette démonstration."],
  bottom:["Context must be studied, but culture alone does not dissolve an argument. The question is whether Paul’s reasons survive historical scrutiny.","Le contexte doit être étudié, mais la culture seule ne dissout pas un argument. La question est de savoir si les raisons de Paul résistent à l’examen historique."]
},
"CSE014":{
  opposition:["In his 1987 essay, Charles Curran argues that authoritative non-infallible moral judgments carry weight but may contain error. He cites doctrinal developments, different degrees of authority, and the possibility of loyal dissent in specific cases. If the Church can correct a non-definitive judgment, how can permanent moral doctrine be distinguished from reformable applications?","Dans son article de 1987, Charles Curran soutient que les jugements moraux non infaillibles faisant autorité possèdent une force réelle, mais peuvent être erronés. Il invoque les développements doctrinaux, les degrés d'autorité et la possibilité d'un dissentiment loyal dans des cas précis. Si l'Église peut corriger un jugement non définitif, comment distinguer la doctrine morale permanente d'une application réformable ?"],
  appeal:["Curran distinguishes definitive teaching from authoritative non-infallible judgments, and genuine historical developments require explanation. Different levels of teaching authority cannot simply be collapsed into one undifferentiated claim of infallibility.","Curran distingue l’enseignement définitif des jugements non infaillibles qui font néanmoins autorité, et les développements historiques réels demandent une explication. Les différents degrés d’autorité doctrinale ne peuvent être confondus en une seule prétention indifférenciée à l’infaillibilité."],
  concession:["Terminology, discipline, canonical penalties, pastoral strategies and applications do change. Development is real.","La terminologie, la discipline, les peines canoniques, les stratégies pastorales et les applications changent. Le développement est réel."],
  breakpoint:["The possibility that a non-definitive judgment could require correction does not establish that any particular doctrine has been reversed. A proposed contradiction must identify the same moral proposition, the relevant qualifications and the authority with which each text teaches it (Veritatis Splendor §53).","La possibilité qu’un jugement non définitif exige une correction ne prouve pas qu’une doctrine déterminée ait été renversée. Une contradiction alléguée doit identifier la même proposition morale, ses qualifications pertinentes et le degré d’autorité de chaque texte (Veritatis Splendor, §53)."],
  catholicCase:["The continuity chain is substantial: New Testament teaching on adultery, fornication and marriage; the Roman Catechism; and later papal teaching such as Casti Connubii. Newer documents often refine concepts or apply them to new technology rather than inventing the underlying norm.","La chaîne de continuité est substantielle : enseignement du Nouveau Testament sur l’adultère, la fornication et le mariage ; Catéchisme romain ; puis enseignement pontifical tel que Casti Connubii. Les documents plus récents précisent souvent les concepts ou les appliquent à de nouvelles technologies plutôt que d’inventer la norme sous-jacente."],
  counter:["But isn’t that just selecting examples that support continuity and ignoring difficult cases?","Mais cela ne revient-il pas à choisir des exemples favorables à la continuité et à ignorer les cas difficiles ?"],
  response:["Historical change may concern discipline, formulation, application or an authoritative judgment of differing weight. It is not enough to place two documents from different centuries side by side: the propositions must actually conflict, not merely concern different moral objects or historical conditions. Permanent negative norms concerning intrinsically evil acts remain affirmed in Veritatis Splendor §§79–83.","Un changement historique peut concerner la discipline, la formulation, l’application ou un jugement doté d’une autorité différente. Juxtaposer deux documents de siècles différents ne suffit pas : leurs propositions doivent réellement se contredire et non porter sur des objets moraux ou des conditions distincts. Veritatis Splendor (§§79–83) réaffirme la permanence des interdictions d’actes intrinsèquement mauvais."],
  bottom:["Historical development is real, but it does not make every moral norm provisional. The alleged contradiction must be demonstrated at the level of the same moral proposition.","Le développement historique est réel, mais il ne rend pas toute norme morale provisoire. La contradiction alléguée doit être démontrée au niveau de la même proposition morale."]
},
"CSE016":{
  opposition:["Conscience binds even when a person judges wrongly. Curran's 1986 address and 1987 essay defend a limited place for theological dissent from non-infallible teaching, while acknowledging a presumption of truth in its favour. If serious inquiry raises a conflict, how can conscience be followed without turning private conviction into a rival Magisterium?","La conscience oblige même lorsqu'elle se trompe. Dans sa conférence de 1986 et son article de 1987, Curran défend un dissentiment théologique limité devant un enseignement non infaillible, tout en reconnaissant une présomption de vérité en sa faveur. Si une recherche sérieuse révèle une difficulté, comment suivre sa conscience sans ériger l'opinion privée en magistère rival ?"],
  appeal:["This argument takes conscience seriously and correctly rejects acting against what one presently judges to be morally obligatory.","Cet argument prend la conscience au sérieux et rejette à juste titre le fait d’agir contre ce que l’on juge présentement moralement obligatoire."],
  concession:["A person should not deliberately act against a certain judgment of conscience.","Une personne ne doit pas agir délibérément contre un jugement certain de conscience."],
  breakpoint:["Conscience obliges a person to avoid what he judges evil, but it does not create the truth of the act. A mistaken judgment remains possible, and even a sincere theologian's difficulty with non-irreformable teaching does not confer independent doctrinal authority on private conscience (Aquinas I–II q.19 aa.5–6; Donum Veritatis §28).","La conscience oblige à éviter ce que l’on juge mauvais, mais elle ne crée pas la vérité de l’acte. Un jugement erroné demeure possible, et même la difficulté sincère d’un théologien devant un enseignement non irréformable ne confère pas à sa conscience une autorité doctrinale autonome (saint Thomas, I–II, q.19, a.5–6 ; Donum Veritatis, §28)."],
  catholicCase:["Catholic teaching therefore joins two duties: follow conscience and form conscience. Formation includes seeking evidence, understanding authoritative teaching, examining motives and remaining willing to correct an error.","L’enseignement catholique unit donc deux devoirs : suivre sa conscience et former sa conscience. Cette formation comprend la recherche des preuves, la compréhension de l’enseignement autoritatif, l’examen des motifs et la disposition à corriger une erreur."],
  counter:["Doesn’t “form your conscience” just mean “make it agree with the Church”?","« Former sa conscience » ne signifie-t-il pas simplement « la faire coïncider avec l’Église » ?"],
  response:["Donum Veritatis §§28–30 addresses theologians who have serious difficulties with non-irreformable teaching: it demands patient inquiry, loyalty to the Magisterium and readiness to revise their views. The instruction does not turn private conscience into an alternative teaching authority. Every Catholic must seek to form conscience truthfully rather than treat sincere disagreement as permission to disregard a moral norm.","Donum Veritatis (§§28–30) traite des théologiens éprouvant de sérieuses difficultés devant un enseignement non irréformable : il demande une recherche patiente, la fidélité au Magistère et la disponibilité à réviser leurs conclusions. Ce texte ne fait pas de la conscience privée une autorité doctrinale parallèle. Tout catholique doit former sa conscience dans la vérité et ne peut tenir un désaccord sincère pour une permission de méconnaître une norme morale."],
  bottom:["Conscience binds, but conscience can err. The Catholic task is neither blind obedience nor private infallibility, but sincere judgment disciplined by truth.","La conscience oblige, mais elle peut se tromper. La tâche catholique n’est ni l’obéissance aveugle ni l’infaillibilité privée, mais un jugement sincère discipliné par la vérité."]
},
"CSE018":{
  opposition:["Curran argues that non-infallible teaching deserves religious respect but may be erroneous; he defends qualified public theological dissent, not the abolition of the Church's teaching office. When serious theologians disagree on a particular judgment, what weight must Catholics still give the authentic Magisterium?","Curran soutient qu'un enseignement non infaillible mérite un respect religieux mais peut comporter une erreur ; il défend un dissentiment théologique public et limité, non l'abolition du magistère de l'Église. Lorsque des théologiens sérieux contestent un jugement particulier, quel poids les catholiques doivent-ils encore donner au magistère authentique ?"],
  appeal:["Curran's distinction between levels of magisterial teaching has a real basis: not every pronouncement is a definitive dogmatic definition. Lay Catholics need reliable guidance and cannot independently reproduce every specialist's research.","La distinction de Curran entre les degrés du magistère repose sur une réalité : toute déclaration ne constitue pas une définition dogmatique définitive. Les fidèles ont besoin d’un guide sûr et ne peuvent refaire seuls les recherches de chaque spécialiste."],
  concession:["There are genuine open questions in Catholic theology, and expert disagreement can be evidence that a matter is not settled.","Il existe de véritables questions ouvertes en théologie catholique, et le désaccord d’experts peut indiquer qu’une question n’est pas tranchée."],
  breakpoint:["The existence of dissent is not a measure of doctrinal authority. Even non-definitive authentic teaching calls for religious submission appropriate to its status, and the number of dissenting theologians does not itself free the faithful to disregard it (Donum Veritatis §§23–28).","L’existence de dissensions n’est pas une mesure de l’autorité doctrinale. Même un enseignement authentique non définitif demande l’adhésion religieuse qui correspond à son statut ; le nombre de théologiens dissidents ne dispense pas à lui seul les fidèles d’en tenir compte (Donum Veritatis, §§23–28)."],
  catholicCase:["Catholic theology distinguishes disputed questions from authoritative moral teaching. Donum Veritatis explicitly allows serious difficulty and further inquiry while rejecting the idea that the Magisterium is merely one opinion among competing schools.","La théologie catholique distingue les questions disputées de l’enseignement moral autoritatif. Donum Veritatis reconnaît la possibilité de difficultés sérieuses et de recherches ultérieures tout en rejetant l’idée que le Magistère soit simplement une opinion parmi des écoles concurrentes."],
  counter:["But theologians sometimes challenge authoritative teaching precisely because they think the argument is defective.","Mais des théologiens contestent parfois un enseignement autoritatif précisément parce qu’ils jugent l’argument défectueux."],
  response:["Where a teaching is genuinely non-irreformable, serious difficulties can warrant disciplined examination; they do not create an automatic permission to contradict the teaching. Donum Veritatis §§28–31 demands an honest search for resolution, loyalty to the Magisterium and avoidance of treating theologians as a competing authority.","Lorsqu’un enseignement n’est réellement pas irréformable, des difficultés sérieuses peuvent justifier un examen rigoureux ; elles ne donnent pas automatiquement la permission de contredire l’enseignement. Donum Veritatis (§§28–31) demande une recherche loyale de solution, la fidélité au magistère et le refus de substituer une autorité théologique concurrente."],
  bottom:["The number of dissenting theologians does not settle the issue. First determine whether the question is actually open and what authority the disputed teaching possesses.","Le nombre de théologiens dissidents ne tranche pas la question. Il faut d’abord déterminer si la matière est réellement ouverte et quelle autorité possède l’enseignement contesté."]
},
"CSE020":{
  opposition:["An entrenched habit can involve strong urges and reduced control. Does this diminish personal responsibility for a particular act, even when the act itself is morally wrong?","Une habitude enracinée peut s’accompagner d’impulsions fortes et d’un contrôle diminué. Cela réduit-il la responsabilité d’un acte particulier, même lorsque l’acte demeure moralement mauvais ?"],
  appeal:["Outwardly identical acts can involve very different degrees of freedom, deliberation and compulsion.","Des actes extérieurement identiques peuvent impliquer des degrés très différents de liberté, de délibération et de compulsion."],
  concession:["Knowledge and freedom can be reduced by fear, anxiety, immaturity or an acquired habit. Yet not every habitual choice is involuntary: the degree of deliberation in the concrete act remains decisive (Aquinas I–II qq.77–78; Catechism §2352).","La connaissance et la liberté peuvent être diminuées par la peur, l’anxiété, l’immaturité ou une habitude acquise. Tout acte habituel n’est pourtant pas involontaire : le degré de délibération dans l’acte concret demeure déterminant (saint Thomas, I–II, q.77–78 ; Catéchisme, §2352)."],
  breakpoint:["A strong habit may impede freedom without abolishing it. Aquinas distinguishes sin from prior passion (I–II q.77) from sin through knowingly chosen vice (q.78); those are not identical. Scientific literature about drug addiction cannot establish a sexual-addiction diagnosis or determine someone's moral guilt.","Une habitude forte peut entraver la liberté sans l’abolir. Saint Thomas distingue le péché sous l’effet d’une passion préalable (I–II, q.77) de celui qui procède d’un vice sciemment choisi (q.78) ; ces situations ne sont pas identiques. Les recherches sur la toxicomanie ne prouvent ni un diagnostic de dépendance sexuelle ni la culpabilité morale d’une personne."],
  catholicCase:["Traditional moral analysis examines knowledge and freedom in the concrete act, but also whether an earlier voluntary choice helped create the condition that later weakened deliberation. Aquinas I–II q.77 a.7 distinguishes a passion involuntary in its origin from one voluntary in its cause; q.78 addresses knowingly chosen vice. Neither distinction authorizes an outsider to presume an individual's guilt merely from repetition.","L'analyse morale traditionnelle examine la connaissance et la liberté dans l'acte concret, mais aussi si un choix volontaire antérieur a contribué à créer la condition qui a ensuite affaibli la délibération. Saint Thomas (I–II, q.77, a.7) distingue la passion involontaire dans son origine de celle qui est volontaire dans sa cause ; la q.78 traite du vice sciemment choisi. Aucune de ces distinctions n'autorise un tiers à présumer la culpabilité d'une personne du seul fait de la répétition."],
  counter:["Isn’t that impossible to measure reliably?","N’est-ce pas impossible à mesurer avec fiabilité ?"],
  response:["Often it is difficult, which is why categorical judgments about another person’s mortal guilt are unsafe. Difficulty of measuring culpability, however, does not change the objective moral character of the act.","C’est souvent difficile, raison pour laquelle les jugements catégoriques sur la culpabilité mortelle d’autrui sont imprudents. Mais la difficulté de mesurer la culpabilité ne change pas le caractère moral objectif de l’acte."],
  bottom:["Habit can reduce responsibility, but not automatically. Objective act and subjective culpability must remain distinct.","L’habitude peut réduire la responsabilité, mais pas automatiquement. L’acte objectif et la culpabilité subjective doivent rester distincts."]
},
"CSE021":{
  opposition:["Freud's 1908 essay argues that the prevailing 'civilized' sexual code can contribute to nervous suffering and that people's capacity for sublimation differs. This is a historically situated argument about sexual restrictions, not a controlled study of present-day Catholic chastity. Does the possibility of such suffering count against treating every form of sexual restraint as healthy?","Dans son essai de 1908, Freud soutient que le code sexuel « civilisé » de son époque peut contribuer à la souffrance nerveuse et que la capacité de sublimation varie selon les personnes. Cet argument, situé dans son contexte historique, n'est pas une étude contrôlée de la chasteté catholique contemporaine. La possibilité de telles souffrances met-elle en cause l'idée que toute retenue sexuelle serait saine ?"],
  appeal:["The criticism has force when chastity is taught as shame, disgust toward the body or constant anxiety about temptation.","La critique est forte lorsque la chasteté est enseignée comme honte, dégoût du corps ou anxiété constante devant la tentation."],
  concession:["Bad formation can become repressive. Sexual desire is part of human nature and is not itself sinful.","Une mauvaise formation peut devenir répressive. Le désir sexuel appartient à la nature humaine et n’est pas en lui-même pécheur."],
  breakpoint:["Restraint of desire is not equivalent to repression. Mature human agency includes ordering powerful desires rather than simply expressing them whenever they arise.","La maîtrise du désir n’équivaut pas à la répression. L’action humaine mûre implique d’ordonner des désirs puissants plutôt que de les exprimer chaque fois qu’ils surgissent."],
  catholicCase:["In Catholic virtue ethics, chastity is integration under reason: married and unmarried people both learn to direct sexuality according to their state and duties. The goal is not numbness but freedom from being ruled by appetite.","Dans l’éthique catholique des vertus, la chasteté est une intégration sous la raison : mariés et célibataires apprennent à orienter la sexualité selon leur état et leurs devoirs. Le but n’est pas l’insensibilité, mais la liberté à l’égard de la domination de l’appétit."],
  counter:["But suppression of desire can still cause psychological harm.","Mais la suppression du désir peut tout de même causer un dommage psychologique."],
  response:["An education based on panic, shame or repression can aggravate suffering, which must be taken seriously. But Freud's 1908 causal theory is not a contemporary clinical demonstration that Catholic chastity itself causes illness. Chastity in Aquinas (II–II q.151 a.1) is a virtue ordering desire through reason, not contempt for the body; psychological care remains appropriate where distress is real.","Une éducation fondée sur la panique, la honte ou le refoulement peut aggraver la souffrance, qu’il faut prendre au sérieux. Mais la théorie causale de Freud en 1908 n’est pas une démonstration clinique contemporaine selon laquelle la chasteté catholique cause elle-même des maladies. Chez saint Thomas (II–II, q.151, a.1), la chasteté ordonne le désir par la raison, sans mépris du corps ; un accompagnement psychologique reste approprié lorsque la souffrance est réelle."],
  bottom:["Chastity is not the denial of sexuality. Properly understood, it is the discipline by which sexuality serves the good of the person rather than governing the person.","La chasteté n’est pas la négation de la sexualité. Bien comprise, elle est la discipline par laquelle la sexualité sert le bien de la personne au lieu de la gouverner."]
},
"CSE029":{
  opposition:["A qualitative study based on interviews with 15 US Catholic priests examined perceived benefits and psychological difficulties associated with celibacy and obedience. It can illuminate participants' experiences, but cannot establish how common these outcomes are among all priests or prove that celibacy causes them. What pastoral responsibilities follow from reported distress or isolation?","Une étude qualitative fondée sur des entretiens avec quinze prêtres catholiques américains examine des bienfaits perçus et des difficultés psychologiques liés au célibat et à l'obéissance. Elle éclaire leur expérience, mais ne mesure pas la fréquence de ces situations chez l'ensemble des prêtres et n'établit pas que le célibat les cause. Quelles responsabilités pastorales découlent des souffrances ou de l'isolement rapportés ?"],
  appeal:["Celibacy can indeed be lived badly, and human beings genuinely need intimacy, friendship and belonging.","Le célibat peut réellement être mal vécu, et l’être humain a véritablement besoin d’intimité, d’amitié et d’appartenance."],
  concession:["Celibacy is not automatically healthy. Isolation, poor formation, emotional immaturity or lack of community can seriously damage a person.","Le célibat n’est pas automatiquement sain. L’isolement, une mauvaise formation, l’immaturité affective ou l’absence de communauté peuvent gravement nuire à une personne."],
  breakpoint:["The need for intimacy and attachment does not establish that sexual activity itself is a psychological necessity.","Le besoin d’intimité et d’attachement n’établit pas que l’activité sexuelle elle-même soit une nécessité psychologique."],
  catholicCase:["Catholic tradition treats continence as humanly possible while insisting on friendship, community, prayer and disciplined life. It distinguishes the need for love and relationship from a supposed necessity of sexual expression.","La tradition catholique considère la continence comme humainement possible tout en insistant sur l’amitié, la communauté, la prière et une vie disciplinée. Elle distingue le besoin d’amour et de relation d’une prétendue nécessité d’expression sexuelle."],
  counter:["But even if possible, why call it a higher vocation?","Mais même si c’est possible, pourquoi l’appeler une vocation supérieure ?"],
  response:["That is a theological question distinct from psychological health. Catholicism values consecrated virginity because of its undivided dedication to God, not because marriage or sexuality are dirty.","C’est une question théologique distincte de la santé psychologique. Le catholicisme valorise la virginité consacrée en raison de son dévouement sans partage à Dieu, non parce que le mariage ou la sexualité seraient impurs."],
  bottom:["A 15-person qualitative study cannot establish the prevalence or cause of psychological distress among all celibates. Celibacy is not a psychiatric diagnosis; each person's health, relationships and support need individual assessment.","Une étude qualitative de quinze personnes ne permet d'établir ni la prévalence ni la cause de la détresse chez tous les célibataires. Le célibat n'est pas un diagnostic psychiatrique ; la santé, les relations et le soutien de chacun exigent un examen individuel."]
},
"CSE031":{
  opposition:["If two people sincerely love each other, are committed and intend to marry, requiring a wedding before sex looks like making a ceremony more important than the relationship.","Si deux personnes s’aiment sincèrement, sont engagées et ont l’intention de se marier, exiger le mariage avant les relations sexuelles semble donner plus d’importance à une cérémonie qu’à la relation."],
  appeal:["Love, commitment and serious intention matter morally; a merely casual encounter is not the same relational reality as a devoted couple.","L’amour, l’engagement et l’intention sérieuse comptent moralement ; une rencontre occasionnelle n’est pas la même réalité relationnelle qu’un couple profondément engagé."],
  concession:["A loving engaged couple possesses genuine goods that a casual sexual relationship may lack.","Un couple fiancé et aimant possède de véritables biens qu’une relation sexuelle occasionnelle peut ne pas avoir."],
  breakpoint:["The missing step is the claim that intention to marry already creates marriage. It does not create the public, exclusive and binding covenant or its present rights and duties.","L’étape manquante est l’idée que l’intention de se marier crée déjà le mariage. Elle ne crée ni l’alliance publique, exclusive et obligatoire, ni ses droits et devoirs présents."],
  catholicCase:["Matrimonial consent establishes a present marriage, not merely a promise to marry later (CIC can. 1057). Catholics ordinarily must also observe canonical form (can. 1108), subject to exceptions and dispensations established by law (including cann. 1116 and 1127 §2). A sincere, exclusive engagement is not yet the matrimonial covenant and does not itself confer conjugal rights.","Le consentement matrimonial établit le mariage présent, et non une simple promesse de se marier plus tard (CIC, can. 1057). Les catholiques doivent normalement observer la forme canonique (can. 1108), sous réserve des exceptions et dispenses prévues par le droit (notamment cann. 1116 et 1127 §2). Des fiançailles sincères et exclusives ne constituent pas encore l'alliance matrimoniale et ne confèrent pas, à elles seules, les droits conjugaux."],
  counter:["But modern contraception separates sex from parenthood, so why must the legal or sacramental bond come first?","Mais la contraception moderne sépare la sexualité de la parentalité ; pourquoi le lien juridique ou sacramentel doit-il venir d’abord ?"],
  response:["That argument assumes contraception changes the moral meaning of sex rather than merely reducing the likelihood of conception. Catholicism rejects that premise: intercourse remains the kind of act naturally connected to generation and therefore to stable parental responsibility.","Cet argument suppose que la contraception change la signification morale de la sexualité au lieu de simplement réduire la probabilité de conception. Le catholicisme rejette cette prémisse : l’union demeure le type d’acte naturellement lié à la génération et donc à une responsabilité parentale stable."],
  bottom:["Love matters, but love alone does not create marriage. The Catholic claim is that sexual union belongs to the covenant that makes permanent fidelity and parenthood its objective framework.","L’amour compte, mais l’amour seul ne crée pas le mariage. L’affirmation catholique est que l’union sexuelle appartient à l’alliance qui fait de la fidélité permanente et de la parentalité son cadre objectif."]
}
});
