export const CSE_DEBATES_035_064=Object.freeze({
"CSE035":{
  opposition:["Living together before marriage is practical. It lets a couple test compatibility, finances, habits and sexual chemistry before making a permanent commitment.","Vivre ensemble avant le mariage est pratique. Cela permet de tester la compatibilité, les finances, les habitudes et l’entente sexuelle avant de prendre un engagement permanent."],
  appeal:["The concern is reasonable: marriage is serious, and people should not enter it blindly.","La préoccupation est raisonnable : le mariage est sérieux, et on ne doit pas y entrer aveuglément."],
  concession:["Couples should learn one another’s habits, expectations, weaknesses and practical compatibility before marriage.","Les couples doivent apprendre à connaître les habitudes, les attentes, les faiblesses et la compatibilité pratique de l’autre avant le mariage."],
  breakpoint:["The argument assumes that simulating married life is the best or necessary way to discern marriage. It also tends to combine several distinct questions: sexual relations, shared housing, scandal and practical dependence.","L’argument suppose que simuler la vie conjugale est le meilleur ou le seul moyen de discerner le mariage. Il tend aussi à confondre plusieurs questions distinctes : relations sexuelles, logement commun, scandale et dépendance pratique."],
  catholicCase:["If cohabitation includes sex, Catholic teaching judges the sexual relations as outside marriage. If it is genuinely continent, sharing a residence is not itself fornication, but the couple must still assess proximate occasion, scandal and whether financial or emotional entanglement makes discernment less free.","Si la cohabitation comprend des relations sexuelles, l’enseignement catholique les juge comme ayant lieu hors mariage. Si elle est réellement continente, partager un logement n’est pas en soi une fornication, mais il faut encore évaluer l’occasion prochaine, le scandale et le risque qu’une dépendance financière ou affective rende le discernement moins libre."],
  counter:["But many married couples discover incompatibilities only after living together. Isn’t cohabitation simply prudent risk reduction?","Mais beaucoup de couples découvrent des incompatibilités seulement après avoir vécu ensemble. La cohabitation n’est-elle pas simplement une réduction prudente du risque ?"],
  response:["Prudence requires learning enough before marriage, but not every risk-reduction strategy is morally neutral. Discernment can occur through time, family life, conflict, finances, expectations and chastity without treating marital rights as already possessed.","La prudence exige de suffisamment connaître l’autre avant le mariage, mais toute stratégie de réduction du risque n’est pas moralement neutre. Le discernement peut se faire dans le temps, la vie familiale, les conflits, les finances, les attentes et la chasteté sans traiter les droits matrimoniaux comme déjà acquis."],
  bottom:["Cohabitation is not one moral category. Sexual cohabitation is direct; chaste co-residence requires prudential case analysis rather than slogans.","La cohabitation n’est pas une seule catégorie morale. La cohabitation sexuelle pose un problème direct ; une co-résidence chaste exige une analyse prudentielle du cas."]
},
"CSE043":{
  opposition:["Marriage should be defined by love and commitment, not by the sex of the partners. Two men or two women can love, sacrifice and remain faithful just as a man and a woman can.","Le mariage devrait être défini par l’amour et l’engagement, non par le sexe des partenaires. Deux hommes ou deux femmes peuvent aimer, se sacrifier et rester fidèles tout comme un homme et une femme."],
  appeal:["Affection, loyalty, sacrifice and stable commitment are genuine relational goods.","L’affection, la loyauté, le sacrifice et l’engagement stable sont de véritables biens relationnels."],
  concession:["A same-sex relationship can contain real friendship, fidelity and self-sacrifice.","Une relation de même sexe peut contenir une véritable amitié, fidélité et sacrifice de soi."],
  breakpoint:["The unresolved premise is that these goods alone define marriage. Catholicism argues that marriage also has a bodily form: the union of man and woman, naturally ordered to generation and family life.","La prémisse non démontrée est que ces biens suffisent à définir le mariage. Le catholicisme affirme que le mariage possède aussi une forme corporelle : l’union de l’homme et de la femme, naturellement ordonnée à la génération et à la vie familiale."],
  catholicCase:["Marriage is not simply the strongest possible friendship. Its sexual union is male-female in kind, and that kind of union is the one through which children naturally come into being and receive a mother and father.","Le mariage n’est pas simplement l’amitié la plus forte possible. Son union sexuelle est de type homme-femme, et c’est par ce type d’union que les enfants viennent naturellement à l’existence et reçoivent une mère et un père."],
  counter:["But many heterosexual marriages never have children.","Mais beaucoup de mariages hétérosexuels n’ont jamais d’enfants."],
  response:["Actual fertility is not the criterion. The argument concerns the kind of union, not whether conception occurs in this couple. An infertile man and woman still unite in the generative type of bodily act even when age or pathology prevents its result.","La fécondité effective n’est pas le critère. L’argument concerne le type d’union, non le fait qu’une conception se produise dans ce couple. Un homme et une femme stériles accomplissent encore le type d’union corporelle générative même lorsque l’âge ou la pathologie en empêche le résultat."],
  bottom:["The disagreement is not about whether same-sex couples can love. It is about whether love and commitment exhaust the definition of marriage.","Le désaccord ne porte pas sur la capacité des couples de même sexe à aimer. Il porte sur la question de savoir si l’amour et l’engagement épuisent la définition du mariage."]
},
"CSE044":{
  opposition:["If infertile heterosexual couples can marry, procreation clearly cannot be essential to marriage. Excluding same-sex couples on procreative grounds is therefore inconsistent.","Si des couples hétérosexuels stériles peuvent se marier, la procréation ne peut manifestement pas être essentielle au mariage. Exclure les couples de même sexe pour des raisons procréatives est donc incohérent."],
  appeal:["Actual ability to conceive is not a condition for marriage; Catholic law itself does not exclude sterile couples.","La capacité effective de concevoir n’est pas une condition du mariage ; le droit catholique lui-même n’exclut pas les couples stériles."],
  concession:["Actual fertility is not required for a valid marriage, and infertility can occur through age or pathology without fault.","La fécondité effective n’est pas requise pour la validité du mariage, et l’infertilité peut résulter de l’âge ou d’une pathologie sans faute."],
  breakpoint:["Not producing a child is not equivalent to not being the kind of union ordered to generation; those are different claims.","Ne pas produire d’enfant n’équivaut pas à ne pas être le type d’union ordonné à la génération ; ce sont deux affirmations différentes."],
  catholicCase:["Catholic law distinguishes sterility from impotence because the relevant structure is the conjugal kind of union. A sterile husband and wife can perform the marital act even if conception cannot occur.","Le droit catholique distingue stérilité et impuissance parce que la structure pertinente est celle de l’union conjugale. Un mari et une femme stériles peuvent accomplir l’acte matrimonial même si la conception est impossible."],
  counter:["Isn’t “kind of union” just a way of defining the conclusion into the premise?","Le « type d’union » n’est-il pas simplement une manière de placer la conclusion dans la prémisse ?"],
  response:["Only if no account is given of why the distinction matters. The Catholic account points to the bodily complementarity of the act and its natural relation to generation, independent of whether that relation succeeds in each instance.","Seulement si aucune raison n’est donnée pour expliquer pourquoi la distinction compte. L’explication catholique invoque la complémentarité corporelle de l’acte et son rapport naturel à la génération, indépendamment du fait que ce rapport aboutisse dans chaque cas."],
  bottom:["Infertility concerns outcome; the marriage argument concerns the structure of the union. Confusing those two produces the apparent inconsistency.","L’infertilité concerne le résultat ; l’argument sur le mariage concerne la structure de l’union. Confondre les deux produit l’apparente incohérence."]
},
"CSE045":{
  opposition:["Marriage today is mainly about love, companionship and mutual support. Making procreation central imposes an outdated biological model on a personal relationship.","Aujourd’hui, le mariage concerne surtout l’amour, la compagnie et le soutien mutuel. Faire de la procréation un élément central impose un modèle biologique dépassé à une relation personnelle."],
  appeal:["Companionship and mutual love are obviously central to a good marriage, and a purely reproductive account would be impoverished.","La compagnie et l’amour mutuel sont manifestement centraux dans un bon mariage, et une conception purement reproductive serait appauvrissante."],
  concession:["Catholic teaching strongly affirms mutual love, help, sanctification and companionship.","L’enseignement catholique affirme fortement l’amour mutuel, l’aide, la sanctification et la compagnie."],
  breakpoint:["The false choice is between personal love and procreation. Catholic marriage includes both rather than reducing marriage to either one.","Le faux dilemme oppose l’amour personnel et la procréation. Le mariage catholique inclut les deux au lieu de réduire le mariage à l’un ou l’autre."],
  catholicCase:["The traditional hierarchy of ends gives procreation and education of children a constitutive place while also recognizing mutual aid and the spouses’ growth in virtue and charity.","La hiérarchie traditionnelle des fins donne à la procréation et à l’éducation des enfants une place constitutive tout en reconnaissant l’aide mutuelle et la croissance des époux dans la vertu et la charité."],
  counter:["But a childless marriage may be deeply loving and complete as a relationship.","Mais un mariage sans enfant peut être profondément aimant et complet comme relation."],
  response:["Yes. Lack of children does not make a marriage unreal or loveless. The claim is not that every marriage must achieve every good, but that the institution itself is ordered to goods larger than companionship alone.","Oui. L’absence d’enfants ne rend pas un mariage irréel ou sans amour. L’affirmation n’est pas que chaque mariage doit réaliser tous les biens, mais que l’institution elle-même est ordonnée à des biens plus larges que la seule compagnie."],
  bottom:["Catholic marriage is neither merely reproductive nor merely companionate. It joins faithful spousal love with the generative and educational goods of family life.","Le mariage catholique n’est ni purement reproductif ni purement compagnonnique. Il unit l’amour fidèle des époux aux biens génératifs et éducatifs de la vie familiale."]
},
"CSE049":{
  opposition:["If love disappears or married life becomes intolerable, permanent marriage can become cruel. A humane institution should allow people to end a failed relationship and begin again.","Si l’amour disparaît ou si la vie conjugale devient intolérable, le mariage permanent peut devenir cruel. Une institution humaine devrait permettre de mettre fin à une relation échouée et de recommencer."],
  appeal:["Abandonment, grave conflict and abuse can make continued common life seriously harmful or unsafe; Catholic teaching permits separation in proportionate cases.","L’abandon, le conflit grave et les abus peuvent rendre la vie commune gravement nuisible ou dangereuse ; l’enseignement catholique permet la séparation dans des cas proportionnés."],
  concession:["Separation can be justified, and civil measures may be necessary to protect spouses, children or property.","La séparation peut être justifiée, et des mesures civiles peuvent être nécessaires pour protéger les époux, les enfants ou les biens."],
  breakpoint:["Ending common life and dissolving the matrimonial bond are distinct acts. Failure of the relationship does not by itself establish that the covenant has ceased to exist.","Mettre fin à la vie commune et dissoudre le lien matrimonial sont deux actes distincts. L’échec de la relation n’établit pas à lui seul que l’alliance a cessé d’exister."],
  catholicCase:["Christ’s teaching on divorce is taken to mean that a valid consummated marriage establishes a bond not dependent on continuing affection. Permanence protects the meaning of the original consent: “for life” is not conditional on future satisfaction.","L’enseignement du Christ sur le divorce est compris comme signifiant qu’un mariage valide et consommé établit un lien qui ne dépend pas de la persistance de l’affection. La permanence protège le sens du consentement initial : « pour la vie » n’est pas conditionné par la satisfaction future."],
  counter:["But consent cannot bind people to unforeseeable misery forever.","Mais le consentement ne peut lier des personnes à une misère imprévisible pour toujours."],
  response:["It can bind them to a covenant while still allowing separation from dangerous or destructive common life. The Catholic claim is narrower than “stay physically together no matter what”: the bond remains even where common life cannot.","Il peut les lier à une alliance tout en permettant la séparation d’une vie commune dangereuse ou destructrice. L’affirmation catholique est plus étroite que « rester physiquement ensemble quoi qu’il arrive » : le lien demeure même lorsque la vie commune ne peut plus demeurer."],
  bottom:["Indissolubility does not mean compulsory cohabitation under every condition. It means that grave failure does not by itself dissolve a valid marital bond.","L’indissolubilité ne signifie pas cohabitation obligatoire en toute circonstance. Elle signifie qu’un échec grave ne dissout pas par lui-même un lien matrimonial valide."]
},
"CSE050":{
  opposition:["If a marriage is dead, abusive or irretrievably broken, forbidding remarriage punishes the innocent spouse and elevates a failed past relationship over a real new one.","Si un mariage est mort, abusif ou irrémédiablement brisé, interdire le remariage punit le conjoint innocent et élève une relation passée échouée au-dessus d’une nouvelle relation réelle."],
  appeal:["The burden can be severe, especially for an abandoned spouse who did not cause the breakdown.","Le fardeau peut être très lourd, surtout pour un conjoint abandonné qui n’a pas causé la rupture."],
  concession:["Catholic teaching does not deny the injustice or loneliness an innocent spouse may suffer, and it permits separation where necessary.","L’enseignement catholique ne nie ni l’injustice ni la solitude que peut subir un conjoint innocent, et il permet la séparation lorsque nécessaire."],
  breakpoint:["The argument assumes that a failed common life equals a dissolved bond. Catholic teaching distinguishes those realities.","L’argument suppose qu’une vie commune échouée équivaut à un lien dissous. L’enseignement catholique distingue ces réalités."],
  catholicCase:["If the first marriage was valid, a later civil union cannot create freedom to marry while the spouse still lives. A declaration of nullity is different because it concerns whether a valid marriage ever arose at the beginning.","Si le premier mariage était valide, une union civile ultérieure ne peut créer la liberté de se marier tant que le conjoint vit. Une déclaration de nullité est différente car elle porte sur la question de savoir si un mariage valide a réellement existé dès le début."],
  counter:["Isn’t annulment just Catholic divorce under another name?","La nullité n’est-elle pas simplement un divorce catholique sous un autre nom ?"],
  response:["No in principle: divorce ends a recognized marriage; nullity judges that a valid bond was absent from the start because an essential requirement was missing. Whether tribunals apply that distinction well in a particular case is a separate question.","Non en principe : le divorce met fin à un mariage reconnu ; la nullité juge qu’un lien valide n’existait pas dès le début faute d’une condition essentielle. La question de savoir si les tribunaux appliquent bien cette distinction dans un cas concret est distincte."],
  bottom:["The rule on remarriage follows from indissolubility, not from denial that a marriage can fail catastrophically.","La règle sur le remariage découle de l’indissolubilité, non du refus d’admettre qu’un mariage puisse échouer de manière catastrophique."]
},
"CSE051":{
  opposition:["Within marriage, whatever both spouses freely agree to sexually should be permissible. Marriage exists precisely to provide a legitimate sexual relationship.","Dans le mariage, tout ce à quoi les deux époux consentent librement devrait être permis sexuellement. Le mariage existe précisément pour fournir une relation sexuelle légitime."],
  appeal:["Mutual consent and marital intimacy are real goods, and marriage does create rights and freedoms absent outside it.","Le consentement mutuel et l’intimité conjugale sont de vrais biens, et le mariage crée des droits et des libertés absents hors de lui."],
  concession:["Marriage genuinely changes the moral context of sexual activity, and spouses have a wide sphere of legitimate affection and intimacy.","Le mariage change réellement le contexte moral de l’activité sexuelle, et les époux disposent d’un large espace d’affection et d’intimité légitimes."],
  breakpoint:["The inference from “marriage permits sex” to “marriage sanctifies every sexual choice” does not follow. Consent cannot authorize what contradicts fidelity, justice or the integrity of the marital act.","L’inférence de « le mariage permet la sexualité » à « le mariage sanctifie tout choix sexuel » ne suit pas. Le consentement ne peut autoriser ce qui contredit la fidélité, la justice ou l’intégrité de l’acte conjugal."],
  catholicCase:["Casti Connubii explicitly denies that spouses can concede to each other something contrary to divine law. Marriage creates a moral relationship; it does not suspend moral analysis.","Casti Connubii nie explicitement que les époux puissent se concéder mutuellement quelque chose de contraire à la loi divine. Le mariage crée une relation morale ; il ne suspend pas l’analyse morale."],
  counter:["But if neither spouse is harmed and both desire the act, what remaining moral problem is there?","Mais si aucun conjoint n’est lésé et que les deux désirent l’acte, quel problème moral reste-t-il ?"],
  response:["The same issue as in consent generally: the moral object cannot be reduced to mutual willingness. The act must still be compatible with marital fidelity, chastity and the meaning of conjugal union.","Le même problème que pour le consentement en général : l’objet moral ne peut être réduit à la volonté mutuelle. L’acte doit encore être compatible avec la fidélité, la chasteté et la signification de l’union conjugale."],
  bottom:["Marriage makes conjugal sexuality legitimate; it does not make every consensual sexual choice good.","Le mariage rend légitime la sexualité conjugale ; il ne rend pas bon tout choix sexuel consensuel."]
},
"CSE054":{
  opposition:["Traditional talk of the “marital debt” implies that marriage gives each spouse a right to sex, so refusing a spouse may itself be unjust. Modern claims about marital coercion therefore seem inconsistent with older teaching.","Le langage traditionnel du « devoir conjugal » implique que le mariage donne à chaque conjoint un droit aux relations sexuelles ; refuser peut donc être injuste. Les affirmations modernes sur la coercition conjugale semblent ainsi incompatibles avec l’enseignement ancien."],
  appeal:["The tradition really does teach reciprocal marital rights and duties, and it would be dishonest to erase that fact.","La tradition enseigne réellement des droits et devoirs conjugaux réciproques, et il serait malhonnête d’effacer ce fait."],
  concession:["A spouse can sometimes act selfishly or unjustly by persistently refusing legitimate marital relations without proportionate reason.","Un conjoint peut parfois agir égoïstement ou injustement en refusant continuellement des relations conjugales légitimes sans raison proportionnée."],
  breakpoint:["A right to request a marital act is not a right to force one. Moral obligation and coercive entitlement are different concepts.","Un droit à demander l’acte conjugal n’est pas un droit à l’imposer par la force. L’obligation morale et le pouvoir coercitif sont des concepts différents."],
  catholicCase:["Traditional reciprocal duties are bounded by reason, charity, health and the moral character of the act. Humanae Vitae explicitly says an imposed conjugal act that disregards the spouse’s condition and reasonable wishes is not an act of true love.","Les devoirs réciproques traditionnels sont limités par la raison, la charité, la santé et le caractère moral de l’acte. Humanae Vitae dit explicitement qu’un acte conjugal imposé sans égard à l’état et aux souhaits raisonnables du conjoint n’est pas un acte de véritable amour."],
  counter:["Then does the marital obligation have any practical meaning?","Le devoir conjugal a-t-il alors encore un sens pratique ?"],
  response:["Yes. It means spouses should not treat sexuality as purely individual property or use refusal manipulatively. But a moral duty is fulfilled through free human action, not violence or domination.","Oui. Cela signifie que les époux ne doivent pas traiter la sexualité comme une propriété purement individuelle ni utiliser le refus comme moyen de manipulation. Mais un devoir moral s’accomplit par un acte humain libre, non par violence ou domination."],
  bottom:["Marital rights are real and reciprocal; coercion is not one of those rights.","Les droits matrimoniaux sont réels et réciproques ; la coercition n’en fait pas partie."]
},
"CSE056":{
  opposition:["If both spouses agree to non-monogamy, adultery should no longer apply because no one is being deceived. Fidelity can be defined by the couple however they choose.","Si les deux époux acceptent la non-monogamie, l’adultère ne devrait plus s’appliquer puisqu’il n’y a aucune tromperie. Le couple peut définir la fidélité comme il l’entend."],
  appeal:["The argument correctly sees that secrecy and betrayal add serious wrongs to adultery, and consensual non-monogamy removes some of those wrongs.","L’argument voit justement que le secret et la trahison ajoutent des maux graves à l’adultère, et que la non-monogamie consensuelle en supprime certains."],
  concession:["An openly agreed arrangement differs morally from a secret affair because deception is absent.","Un arrangement ouvertement accepté diffère moralement d’une liaison secrète parce que la tromperie en est absente."],
  breakpoint:["The unresolved claim is that exclusivity is merely an optional private rule. Catholic marriage treats exclusivity as part of what matrimonial consent establishes, not as a clause spouses may later delete.","L’affirmation non démontrée est que l’exclusivité serait une simple règle privée facultative. Le mariage catholique considère l’exclusivité comme partie de ce qu’établit le consentement matrimonial, non comme une clause que les époux peuvent supprimer ensuite."],
  catholicCase:["The marital covenant is a mutual, exclusive gift. A spouse cannot authorize the other to treat a third person as a sexual partner without contradicting the form of that covenant.","L’alliance matrimoniale est un don mutuel et exclusif. Un conjoint ne peut autoriser l’autre à traiter une tierce personne comme partenaire sexuel sans contredire la forme de cette alliance."],
  counter:["But why can’t adults redefine their own covenant by mutual agreement?","Pourquoi des adultes ne pourraient-ils pas redéfinir leur propre alliance d’un commun accord ?"],
  response:["Because Catholicism holds that marriage has an objective structure prior to private preference. The same reason spouses cannot mutually agree to make the bond temporary while still calling it Catholic marriage applies to exclusivity.","Parce que le catholicisme soutient que le mariage possède une structure objective antérieure à la préférence privée. La même raison pour laquelle les époux ne peuvent convenir de rendre le lien temporaire tout en l’appelant mariage catholique vaut pour l’exclusivité."],
  bottom:["Mutual permission removes deception, not the contradiction with marital exclusivity.","La permission mutuelle supprime la tromperie, non la contradiction avec l’exclusivité matrimoniale."]
},
"CSE061":{
  opposition:["Contraception is simply a responsible technology that lets couples separate sex from unwanted pregnancy. If avoiding pregnancy is sometimes prudent, using an effective means to do so should be morally neutral.","La contraception est simplement une technologie responsable qui permet aux couples de séparer sexualité et grossesse non désirée. Si éviter une grossesse est parfois prudent, employer un moyen efficace devrait être moralement neutre."],
  appeal:["The argument starts from a point Catholic teaching accepts: spouses can have serious reasons to avoid pregnancy.","L’argument part d’un point que l’enseignement catholique accepte : des époux peuvent avoir de sérieuses raisons d’éviter une grossesse."],
  concession:["Responsible parenthood can require postponing pregnancy, sometimes for a long period.","La responsabilité parentale peut exiger de différer une grossesse, parfois longtemps."],
  breakpoint:["The false inference is that a legitimate end makes every means to that end morally equivalent.","L’inférence fausse est qu’une fin légitime rend moralement équivalents tous les moyens d’y parvenir."],
  catholicCase:["Catholic teaching identifies contraception by the chosen act: intercourse is performed while fertility is deliberately blocked or frustrated. Casti Connubii condemns that choice well before modern hormonal methods; later teaching preserves the same structure.","L’enseignement catholique identifie la contraception par l’acte choisi : l’union est accomplie tandis que la fécondité est délibérément bloquée ou frustrée. Casti Connubii condamne ce choix bien avant les méthodes hormonales modernes ; l’enseignement ultérieur conserve la même structure."],
  counter:["But why should the biological structure of an act determine morality?","Pourquoi la structure biologique d’un acte devrait-elle déterminer la morale ?"],
  response:["The Catholic argument is not “biology alone decides morality.” It is that the bodily form of the marital act participates in a human good—generation—and that deliberately choosing to negate that dimension while performing the act changes what is being chosen.","L’argument catholique n’est pas « la biologie seule décide de la morale ». Il affirme que la forme corporelle de l’acte conjugal participe à un bien humain — la génération — et que choisir délibérément d’en nier cette dimension tout en accomplissant l’acte change ce qui est choisi."],
  bottom:["The controversy is not whether avoiding pregnancy can be responsible. It is whether deliberately contracepting intercourse is a morally neutral means of doing so.","La controverse ne porte pas sur le fait qu’éviter une grossesse puisse être responsable. Elle porte sur la question de savoir si contracepter délibérément l’union est un moyen moralement neutre."]
},
"CSE063":{
  opposition:["NFP and contraception aim at the same result: sex without pregnancy. Calling one moral and the other immoral looks like a word game based on technology rather than intention.","La PFN et la contraception visent le même résultat : des relations sans grossesse. Dire que l’une est morale et l’autre immorale ressemble à un jeu de mots fondé sur la technique plutôt que sur l’intention."],
  appeal:["The remote intention can be identical: both couples may deliberately intend to avoid conception.","L’intention lointaine peut être identique : les deux couples peuvent vouloir délibérément éviter la conception."],
  concession:["NFP is not morally different because its users secretly want pregnancy. They may very clearly intend to avoid it.","La PFN n’est pas moralement différente parce que ses utilisateurs voudraient secrètement une grossesse. Ils peuvent très clairement vouloir l’éviter."],
  breakpoint:["The missing distinction is between the further intention and the act chosen as the means. Same end does not make different means the same moral act.","La distinction manquante est celle entre l’intention ultérieure et l’acte choisi comme moyen. Une même fin ne rend pas des moyens différents moralement identiques."],
  catholicCase:["Periodic continence chooses not to have intercourse during fertile periods. Contraception chooses to have intercourse while deliberately acting to render that intercourse infertile. Pius XII and Humanae Vitae explicitly distinguish those choices.","La continence périodique choisit de ne pas avoir de relations pendant les périodes fécondes. La contraception choisit d’avoir des relations tout en agissant délibérément pour rendre cette union inféconde. Pie XII et Humanae Vitae distinguent explicitement ces choix."],
  counter:["But abstaining only because conception might occur is still a deliberate anti-conception strategy. Isn’t that contraception by omission?","Mais s’abstenir uniquement parce qu’une conception pourrait survenir reste une stratégie délibérément anti-conception. N’est-ce pas une contraception par omission ?"],
  response:["Refraining from an act and performing it while altering it are not identical choices merely because they serve the same goal. Moral reasoning makes that distinction elsewhere as well. Moreover, periodic abstinence is not automatically virtuous: using it for selfish or disproportionate reasons can itself be morally defective.","S’abstenir d’un acte et l’accomplir tout en le modifiant ne sont pas des choix identiques simplement parce qu’ils servent la même fin. Le raisonnement moral fait cette distinction ailleurs aussi. De plus, la continence périodique n’est pas automatiquement vertueuse : l’employer pour des raisons égoïstes ou disproportionnées peut elle-même être moralement défectueuse."],
  bottom:["Same intention does not mean same act. The Catholic distinction concerns what the couple chooses to do to the marital act itself.","Même intention ne signifie pas même acte. La distinction catholique porte sur ce que le couple choisit de faire à l’acte conjugal lui-même."]
},
"CSE064":{
  opposition:["NFP is just Catholic contraception with a natural method. Couples track fertility specifically to prevent pregnancy, so the moral distinction seems cosmetic.","La PFN est simplement une contraception catholique utilisant une méthode naturelle. Les couples suivent la fécondité précisément pour empêcher une grossesse ; la distinction morale paraît cosmétique."],
  appeal:["The phrase is rhetorically effective because it focuses on intention and outcome, which often are the same.","La formule est rhétoriquement efficace parce qu’elle se concentre sur l’intention et le résultat, souvent identiques."],
  concession:["NFP can be used with a contraceptive mentality in the ordinary-language sense of selfishly refusing parenthood. Catholic teaching does not declare every use of periodic abstinence virtuous.","La PFN peut être utilisée avec une mentalité contraceptive au sens courant d’un refus égoïste de la parentalité. L’enseignement catholique ne déclare pas vertueux tout usage de la continence périodique."],
  breakpoint:["But the technical moral meaning of contraception concerns the act chosen, not merely the wish to avoid a child. Periodic abstinence does not render an act infertile; it chooses when not to perform the act.","Mais le sens moral technique de la contraception concerne l’acte choisi, non le seul désir d’éviter un enfant. La continence périodique ne rend pas un acte infécond ; elle choisit quand ne pas accomplir l’acte."],
  catholicCase:["That is why Pius XII can both permit recourse to infertile periods for serious reasons and reject direct contraception. The distinction predates contemporary NFP marketing.","C’est pourquoi Pie XII peut à la fois permettre le recours aux périodes infécondes pour de sérieuses raisons et rejeter la contraception directe. La distinction est antérieure au marketing contemporain de la PFN."],
  counter:["Isn’t this still overly focused on the physical act?","Cela ne reste-t-il pas excessivement centré sur l’acte physique ?"],
  response:["Only if moral object is reduced to anatomy. The claim is about what the will chooses to do: abstain, or perform intercourse while deliberately suppressing its fertility. That is an intentional difference, not merely a physical one.","Seulement si l’objet moral est réduit à l’anatomie. L’affirmation porte sur ce que la volonté choisit de faire : s’abstenir, ou accomplir l’union tout en supprimant délibérément sa fécondité. C’est une différence intentionnelle, non seulement physique."],
  bottom:["NFP can be used badly, but it is not contraception in the Catholic moral sense because the chosen means is different.","La PFN peut être mal utilisée, mais elle n’est pas une contraception au sens moral catholique parce que le moyen choisi est différent."]
}
});
