export const CSE_DEBATES_070_104=Object.freeze({
"CSE070":{
  opposition:["If one spouse insists on contraception, the other either cooperates or destroys the marriage by refusing sex. It seems unfair to burden the unwilling spouse with the other’s choice.","Si un conjoint impose la contraception, l’autre doit soit coopérer, soit risquer de détruire le mariage en refusant les relations. Il paraît injuste de faire porter au conjoint réticent le poids du choix de l’autre."],
  appeal:["The case is genuinely difficult because marital duties, coercion, peace of the household and personal moral responsibility can collide.","Le cas est réellement difficile parce que devoirs conjugaux, contrainte, paix du foyer et responsabilité morale personnelle peuvent entrer en conflit."],
  concession:["The spouses’ responsibility is not automatically identical. The one who chooses contraception bears a responsibility the reluctant spouse may not share.","La responsabilité des époux n’est pas automatiquement identique. Celui qui choisit la contraception porte une responsabilité que le conjoint réticent peut ne pas partager."],
  breakpoint:["The mistake is assuming that any participation equals approval. Moral cooperation depends on intention, what each spouse actually chooses, and what can reasonably be avoided.","L’erreur est de supposer que toute participation équivaut à une approbation. La coopération morale dépend de l’intention, de ce que chacun choisit réellement et de ce qui peut raisonnablement être évité."],
  catholicCase:["Casti Connubii §59 distinguishes the spouse choosing contraception from one who, for a grave reason, reluctantly tolerates what is not approved. The latter must not choose contraception and must not neglect charitable efforts to dissuade the partner. The passage concerns responsibility in a constrained situation, not permission to contracept.","Casti Connubii (§59) distingue le conjoint qui choisit la contraception de celui qui, pour une raison grave, tolère à regret ce qu'il n'approuve pas. Celui-ci ne doit ni choisir la contraception ni négliger de chercher charitablement à en détourner l'autre. Ce texte traite de la responsabilité en situation contrainte, non d'une permission de contracepter."],
  counter:["Doesn’t this become a loophole allowing contraception whenever the marriage is tense?","Cela ne devient-il pas une échappatoire permettant la contraception chaque fois que le mariage est tendu ?"],
  response:["No. The exception concerns the responsibility of the non-choosing spouse, not the moral goodness of contraception. Grave reasons, reluctance and absence of approval matter; the contraceptive act itself is not reclassified as good.","Non. L’exception concerne la responsabilité du conjoint qui ne choisit pas, non la bonté morale de la contraception. Les raisons graves, la réticence et l’absence d’approbation comptent ; l’acte contraceptif lui-même n’est pas reclassé comme bon."],
  bottom:["Grave reason, reluctant toleration and charitable efforts to dissuade the partner are integral to Casti Connubii §59. The passage does not declare contraception good or resolve every case of material cooperation.","La raison grave, la tolérance à regret et le devoir charitable de détourner l'autre sont constitutifs de Casti Connubii (§59). Ce passage ne rend pas la contraception bonne et ne règle pas tous les cas de coopération matérielle."],
},
"CSE071":{
  opposition:["Margaret Farley holds that the justice of masturbation should be judged largely by its effects on a person's wellbeing and freedom rather than by an intrinsic moral prohibition (Just Love, p.236, quoted in the CDF's 2012 Notification). If no one else is harmed, why should the act itself be considered gravely disordered?","Margaret Farley estime que la justice morale de la masturbation doit être appréciée surtout selon ses effets sur le bien-être et la liberté de la personne plutôt qu'en vertu d'une interdiction intrinsèque (Just Love, p.236, cité dans la Notification de la CDF de 2012). Si personne d'autre n'en subit de préjudice, pourquoi l'acte lui-même serait-il jugé gravement désordonné ?"],
  appeal:["Masturbation lacks some additional wrongs found in adultery, coercion or exploitation.","La masturbation ne comporte pas certains maux supplémentaires de l’adultère, de la contrainte ou de l’exploitation."],
  concession:["Its object differs from adultery, coercion or exploitation. An act's objective moral gravity must also be distinguished from the person's culpability: immaturity, anxiety, acquired habit or psychological factors may reduce deliberation. Neither automatic mortal guilt nor automatic absence of serious responsibility follows.","Son objet diffère de l’adultère, de la contrainte ou de l’exploitation. Il faut distinguer la gravité morale objective de la culpabilité personnelle : immaturité, angoisse, habitude acquise ou facteurs psychologiques peuvent diminuer le consentement réfléchi. Il ne s’ensuit ni culpabilité mortelle automatique ni absence systématique de responsabilité grave."],
  breakpoint:["The absence of an injured third party does not make an act morally neutral. Catholic sexual ethics also evaluates the use of the sexual faculty itself and whether sexual pleasure is integrated into conjugal self-giving.","L’absence d’une tierce victime ne rend pas un acte moralement neutre. La morale sexuelle catholique évalue aussi l’usage même de la faculté sexuelle et demande si le plaisir sexuel est intégré au don conjugal."],
  catholicCase:["Masturbation deliberately seeks sexual release outside that conjugal context. The judgment concerns the act’s object; responsibility in a particular occurrence is a separate question.","La masturbation recherche délibérément la décharge sexuelle hors de ce contexte conjugal. Le jugement porte sur l’objet de l’acte ; la responsabilité dans une occurrence particulière est une question distincte."],
  counter:["Why must sexual pleasure always be integrated into marriage? Pleasure in eating is not limited to a particular relationship, so why should sexuality differ?","Pourquoi le plaisir sexuel devrait-il toujours s'inscrire dans le mariage ? Le plaisir de manger n'est pas réservé à une relation particulière ; pourquoi la sexualité serait-elle différente ?"],
  response:["Sexual pleasure belongs to a faculty whose human meaning is relational and generative in a way nutrition is not. The substantive disagreement is therefore whether sexuality has that objective relational and generative meaning.","Le plaisir sexuel appartient à une faculté dont la signification humaine est relationnelle et générative d’une manière que la nutrition ne l’est pas. Le désaccord de fond porte donc sur la question de savoir si la sexualité possède cette signification objective, relationnelle et générative."],
  bottom:["The Church judges deliberate masturbation objectively disordered, while Persona Humana §9 expressly requires individual assessment of freedom and habits. Frequency alone neither proves that the act is good nor measures a person's guilt.","L’Église juge la masturbation délibérée objectivement désordonnée, tout en exigeant, selon Persona Humana (§9), d’évaluer concrètement liberté et habitudes. La fréquence ne prouve ni la bonté de l’acte ni la culpabilité d’une personne."]
},
"CSE074":{
  opposition:["If adults freely consent to produce and view pornography, and coercion and harmful depictions are guarded against, why should the activity itself be wrong? Could the concern be exploitation and degrading use rather than every erotic depiction?","Si des adultes consentent librement à produire et regarder de la pornographie, et que la contrainte ainsi que les représentations nuisibles sont combattues, pourquoi l’activité elle-même serait-elle mauvaise ? Le problème ne serait-il pas plutôt l’exploitation et l’usage dégradant que toute représentation érotique ?"],
  appeal:["Respect for consent and freedom from exploitation are genuine moral concerns. They matter when analyzing pornography, but neither consent nor an unverified assumption about production conditions decides the objective Catholic moral question by itself.","Le respect du consentement et l'absence d'exploitation sont de véritables exigences morales. Elles comptent dans l'analyse de la pornographie, mais ni le consentement ni des suppositions non vérifiées sur les conditions de production ne résolvent à eux seuls la question morale objective en doctrine catholique."],
  concession:["Consent removes one important possible wrong. Non-consensual or trafficked pornography is worse precisely because additional injustices are present.","Le consentement supprime un mal possible important. La pornographie non consentie ou issue de la traite est pire précisément parce que des injustices supplémentaires sont présentes."],
  breakpoint:["The inference from “consensual production” to “morally good use” does not follow. Pornography is also chosen as sexual spectacle for third-party arousal.","L’inférence de « production consentie » à « usage moralement bon » ne suit pas. La pornographie est aussi choisie comme spectacle sexuel destiné à l’excitation de tiers."],
  catholicCase:["Catholic teaching objects not only to coercion but to deliberate lust, exposure of sexual intimacy and treatment of persons or images as objects of sexual consumption.","L’enseignement catholique objecte non seulement à la contrainte mais aussi à la convoitise délibérée, à l’exposition de l’intimité sexuelle et au traitement des personnes ou images comme objets de consommation sexuelle."],
  counter:["What if the performers themselves enjoy exhibition and feel no degradation?","Et si les interprètes aiment eux-mêmes s’exhiber et ne se sentent pas dégradés ?"],
  response:["Subjective satisfaction does not settle the moral object. The question remains whether intentionally displaying sexual acts for others’ arousal respects the good of sexuality and personal dignity.","La satisfaction subjective ne tranche pas l’objet moral. La question demeure de savoir si l’exposition intentionnelle d’actes sexuels pour exciter autrui respecte le bien de la sexualité et la dignité personnelle."],
  bottom:["Consent matters greatly, but it does not transform sexual exhibition for consumption into a morally neutral act.","Le consentement compte beaucoup, mais il ne transforme pas l’exposition sexuelle destinée à la consommation en acte moralement neutre."]
},
"CSE076":{
  opposition:["The Catechism §2354 defines pornography by displaying real or simulated sexual acts to third parties. Private material created exclusively by spouses poses a different question: does recording intimacy remain prudent and respectful if it is never shared?","Le Catéchisme (§2354) définit la pornographie par l'exposition à des tiers d'actes sexuels réels ou simulés. Du matériel créé exclusivement par les époux pose une autre question : enregistrer leur intimité demeure-t-il prudent et respectueux sans aucune diffusion ?"],
  appeal:["The case is genuinely different from third-party pornography because no outside performer is being consumed and the sexual relationship itself is legitimate.","Le cas est réellement différent de la pornographie impliquant des tiers parce qu’aucun interprète extérieur n’est consommé et que la relation sexuelle elle-même est légitime."],
  concession:["Private material kept between spouses is not automatically identical to the third-party exhibition defined as pornography in Catechism §2354. That paragraph alone does not classify every form of private spousal recording; the object, intent, consent and protection of privacy still need scrutiny.","Des images privées conservées entre époux ne sont pas automatiquement identiques à l'exhibition devant des tiers que décrit le Catéchisme (§2354) à propos de la pornographie. Ce paragraphe ne classe pas à lui seul toutes les formes d'enregistrement intime privé : l'objet de l'acte, l'intention, le consentement et la protection de la vie privée demandent encore un examen."],
  breakpoint:["The opposite error is assuming marital legitimacy makes every medium prudent or morally harmless.","L’erreur inverse serait de supposer que la légitimité matrimoniale rend tout média prudent ou moralement inoffensif."],
  catholicCase:["The analysis should ask whether the material remains integrated into marital intimacy, whether it objectifies the spouse, and whether creating a permanent, copyable sexual image exposes the spouse to serious privacy risks.","L’analyse doit demander si le matériel demeure intégré à l’intimité conjugale, s’il objectifie le conjoint et si la création d’une image sexuelle permanente et copiable expose le conjoint à de graves risques pour la vie privée."],
  counter:["If both spouses understand the risks and still consent, why should prudence become a moral issue?","Si les deux époux comprennent les risques et consentent quand même, pourquoi la prudence deviendrait-elle une question morale ?"],
  response:["Because knowingly creating a serious and unnecessary risk to a spouse’s dignity or privacy can itself be imprudent. Consent does not eliminate every duty of care.","Parce que créer sciemment un risque sérieux et inutile pour la dignité ou la vie privée du conjoint peut être imprudent. Le consentement n’élimine pas tout devoir de prudence."],
  bottom:["Displaying sexual acts to third parties falls under the clear prohibition of pornography. Private spousal images require distinct prudential judgment about chastity, dignity and privacy; the definition in §2354 does not itself decide every private digital practice.","L'exposition d'actes sexuels à des tiers relève de l'interdiction claire de la pornographie. Les images privées entre époux exigent un jugement prudentiel distinct sur la chasteté, la dignité et l'intimité ; la définition du §2354 ne tranche pas chaque pratique numérique privée."]
},
"CSE083":{
  opposition:["Margaret Farley argues that same-sex relationships and sexual activity may be evaluated by the same relational criteria as heterosexual ones (Just Love, p. 295, quoted in the CDF's 2012 Notification). If mutual love, fidelity and justice matter, why exclude a faithful same-sex couple?","Margaret Farley soutient que les relations et actes sexuels entre personnes de même sexe peuvent être jugés selon les mêmes critères relationnels que les autres (Just Love, p. 295, cité dans la Notification de la CDF de 2012). Si amour, fidélité et justice comptent, pourquoi exclure un couple fidèle de même sexe ?"],
  appeal:["Affection, loyalty, sacrifice and other relational goods can be genuinely present and should not be denied or mocked.","L’affection, la loyauté, le sacrifice et d’autres biens relationnels peuvent être réellement présents et ne doivent être ni niés ni ridiculisés."],
  concession:["Affection, loyalty and self-sacrifice are real goods wherever they occur. Fidelity makes a relationship morally different from promiscuity.","L’affection, la loyauté et le sacrifice de soi sont de vrais biens partout où ils se trouvent. La fidélité rend une relation moralement différente de la promiscuité."],
  breakpoint:["The disputed premise is that these goods exhaust the moral meaning of sexual acts. Catholicism says the bodily form of the act and its relation to marriage and generation also matter.","La prémisse disputée est que ces biens épuisent le sens moral des actes sexuels. Le catholicisme affirme que la forme corporelle de l’acte et son rapport au mariage et à la génération comptent aussi."],
  catholicCase:["Persona Humana §8 distinguishes the objective judgment on sexual acts from a person's culpability, which must be assessed prudently. The paragraph also reflects historical hypotheses about the causes and permanence of same-sex attraction; those are not established as present-day clinical findings. The Catholic doctrinal argument rests on its understanding of conjugal acts, not on treating an individual's orientation as a psychiatric diagnosis or denying genuine affection.","Persona Humana (§8) distingue le jugement objectif sur les actes sexuels de la culpabilité d'une personne, qui exige une appréciation prudente. Ce paragraphe reprend aussi des hypothèses historiques sur les causes et la permanence de l'attirance pour le même sexe ; elles ne doivent pas être présentées comme des connaissances cliniques actuelles. L'argument doctrinal catholique repose sur sa conception des actes conjugaux, non sur un diagnostic psychiatrique de l'orientation individuelle ni sur la négation d'une affection authentique."],
  counter:["Isn’t that just privileging biology over love?","Cela ne revient-il pas à privilégier la biologie sur l’amour ?"],
  response:["Affection, loyalty and sacrifice can be genuine goods, but they do not alone determine the moral character of a sexual act. Catholic theology distinguishes the chosen object, the person's responsibility and the dignity owed to every person.","L'affection, la loyauté et le sacrifice peuvent être des biens réels, mais ils ne déterminent pas à eux seuls le caractère moral d'un acte sexuel. La théologie catholique distingue l'objet choisi, la responsabilité personnelle et la dignité due à chacun."],
  bottom:["The Church need not deny the relationship’s genuine goods to maintain that those goods do not by themselves make every sexual expression morally ordered.","L’Église n’a pas besoin de nier les biens réels de la relation pour maintenir que ces biens ne rendent pas, à eux seuls, toute expression sexuelle moralement ordonnée."]
},
"CSE084":{
  opposition:["Infertile heterosexual spouses can marry although they cannot conceive. If successful procreation is not required for marriage, why must the man–woman distinction remain essential to its definition?","Des époux hétérosexuels stériles peuvent se marier alors qu'ils ne peuvent concevoir. Si une procréation effective n'est pas requise, pourquoi la différence homme–femme demeure-t-elle essentielle à la définition du mariage ?"],
  appeal:["Actual conception is not required for every marriage or every conjugal act.","La conception effective n’est pas requise pour chaque mariage ni pour chaque acte conjugal."],
  concession:["A marriage may be permanently infertile and remain fully valid.","Un mariage peut être définitivement stérile et rester pleinement valide."],
  breakpoint:["Inability to achieve an outcome is not the same as absence of the type of bodily union naturally ordered to that outcome.","L’incapacité à atteindre un résultat n’est pas la même chose que l’absence du type d’union corporelle naturellement ordonné à ce résultat."],
  catholicCase:["Canon 1084 §3 states that sterility neither prevents nor invalidates marriage, expressly without prejudice to canon 1098 on deceit used to obtain consent; §1 separately treats antecedent and perpetual incapacity for intercourse, while §2 protects marriage when that impediment is doubtful. Those distinct juridical rules are not a fertility test and do not by themselves establish the whole philosophical account of male–female conjugal union.","Le canon 1084 §3 précise que la stérilité n'empêche ni n'invalide le mariage, sous réserve du canon 1098 sur le dol destiné à obtenir le consentement ; le §1 traite séparément de l'impuissance antécédente et perpétuelle, tandis que le §2 protège le mariage lorsque cet empêchement est douteux. Ces règles juridiques distinctes ne constituent pas un examen de fécondité et ne suffisent pas, à elles seules, à établir toute la conception philosophique de l'union conjugale homme-femme."],
  counter:["But why should “type of act” matter if the result is known to be impossible?","Pourquoi le « type d’acte » devrait-il compter si l’on sait que le résultat est impossible ?"],
  response:["Because moral meaning is not determined solely by outcome. We routinely distinguish acts by what they are, even when circumstances prevent their ordinary effects. Catholic marriage applies the same action-theory distinction here.","Parce que la signification morale n’est pas déterminée uniquement par le résultat. Nous distinguons couramment les actes selon ce qu’ils sont, même lorsque les circonstances empêchent leurs effets ordinaires. Le mariage catholique applique ici la même distinction de théorie de l’action."],
  bottom:["Sterility is failure of an outcome within a generative kind of union; it is not the absence of that kind of union.","La stérilité est l’échec d’un résultat au sein d’un type d’union générative ; elle n’est pas l’absence de ce type d’union."]
},
"CSE087":{
  opposition:["The American Psychological Association condemns stigma, discrimination and violence against sexual minorities and reports that such prejudice can harm mental health. If religious language is used to stigmatize gay people, is the Church sufficiently confronting the consequences of that language?","L'American Psychological Association condamne la stigmatisation, la discrimination et les violences contre les minorités sexuelles et relève leurs conséquences possibles sur la santé psychique. Si un langage religieux sert à stigmatiser des personnes homosexuelles, l'Église en affronte-t-elle suffisamment les conséquences ?"],
  appeal:["The concern is serious because moral language can be weaponized, and people have suffered contempt, rejection and violence under religious pretexts.","La préoccupation est sérieuse parce que le langage moral peut être utilisé comme arme, et des personnes ont subi mépris, rejet et violence sous des prétextes religieux."],
  concession:["Cruelty, violence and unjust discrimination are wrong. The 1986 CDF letter explicitly rejects violent malice and insists on personal dignity.","La cruauté, la violence et la discrimination injuste sont mauvaises. La lettre de 1986 de la CDF rejette explicitement la malveillance violente et insiste sur la dignité personnelle."],
  breakpoint:["The further inference is that a moral judgment about an act is therefore itself hatred. That would make many forms of moral disagreement impossible in principle.","L’inférence supplémentaire est qu’un jugement moral sur un acte serait donc lui-même haineux. Cela rendrait en principe impossible de nombreuses formes de désaccord moral."],
  catholicCase:["The 1986 CDF letter §10 condemns hostile speech, violence and attacks on dignity; Dignitas Infinita §55 again condemns unjust discrimination, imprisonment, torture and killing because of sexual orientation. These obligations coexist with the Church's sexual ethics. Neither moral disagreement nor a claim about conscience excuses mistreatment.","La lettre de la CDF de 1986 (§10) condamne les propos malveillants, la violence et l'atteinte à la dignité ; Dignitas Infinita (§55) condamne aussi les discriminations injustes, l'emprisonnement, la torture et la mise à mort fondés sur l'orientation sexuelle. Ces obligations subsistent avec la morale sexuelle de l'Église. Ni le désaccord moral ni la conscience ne justifient de maltraiter autrui."],
  counter:["But in practice the distinction often feels hollow when the teaching denies recognition to a person’s relationship.","Mais en pratique la distinction paraît souvent vide lorsque l’enseignement refuse de reconnaître la relation d’une personne."],
  response:["That pastoral failure can be real and should be confronted. It does not settle the underlying moral argument. The correct test is whether the teaching can be defended without contempt and whether communities actually treat persons according to the dignity they profess.","Cet échec pastoral peut être réel et doit être affronté. Il ne tranche pas l’argument moral sous-jacent. Le bon test est de savoir si l’enseignement peut être défendu sans mépris et si les communautés traitent réellement les personnes selon la dignité qu’elles professent."],
  bottom:["Moral disagreement does not license dehumanization. Nor does the existence of stigma by itself prove the moral judgment false.","Le désaccord moral n’autorise pas la déshumanisation. L’existence de stigmatisation ne prouve pas non plus, à elle seule, que le jugement moral soit faux."]
},
"CSE088":{
  opposition:["The American Psychological Association explicitly says same-sex orientation is not a mental disorder and opposes efforts that promise to change orientation. Does a traditional moral account need to change if it once depended on assumptions that homosexuality is a psychiatric disease or that orientation is freely chosen?","L'American Psychological Association affirme expressément que l'orientation homosexuelle n'est pas un trouble mental et rejette les interventions promettant de la modifier. Une morale traditionnelle doit-elle être révisée si elle s'appuyait sur la maladie psychiatrique ou sur le choix volontaire de cette orientation ?"],
  appeal:["Scientific corrections matter. A moral argument that depends on false claims about pathology or voluntariness must be revised.","Les corrections scientifiques comptent. Un argument moral fondé sur de fausses affirmations concernant la pathologie ou le caractère volontaire doit être révisé."],
  concession:["Psychology can correct mistaken assumptions about development, choice, distress and mental health. Same-sex attraction should not be treated as personal guilt merely because it exists.","La psychologie peut corriger des présupposés erronés sur le développement, le choix, la détresse et la santé mentale. L’attirance envers le même sexe ne doit pas être traitée comme culpabilité personnelle du seul fait qu’elle existe."],
  breakpoint:["The moral judgment on sexual acts does not depend on classifying a sexual orientation as a psychiatric disease.","Le jugement moral sur les actes sexuels ne dépend pas de la classification d’une orientation sexuelle comme maladie psychiatrique."],
  catholicCase:["Sexual orientation is not, simply as such, a psychiatric diagnosis or a personally culpable choice. The CDF's 1986 designation of an inclination as objectively disordered concerns its moral orientation toward acts, not a finding of mental illness. The Church's judgment about acts must be defended from conjugal morality rather than from a claim that orientation itself is a disease.","Une orientation sexuelle n'est pas, en tant que telle, un diagnostic psychiatrique ni un choix personnellement coupable. La qualification d'inclination objectivement désordonnée donnée par la CDF en 1986 concerne son orientation morale vers des actes, non une maladie mentale. Le jugement de l'Église sur les actes doit être défendu à partir de la morale conjugale et non en présentant l'orientation elle-même comme une maladie."],
  counter:["But if psychology shows same-sex orientation is stable and unchosen, doesn’t requiring celibacy become unreasonable?","Mais si la psychologie montre qu’une orientation homosexuelle est stable et non choisie, exiger la continence ne devient-il pas déraisonnable ?"],
  response:["An involuntary attraction does not itself entail personal guilt; its involuntary character also does not establish the morality of any chosen sexual act. Chastity is required according to one's state of life, with pastoral attention to particular circumstances and no unsupported promises of changing orientation.","Une attirance involontaire n'entraîne pas à elle seule une culpabilité personnelle ; son caractère involontaire ne détermine pas non plus la moralité d'un acte sexuel choisi. La chasteté est demandée selon l'état de vie, avec une attention pastorale aux situations particulières et sans promesses infondées de changement d'orientation."],
  bottom:["Psychology can and should correct factual errors. It does not by itself replace the moral anthropology on which the Catholic judgment rests.","La psychologie peut et doit corriger les erreurs factuelles. Elle ne remplace pas à elle seule l’anthropologie morale sur laquelle repose le jugement catholique."]
},
"CSE089":{
  opposition:["Margaret Farley argued that legal recognition of civil unions and same-sex marriage could help combat stigma and provide comparable social recognition (Just Love, p. 293, quoted in the CDF's 2012 Notification). Why should a civil state with citizens of different religions reject that equal-recognition case?","Margaret Farley défendait la reconnaissance juridique des unions civiles et du mariage entre personnes de même sexe pour lutter contre la stigmatisation et favoriser une reconnaissance sociale comparable (Just Love, p. 293, cité dans la Notification de la CDF de 2012). Pourquoi un État composé de citoyens de religions diverses devrait-il écarter cet argument d'égalité ?"],
  appeal:["Private religious rules and the coercive power of civil law are distinct; legal restrictions require reasons appropriate to the common good and public justice.","Les règles religieuses privées et le pouvoir coercitif de la loi civile sont distincts ; les restrictions juridiques exigent des raisons propres au bien commun et à la justice publique."],
  concession:["A civil-law argument cannot simply be “the Church forbids it.” It must explain what public institution marriage is and why its definition matters.","Un argument de droit civil ne peut se réduire à « l’Église l’interdit ». Il doit expliquer ce qu’est l’institution publique du mariage et pourquoi sa définition compte."],
  breakpoint:["The dispute is not whether one same-sex wedding directly damages one heterosexual marriage. It is whether marriage law merely registers private affection or publicly defines an institution connected to sexual difference, family and generation.","Le désaccord ne porte pas sur le fait qu’un mariage de même sexe endommagerait directement un mariage hétérosexuel. Il porte sur la question de savoir si le droit du mariage enregistre seulement une affection privée ou définit publiquement une institution liée à la différence sexuelle, à la famille et à la génération."],
  catholicCase:["The CDF’s 2003 reasoning is institutional: changing the legal definition changes what the state recognizes as marriage. Its force therefore depends on the public significance attributed to sexual difference and parenthood.","Le raisonnement de la CDF en 2003 est institutionnel : modifier la définition juridique change ce que l’État reconnaît comme mariage. Sa force dépend donc de la signification publique attribuée à la différence sexuelle et à la parentalité."],
  counter:["But the state already recognizes infertile and childless marriages, so procreation cannot be the public purpose.","Mais l’État reconnaît déjà les mariages stériles et sans enfants ; la procréation ne peut donc être le but public."],
  response:["The CDF's 2003 argument is that civil law shapes the public definition of marriage, not simply that the Church forbids a private relationship. Section 7 also makes claims about child development: those historical empirical assertions must be evaluated on their own evidence, not presented as scientific conclusions established by magisterial authority. Farley's competing arguments about public recognition and non-discrimination require a distinct legal and moral reply.","Pour la CDF (2003), le droit civil façonne la définition publique du mariage ; l'argument ne se réduit pas à l'interdiction ecclésiale d'une relation privée. Le §7 avance aussi des affirmations sur le développement des enfants : ces assertions empiriques historiques doivent être évaluées d'après leurs preuves propres, et non présentées comme des conclusions scientifiques établies par l'autorité magistérielle. Les arguments contraires de Farley sur la reconnaissance publique et la non-discrimination demandent une réponse juridique et morale distincte."],
  bottom:["The Catholic civil argument is about the public definition of marriage, not the claim that a same-sex couple directly harms a particular other marriage.","L’argument civil catholique porte sur la définition publique du mariage, non sur l’idée qu’un couple de même sexe nuirait directement à un mariage particulier."]
},
"CSE093":{
  opposition:["The APA distinguishes biological sex from culturally variable gender roles and recognizes atypical development of sex characteristics. If these concepts differ, which parts of the traditional account describe bodily reality and which merely describe social expectations?","L'APA distingue le sexe biologique des rôles de genre variables selon les cultures et reconnaît des développements atypiques des caractères sexuels. Si ces notions diffèrent, qu'est-ce qui, dans la tradition, décrit le corps et qu'est-ce qui n'est qu'attente sociale ?"],
  appeal:["Many expectations attached to men and women are cultural rather than biologically necessary.","De nombreuses attentes attachées aux hommes et aux femmes sont culturelles plutôt que biologiquement nécessaires."],
  concession:["Gender roles, dress, occupations and social expectations can vary and can contain unjust stereotypes.","Les rôles de genre, les vêtements, les professions et les attentes sociales peuvent varier et contenir des stéréotypes injustes."],
  breakpoint:["Clothing, temperament and occupations do not determine whether someone is male or female. The moral significance of embodied reproductive differences must be distinguished from historically contingent social expectations. Neither cultural variation nor atypical sex development by itself settles a normative judgment.","Les vêtements, le tempérament et les professions ne déterminent pas le sexe d’une personne. La portée morale des différences corporelles liées à la reproduction doit être distinguée des attentes sociales historiquement contingentes. Ni la diversité culturelle ni un développement sexuel atypique ne tranchent à eux seuls un jugement normatif."],
  catholicCase:["Dignitas Infinita §59 distinguishes biological sex from the sociocultural role of sex while refusing their complete separation. This does not elevate every custom concerning clothing, occupation or temperament into permanent doctrine. Persons with atypical sex development deserve accurate clinical assessment and individualized care, not classification by stereotype.","Dignitas Infinita (§59) distingue le sexe biologique du rôle socioculturel du sexe sans les séparer entièrement. Ce texte n'élève pas toute coutume sur le vêtement, le métier ou le tempérament au rang de doctrine permanente. Les personnes présentant un développement sexuel atypique méritent une évaluation clinique rigoureuse et des soins individualisés, non une classification par stéréotypes."],
  counter:["But biology itself contains atypical development and ambiguity.","Mais la biologie elle-même comporte des développements atypiques et des ambiguïtés."],
  response:["Variations in sex development complicate some classifications and call for careful individualized medical assessment. They do not establish that bodily sex generally is created by social agreement. Nor should any person with atypical sex characteristics be reduced to a diagnosis or used merely as an example in an ideological dispute.","Les variations du développement sexuel peuvent compliquer certaines classifications et demandent une évaluation médicale individualisée et rigoureuse. Elles ne démontrent pas que le sexe corporel serait généralement créé par convention sociale. Il ne faut pas davantage réduire une personne présentant des caractéristiques sexuelles atypiques à un diagnostic ou en faire un simple exemple dans une querelle idéologique."],
  bottom:["Sexual difference belongs to embodied human life, while many customary gender roles can vary. Dignitas Infinita §59 distinguishes the two without severing them.","La différence sexuelle appartient à la vie corporelle de l'être humain, tandis que de nombreux rôles socioculturels peuvent varier. Dignitas Infinita (§59) les distingue sans les séparer."],
},
"CSE094":{
  opposition:["The American Psychological Association's February 2024 policy supports access to affirming, evidence-based healthcare for transgender and gender-diverse people and challenges stigmatizing misinformation. How should this clinical-policy position be weighed against Catholic anthropology of the sexed body?","La politique de l'American Psychological Association de février 2024 soutient l'accès à des soins affirmatifs fondés sur les données probantes pour les personnes transgenres et de diverses identités de genre, et critique la désinformation stigmatisante. Comment apprécier cette politique clinique à la lumière de l'anthropologie catholique du corps sexué ?"],
  appeal:["The suffering is real and should never be dismissed as mere ideology. Clinical outcomes matter.","La souffrance est réelle et ne doit jamais être rejetée comme simple idéologie. Les résultats cliniques comptent."],
  concession:["People experiencing serious distress deserve respect, competent care and protection from ridicule or neglect.","Les personnes éprouvant une détresse grave méritent respect, soins compétents et protection contre la moquerie ou l’abandon."],
  breakpoint:["Real distress requires care, but neither distress nor a professional association's policy by itself resolves the moral object of every intervention. Clinical questions about effectiveness and risk differ from the theological argument that body and person form a unity.","La souffrance réelle demande des soins, mais ni la souffrance ni la politique d'une association professionnelle ne déterminent à elles seules l'objet moral de chaque intervention. Les questions cliniques d'efficacité et de risque se distinguent de l'argument théologique sur l'unité du corps et de la personne."],
  catholicCase:["Catholic anthropology treats the body as part of the person, not as raw material external to identity. That makes bodily sex morally relevant while leaving empirical medicine responsible for evaluating distress, risks and outcomes.","L’anthropologie catholique considère le corps comme partie de la personne, non comme une matière brute extérieure à l’identité. Le sexe corporel est donc moralement pertinent, tandis que la médecine empirique reste chargée d’évaluer la détresse, les risques et les résultats."],
  counter:["But if an intervention demonstrably reduces suffering, why should anthropology override clinical benefit?","Mais si une intervention réduit manifestement la souffrance, pourquoi l’anthropologie devrait-elle l’emporter sur le bénéfice clinique ?"],
  response:["Relieving genuine distress matters, as do informed consent, clinical effectiveness, contraindications, uncertainty and follow-up. Dignitas Infinita §60 makes a distinct moral argument about the unity of body and person. Neither citing 'compassion' nor invoking a medical society settles every treatment choice; serious cases call for skilled clinical and, if desired, competent Catholic ethical care without humiliation or neglect.","Soulager une souffrance réelle importe, de même que le consentement éclairé, l'efficacité clinique, les contre-indications, l'incertitude et le suivi. Dignitas Infinita (§60) avance un argument moral distinct sur l'unité du corps et de la personne. Ni la seule « compassion » ni l'autorité d'une société médicale ne tranchent chaque traitement ; les situations difficiles demandent des soins compétents et, si souhaité, un conseil moral catholique, sans humiliation ni abandon."],
  bottom:["Compassion requires serious care for distress. It does not by itself settle the disputed anthropology or the morality of every proposed intervention.","La compassion exige une prise en charge sérieuse de la détresse. Elle ne tranche pas à elle seule l’anthropologie disputée ni la moralité de toute intervention proposée."]
},
"CSE095":{
  opposition:["The American Psychological Association's 2024 policy links gender-related rejection and discrimination to psychological harm and calls for respectful, individualized care. In ordinary conversation, could refusing a person's requested form of address deepen distress even when the speaker disputes the underlying view of gender identity?","La politique de l'American Psychological Association de 2024 relie rejet et discrimination liés au genre à des dommages psychologiques et demande des soins respectueux et individualisés. Dans la conversation ordinaire, refuser la manière dont une personne demande à être appelée pourrait-il accroître sa souffrance, même si l'on conteste sa conception de l'identité de genre ?"],
  appeal:["Language can wound, and gratuitous confrontation or humiliation is contrary to charity.","Le langage peut blesser, et la confrontation gratuite ou l’humiliation sont contraires à la charité."],
  concession:["Catholics should avoid mockery, cruelty and reducing a person to a disputed identity claim. Context and relationship matter greatly in how one speaks.","Les catholiques doivent éviter la moquerie, la cruauté et la réduction d’une personne à une revendication identitaire disputée. Le contexte et la relation comptent beaucoup dans la manière de parler."],
  breakpoint:["The disputed inference is that respect requires intellectual assent to the underlying claim about identity and bodily sex.","L’inférence disputée est que le respect exige un assentiment intellectuel à l’affirmation sous-jacente sur l’identité et le sexe corporel."],
  catholicCase:["Catholic ethics distinguishes respect for the person from agreement with every proposition the person holds about himself or herself. Charity can require tact without requiring falsehood.","La morale catholique distingue le respect de la personne de l’accord avec toute proposition qu’elle tient sur elle-même. La charité peut exiger du tact sans exiger le mensonge."],
  counter:["But refusing affirmation may have foreseeable psychological costs.","Mais refuser l’affirmation peut avoir des coûts psychologiques prévisibles."],
  response:["Truthfulness does not require gratuitous confrontation, revealing private medical information or refusing ordinary courtesy. Particular words or forms of address must be judged in context, according to what they assert and how they affect the person. Dignitas Infinita §§55–60 does not prescribe a universal pronoun rule.","La vérité n'oblige ni à la confrontation gratuite, ni à révéler des informations médicales privées, ni à refuser la courtoisie ordinaire. Les mots et les formes d'adresse doivent être appréciés selon leur sens et la situation de la personne. Dignitas Infinita (§§55–60) ne prescrit aucune règle universelle concernant les pronoms."],
  bottom:["Respect never requires contempt; neither does it necessarily require assent. The challenge is truthful charity, not maximal confrontation.","Le respect n’exige jamais le mépris ; il n’exige pas nécessairement non plus l’assentiment. Le défi est une charité véridique, non la confrontation maximale."]
},
"CSE096":{
  opposition:["WPATH's Standards of Care 8 recommends individualized assessment, informed decision-making and clinical options intended to relieve persistent gender-related distress. Where a patient reports serious suffering and potential treatment benefits, what evidence and moral reasons justify withholding a particular intervention?","Les Standards of Care 8 de WPATH recommandent une évaluation individualisée, une décision éclairée et des traitements destinés à soulager une souffrance persistante liée au genre. Lorsqu'un patient éprouve une détresse grave et qu'un traitement pourrait lui apporter un bénéfice, quelles preuves et quelles raisons morales justifient le refus de cette intervention ?"],
  appeal:["Adult autonomy is important, and not every medical intervention must restore a diseased organ in a narrow sense.","L’autonomie adulte est importante, et toute intervention médicale ne doit pas nécessairement restaurer un organe malade au sens étroit."],
  concession:["Medical ethics legitimately considers suffering and quality of life, not only survival.","L’éthique médicale considère légitimement la souffrance et la qualité de vie, non seulement la survie."],
  breakpoint:["Autonomy does not by itself make every requested intervention therapeutic. Medicine still asks what counts as health, what harms are imposed and whether the intervention treats a pathology or alters healthy sexual characteristics to conform to an asserted identity.","L’autonomie ne rend pas à elle seule thérapeutique toute intervention demandée. La médecine demande encore ce qui compte comme santé, quels dommages sont imposés et si l’intervention traite une pathologie ou modifie des caractères sexuels sains pour les conformer à une identité affirmée."],
  catholicCase:["Dignitas Infinita §60 teaches that interventions intended to change sex, as a rule, risk threatening the dignity of the sexed body. It expressly distinguishes medically indicated treatment of genital abnormalities apparent at birth or developing later. Assessment of a particular case also requires accurate diagnosis, medical risk evaluation and attention to the intervention's intended object.","Dignitas Infinita (§60) enseigne que les interventions visant à changer de sexe risquent, en règle générale, de menacer la dignité du corps sexué. Le texte distingue expressément le traitement médical des anomalies génitales manifestes dès la naissance ou apparues plus tard. Le discernement d'un cas exige également un diagnostic rigoureux, l'évaluation des risques et l'examen de l'objet de l'intervention."],
  counter:["Why privilege the original body if changing it produces a more livable life?","Pourquoi privilégier le corps d’origine si le modifier produit une vie plus vivable ?"],
  response:["Because Catholic anthropology does not treat the body as external material owned by an inner self. The body participates in personal identity. A critic must therefore challenge that anthropology rather than appeal to autonomy alone.","Parce que l’anthropologie catholique ne traite pas le corps comme une matière extérieure possédée par un moi intérieur. Le corps participe à l’identité personnelle. Le critique doit donc contester cette anthropologie plutôt que faire appel à la seule autonomie."],
  bottom:["Relief of distress and quality of life matter clinically. Dignitas Infinita §60 nevertheless states a general moral objection to sex-change interventions, while distinguishing treatment of genital abnormalities; clinical particulars still require careful assessment.","Soulagement de la souffrance et qualité de vie comptent en médecine. Dignitas Infinita (§60) formule néanmoins une objection morale générale aux interventions de changement de sexe tout en distinguant le traitement des anomalies génitales ; les circonstances cliniques doivent encore être examinées."],
},
"CSE101":{
  opposition:["Infertility treatment seeks to help patients have children, and informed reproductive choices deserve careful counseling. Does the good of becoming parents justify IVF even when fertilization takes place outside the spouses’ own act?","Le traitement de l’infertilité cherche à aider les personnes à avoir des enfants et les décisions reproductives demandent une information attentive. Le bien de devenir parents justifie-t-il la FIV même lorsque la fécondation se produit hors de l’acte propre des époux ?"],
  appeal:["The desire for a child is good, infertility can be deeply painful and medical assistance is not wrong merely because it is technologically advanced.","Le désir d’un enfant est bon, l’infertilité peut être profondément douloureuse et l’aide médicale n’est pas mauvaise simplement parce qu’elle est technologiquement avancée."],
  concession:["Catholic teaching explicitly permits many treatments that restore fertility or assist the marital act. It does not reject technology as such.","L’enseignement catholique permet explicitement de nombreux traitements qui restaurent la fertilité ou assistent l’acte conjugal. Il ne rejette pas la technologie en tant que telle."],
  breakpoint:["The crucial distinction is between assisting the spouses’ own conjugal act and replacing it as the cause of conception.","La distinction décisive est celle entre assister l’acte conjugal propre aux époux et le remplacer comme cause de la conception."],
  catholicCase:["Donum Vitae II.B.5 rejects homologous IVF even where embryo destruction and masturbation are excluded, because conception through the laboratory replaces rather than assists the spouses' conjugal act. Dignitas Personae §§12–13 affirm fertility-restoring treatments and techniques that assist that act; §§14–16 separately address embryo destruction and the separation of procreation from conjugal self-giving. None of this diminishes the dignity of any child conceived through IVF.","Donum Vitae (II.B.5) rejette la FIV homologue même lorsque la destruction d'embryons et la masturbation sont exclues, parce que la conception en laboratoire remplace l'acte conjugal des époux au lieu de l'assister. Dignitas Personae (§§12–13) admet les traitements restaurant la fécondité et les techniques qui assistent cet acte ; les §§14–16 examinent séparément la destruction des embryons et la dissociation de la procréation d'avec le don conjugal. Rien de cela ne diminue la dignité d'un enfant conçu par FIV."],
  counter:["But why should the manner of conception matter if the child is loved and the parents are married?","Pourquoi le mode de conception devrait-il compter si l’enfant est aimé et que les parents sont mariés ?"],
  response:["The legitimate desire for a child does not make every means morally interchangeable. The Church permits technology that repairs infertility or assists the spouses' own act, but rejects producing the child through a procedure that replaces that act (Dignitas Personae §§12–16).","Le désir légitime d'un enfant ne rend pas tous les moyens moralement équivalents. L'Église admet la technique qui soigne l'infertilité ou aide l'acte des époux, mais refuse la production de l'enfant par un procédé qui remplace cet acte (Dignitas Personae, §§12–16)."],
  bottom:["IVF is not rejected out of hostility to children or medicine. The moral concerns are the substitution of technique for the conjugal act and, often, additional wrongs toward embryos.","La FIV n’est rejetée ni par hostilité envers les enfants ni envers la médecine. Les difficultés morales concernent la substitution de la technique à l’acte conjugal et, souvent, des torts supplémentaires envers les embryons."]
},
"CSE104":{
  opposition:["Surrogacy can be an act of generosity. If a woman freely carries a child for an infertile couple without exploitation or payment, why condemn her sacrifice?","La gestation pour autrui peut être un acte de générosité. Si une femme porte librement un enfant pour un couple stérile sans exploitation ni paiement, pourquoi condamner son sacrifice ?"],
  appeal:["Altruistic surrogacy avoids payment and may reduce some commercial pressures, but unpaid arrangements can still involve family pressure, power imbalances or conflict over medical decisions. Sincere compassion for an infertile family can be real without eliminating those risks.","La gestation pour autrui altruiste exclut la rémunération et peut réduire certaines pressions commerciales, mais des arrangements non rémunérés peuvent encore comporter des pressions familiales, des rapports de pouvoir inégaux ou des conflits sur les décisions médicales. Une compassion sincère envers une famille infertile peut exister sans supprimer ces risques."],
  concession:["The good intention of helping an infertile couple can be real. Payment is not the sole issue, and even a well-safeguarded unpaid arrangement requires examining the intentional separation of gestation, birth and upbringing.","La bonne intention d’aider un couple infertile peut être réelle. La rémunération n’est pas le seul enjeu et, même avec des garanties dans un arrangement bénévole, il reste à examiner la séparation intentionnelle entre gestation, naissance et éducation."],
  breakpoint:["The inference is that absence of payment removes every moral issue. Surrogacy also deliberately separates gestation from the woman who will rear the child and subjects pregnancy to an agreement that the child will be handed over.","L’inférence est que l’absence de paiement supprime tout problème moral. La gestation pour autrui sépare aussi délibérément la grossesse de la femme qui élèvera l’enfant et soumet la grossesse à un accord prévoyant la remise de l’enfant."],
  catholicCase:["Donum Vitae II.A.3 rejects surrogate motherhood regardless of payment because the procreative plan deliberately separates gestation, birth, and the obligations of maternal love and marital fidelity. The moral objection is therefore not confined to commercialization or demonstrable coercion, even when an infertile couple's desire and a carrier's generosity are sincere.","Donum Vitae (II.A.3) rejette la maternité de substitution indépendamment de toute rémunération, parce que le projet de procréation sépare volontairement la gestation, la naissance et les devoirs de l'amour maternel et de la fidélité conjugale. L'objection morale ne se limite donc pas au commerce ou à une coercition prouvée, même si le désir du couple infertile et la générosité de la femme porteuse sont sincères."],
  counter:["But adoption also separates biological and social parenthood.","Mais l’adoption sépare elle aussi parentalité biologique et sociale."],
  response:["Adoption provides a family for a child already needing one; surrogacy makes the planned separation of gestation and parental upbringing part of how a child is brought into being. The intentions can both be generous, but these are morally different chosen acts.","L'adoption accueille un enfant ayant déjà besoin d'une famille ; la maternité de substitution prévoit dès la conception la séparation entre gestation et éducation parentale. Les intentions peuvent être généreuses dans les deux cas, mais les actes librement choisis diffèrent moralement."],
  bottom:["Altruistic motive can remove commercial exploitation, but it does not remove the intentional fragmentation of gestation, motherhood and parenthood.","Un motif altruiste peut supprimer l’exploitation commerciale, mais il ne supprime pas la fragmentation intentionnelle de la gestation, de la maternité et de la parentalité."]
}
});
