export const CSE_DEBATES_POPULAR=Object.freeze({
"CSE141":{
  opposition:["The Church seems disproportionately preoccupied with sex. Catholics discuss contraception, homosexuality, pornography and premarital sex constantly while many other moral failures receive less attention.","L’Église paraît disproportionnellement préoccupée par la sexualité. Les catholiques parlent sans cesse de contraception, d’homosexualité, de pornographie et de relations avant le mariage tandis que beaucoup d’autres fautes morales reçoivent moins d’attention."],
  appeal:["The criticism is sometimes deserved. A distorted religious culture can reduce moral formation to sexual prohibitions and neglect justice, charity, truthfulness, greed or cruelty.","La critique est parfois méritée. Une culture religieuse déformée peut réduire la formation morale aux interdictions sexuelles et négliger justice, charité, véracité, avidité ou cruauté."],
  concession:["Catholic morality is much larger than sexual morality, and presenting Christianity as if sexual sins were its only serious sins is bad formation.","La morale catholique est beaucoup plus vaste que la morale sexuelle, et présenter le christianisme comme si les péchés sexuels étaient ses seuls péchés graves constitue une mauvaise formation."],
  breakpoint:["But disproportionate discussion does not show that the underlying sexual norms are false. Public controversy itself can cause certain teachings to receive far more attention than their proportion in the whole moral life.","Mais une discussion disproportionnée ne montre pas que les normes sexuelles sous-jacentes soient fausses. La controverse publique elle-même peut faire recevoir à certains enseignements beaucoup plus d’attention que leur proportion dans l’ensemble de la vie morale."],
  catholicCase:["Chastity is one virtue among many. Sexuality matters because it touches marriage, fidelity, children, bodily integrity and powerful appetites, but it belongs within the wider Christian life of worship, justice, mercy and charity.","La chasteté est une vertu parmi beaucoup d’autres. La sexualité compte parce qu’elle touche au mariage, à la fidélité, aux enfants, à l’intégrité corporelle et à des appétits puissants, mais elle appartient à la vie chrétienne plus large de culte, justice, miséricorde et charité."],
  counter:["Why do some Christian communities seem to emphasize sexual sins more than injustice, dishonesty, neglect of the poor or failures of charity?","Pourquoi certaines communautés chrétiennes semblent-elles insister davantage sur les péchés sexuels que sur l’injustice, la malhonnêteté, l’abandon des pauvres ou les manquements à la charité ?"],
  response:["Where that imbalance occurs, it should be corrected. The Gospel joins purity of heart to truthfulness, justice, mercy and love of neighbour; neither social sins nor sexual sins may be excused by attention to the other. The gravity of each act must be taught in its proper place within the whole moral life.","Lorsqu’un tel déséquilibre existe, il faut le corriger. L’Évangile unit la pureté du cœur à la véracité, à la justice, à la miséricorde et à l’amour du prochain ; ni les péchés sociaux ni les péchés sexuels ne peuvent être excusés au prétexte qu’on insiste sur les autres. Il faut enseigner la gravité de chaque acte à sa juste place dans l’ensemble de la vie morale."],
  bottom:["The Church should not be obsessed with sex. But misuse or overemphasis of a teaching does not establish that the teaching itself is false.","L’Église ne devrait pas être obsédée par la sexualité. Mais un mauvais usage ou une suraccentuation d’un enseignement ne prouve pas que cet enseignement soit faux."]
},
"CSE142":{
  opposition:["Traditional sexual morality may have been possible in a protected religious culture, but modern dating, digital pornography, delayed marriage and pervasive sexualization make lifelong chastity unrealistic.","La morale sexuelle traditionnelle a peut-être été possible dans une culture religieuse protégée, mais les rencontres modernes, la pornographie numérique, le mariage tardif et la sexualisation omniprésente rendent la chasteté irréaliste."],
  appeal:["The environment has changed in ways that genuinely increase exposure, temptation and the duration of unmarried adult life.","L’environnement a changé d’une manière qui augmente réellement l’exposition, la tentation et la durée de la vie adulte non mariée."],
  concession:["Chastity can be very difficult, and moral advice that ignores technology, loneliness, habit and delayed marriage can be practically useless.","La chasteté peut être très difficile, et des conseils moraux qui ignorent technologie, solitude, habitudes et mariage tardif peuvent être pratiquement inutiles."],
  breakpoint:["Difficulty does not establish impossibility or falsity. The further premise—that strong sexual desire must be expressed in order for a person to live a healthy human life—also requires proof.","La difficulté ne prouve ni impossibilité ni fausseté. La prémisse supplémentaire — selon laquelle un désir sexuel intense doit être exprimé pour qu’une personne puisse vivre sainement — doit elle aussi être démontrée."],
  catholicCase:["Catholic virtue ethics assumes appetites can be trained rather than merely obeyed. Practically, that means environment, routines, friendships, prayer, sacramental life, digital barriers and avoidance of predictable occasions—not a fantasy of effortless willpower.","L’éthique catholique des vertus suppose que les appétits peuvent être éduqués plutôt que simplement obéis. En pratique, cela signifie environnement, habitudes, amitiés, prière, vie sacramentelle, barrières numériques et évitement des occasions prévisibles — non un fantasme de volonté sans effort."],
  counter:["But repeated failure seems to prove the standard is beyond many people.","Mais les échecs répétés semblent prouver que la norme dépasse beaucoup de personnes."],
  response:["Repeated failure proves difficulty and may reveal habit or reduced freedom; it does not by itself show that the good sought is unreal. Moral formation should respond with realistic means, gradual growth and mercy without redefining failure as success.","Les échecs répétés prouvent la difficulté et peuvent révéler une habitude ou une liberté réduite ; ils ne montrent pas à eux seuls que le bien recherché soit irréel. La formation morale doit répondre par des moyens réalistes, une croissance graduelle et la miséricorde sans redéfinir l’échec comme réussite."],
  bottom:["Modern conditions can make chastity harder. Harder is not the same as impossible or inhuman.","Les conditions modernes peuvent rendre la chasteté plus difficile. Plus difficile ne signifie pas impossible ni inhumain."]
},
"CSE143":{
  opposition:["Some studies associate restrictive religious sexual messages with sexual shame, and people report secrecy or self-reproach after such experiences. Should these harms prompt a reassessment of how chastity is taught, and perhaps of the rules themselves?","Certaines études associent des messages religieux restrictifs sur la sexualité à la honte sexuelle, et des personnes rapportent du secret ou des reproches envers elles-mêmes. Ces dommages devraient-ils conduire à revoir la manière d’enseigner la chasteté, voire les normes elles-mêmes ?"],
  appeal:["Religious shame can be real, and humiliating or obsessive instruction can cause genuine harm.","La honte religieuse peut être réelle, et un enseignement humiliant ou obsessionnel peut causer un véritable dommage."],
  concession:["Bad formation should be criticized. A person should never be taught that temptation, involuntary attraction or past sin makes him or her worthless.","Une mauvaise formation doit être critiquée. On ne doit jamais enseigner qu’une tentation, une attirance involontaire ou un péché passé rend une personne sans valeur."],
  breakpoint:["Moral guilt and toxic shame are not identical. Recognizing that one freely did something wrong does not require believing that one is disgusting or irredeemable.","La culpabilité morale et la honte toxique ne sont pas identiques. Reconnaître qu’on a librement fait quelque chose de mauvais n’exige pas de croire qu’on est répugnant ou irrécupérable."],
  catholicCase:["Catholic repentance is supposed to unite truth about the act with the dignity of the person, forgiveness and restoration. If teaching produces despair or scrupulous self-loathing, its pastoral form needs correction even when the objective norm remains true.","Le repentir catholique doit unir vérité sur l’acte, dignité de la personne, pardon et restauration. Si un enseignement produit désespoir ou dégoût scrupuleux de soi, sa forme pastorale doit être corrigée même lorsque la norme objective reste vraie."],
  counter:["But if the same teaching repeatedly generates shame across many communities, doesn’t that implicate the doctrine itself?","Mais si le même enseignement génère régulièrement de la honte dans de nombreuses communautés, cela n’implique-t-il pas la doctrine elle-même ?"],
  response:["It is evidence worth taking seriously, but one must distinguish harm caused by the proposition from harm caused by teaching methods, family dynamics or confusion between act and person. The empirical question should be investigated rather than assumed either way.","C’est une donnée qu’il faut prendre au sérieux, mais il faut distinguer le dommage causé par la proposition du dommage causé par les méthodes d’enseignement, les dynamiques familiales ou la confusion entre acte et personne. La question empirique doit être examinée plutôt que supposée dans un sens ou l’autre."],
  bottom:["Healthy guilt can call a person to repair a chosen wrong; toxic shame attacks the person’s worth. Catholic teaching should produce the first without cultivating the second.","Une culpabilité saine peut appeler à réparer un mal choisi ; la honte toxique attaque la valeur de la personne. L’enseignement catholique doit produire la première sans cultiver la seconde."]
},
"CSE145":{
  opposition:["If two adults genuinely love each other, their sexual relationship should be judged by that love. “Love is love” rejects arbitrary distinctions between whose affection counts.","Si deux adultes s’aiment réellement, leur relation sexuelle devrait être jugée par cet amour. « L’amour est l’amour » rejette des distinctions arbitraires entre les affections qui compteraient ou non."],
  appeal:["The slogan expresses an important truth: affection, loyalty, sacrifice and personal dignity matter, and relationships should not be dismissed with contempt.","Le slogan exprime une vérité importante : affection, loyauté, sacrifice et dignité personnelle comptent, et les relations ne doivent pas être rejetées avec mépris."],
  concession:["Sincere love is a real good. Catholic ethics does not need to deny genuine affection in order to evaluate a sexual act.","L’amour sincère est un vrai bien. La morale catholique n’a pas besoin de nier une affection authentique pour évaluer un acte sexuel."],
  breakpoint:["The hidden inference is that a loving motive automatically makes every expression of that love good. We do not use that principle consistently elsewhere: love cannot by itself justify adultery, manipulation, contraception or breaking a serious promise.","L’inférence cachée est qu’un motif aimant rend automatiquement bonne toute expression de cet amour. Nous n’utilisons pas ce principe de manière cohérente ailleurs : l’amour ne peut à lui seul justifier adultère, manipulation, contraception ou violation d’une promesse grave."],
  catholicCase:["Catholic morality asks whether love acts in truth toward the good of the beloved. Therefore intention matters greatly, but the chosen act must also respect the goods of sexuality, fidelity and marriage.","La morale catholique demande si l’amour agit dans la vérité envers le bien de l’être aimé. L’intention compte donc beaucoup, mais l’acte choisi doit aussi respecter les biens de la sexualité, de la fidélité et du mariage."],
  counter:["Who gets to define the “true good” of the beloved rather than the couple themselves?","Qui peut définir le « vrai bien » de l’être aimé plutôt que le couple lui-même ?"],
  response:["That is the substantive philosophical question. Catholicism claims human goods are not created entirely by preference; they can be reasoned about from human nature, promises, embodiment and social goods. A critic should challenge that account rather than treat the word love as self-validating.","C’est la véritable question philosophique. Le catholicisme affirme que les biens humains ne sont pas entièrement créés par la préférence ; on peut raisonner à leur sujet à partir de la nature humaine, des promesses, du corps et des biens sociaux. Le critique doit contester cette conception plutôt que traiter le mot amour comme auto-validant."],
  bottom:["Love matters enormously. The disagreement is whether love alone decides which sexual acts are good.","L’amour compte énormément. Le désaccord porte sur la question de savoir si l’amour seul décide quels actes sexuels sont bons."]
},
"CSE149":{
  opposition:["Modern science has changed what we know about sexuality, orientation, psychology and reproduction. Moral rules developed before that knowledge should be revised when science moves on.","La science moderne a changé ce que nous savons de la sexualité, de l’orientation, de la psychologie et de la reproduction. Des règles morales élaborées avant ces connaissances devraient être révisées lorsque la science progresse."],
  appeal:["This is an essential warning. A moral argument resting on a false empirical claim must be corrected.","C’est un avertissement essentiel. Un argument moral reposant sur une affirmation empirique fausse doit être corrigé."],
  concession:["Science can overturn factual assumptions about fertility, development, voluntariness, mental health and medical outcomes. Catholic reasoning should use the best available evidence.","La science peut renverser des présupposés factuels sur la fertilité, le développement, le volontaire, la santé mentale et les résultats médicaux. Le raisonnement catholique doit utiliser les meilleures données disponibles."],
  breakpoint:["The leap occurs when descriptive findings are treated as complete moral conclusions. Science can tell us what happens and with what probability; it does not by itself establish which human goods ought to govern choice.","Le saut se produit lorsque des résultats descriptifs sont traités comme des conclusions morales complètes. La science peut dire ce qui se produit et avec quelle probabilité ; elle n’établit pas à elle seule quels biens humains doivent gouverner le choix."],
  catholicCase:["Psychology can inform whether an attraction is chosen, how compulsion affects freedom or what interventions relieve distress. Biology can explain fertility and embryonic development. Moral judgment then also asks questions about freedom, justice, marriage, bodily meaning and the value of human life.","La psychologie peut éclairer le caractère choisi ou non d’une attirance, l’effet de la compulsion sur la liberté ou les interventions qui soulagent une détresse. La biologie peut expliquer la fertilité et le développement embryonnaire. Le jugement moral pose ensuite aussi des questions sur liberté, justice, mariage, signification corporelle et valeur de la vie humaine."],
  counter:["Isn’t “science cannot decide morality” often used to protect a teaching from contrary evidence?","« La science ne décide pas la morale » n’est-il pas souvent utilisé pour protéger un enseignement contre des preuves contraires ?"],
  response:["It can be misused that way. The safeguard is to expose every empirical premise of the moral argument and let it be tested. If a factual premise fails, the argument must be revised; only the normative premises remain philosophical or theological rather than scientific.","Cette formule peut être mal utilisée ainsi. La protection consiste à exposer chaque prémisse empirique de l’argument moral et à la soumettre à l’examen. Si une prémisse factuelle échoue, l’argument doit être révisé ; seules les prémisses normatives restent philosophiques ou théologiques plutôt que scientifiques."],
  bottom:["Science can falsify facts used in moral arguments. It cannot by itself convert facts into a complete account of what ought to be done.","La science peut falsifier les faits utilisés dans les arguments moraux. Elle ne peut à elle seule transformer les faits en une théorie complète de ce qui doit être fait."]
}
});
