export const CSE_DEBATES_POPULAR=Object.freeze({
"CSE141":{
  opposition:["In a 2013 interview with Antonio Spadaro, Pope Francis warned against insisting only on abortion, same-sex marriage and contraception and urged pastoral context. Why does sexual morality sometimes overshadow mercy, justice, economic wrongdoing and the rest of Christian discipleship?","Dans son entretien de 2013 avec Antonio Spadaro, le pape François avertissait qu'il ne faut pas insister seulement sur l'avortement, le mariage homosexuel et la contraception et demandait de considérer le contexte pastoral. Pourquoi la morale sexuelle éclipse-t-elle parfois la miséricorde, la justice, les fautes économiques et l'ensemble de la vie chrétienne ?"],
  appeal:["The criticism is sometimes deserved. A distorted religious culture can reduce moral formation to sexual prohibitions and neglect justice, charity, truthfulness, greed or cruelty.","La critique est parfois méritée. Une culture religieuse déformée peut réduire la formation morale aux interdictions sexuelles et négliger justice, charité, véracité, avidité ou cruauté."],
  concession:["Catholic morality is much larger than sexual morality, and presenting Christianity as if sexual sins were its only serious sins is bad formation.","La morale catholique est beaucoup plus vaste que la morale sexuelle, et présenter le christianisme comme si les péchés sexuels étaient ses seuls péchés graves constitue une mauvaise formation."],
  breakpoint:["But disproportionate discussion does not show that the underlying sexual norms are false. Public controversy itself can cause certain teachings to receive far more attention than their proportion in the whole moral life.","Mais une discussion disproportionnée ne montre pas que les normes sexuelles sous-jacentes soient fausses. La controverse publique elle-même peut faire recevoir à certains enseignements beaucoup plus d’attention que leur proportion dans l’ensemble de la vie morale."],
  catholicCase:["Sexual chastity is one virtue within the whole moral life. Pope Francis's 2013 interview criticizes pastoral imbalance without revoking the sexual norms; Aquinas treats chastity as part of temperance, not as the summary of every Christian duty. Justice, charity and concern for the poor must receive their full place alongside fidelity and bodily integrity.","La chasteté sexuelle est une vertu parmi celles de la vie morale. Dans l'entretien de 2013, le pape François critique un déséquilibre pastoral sans abroger les normes sexuelles ; saint Thomas traite la chasteté comme une partie de la tempérance, non comme la somme des devoirs chrétiens. Justice, charité et souci des pauvres doivent trouver leur pleine place avec fidélité et intégrité corporelle."],
  counter:["Why do some Christian communities seem to emphasize sexual sins more than injustice, dishonesty, neglect of the poor or failures of charity?","Pourquoi certaines communautés chrétiennes semblent-elles insister davantage sur les péchés sexuels que sur l’injustice, la malhonnêteté, l’abandon des pauvres ou les manquements à la charité ?"],
  response:["Where that imbalance occurs, it should be corrected. The Gospel joins purity of heart to truthfulness, justice, mercy and love of neighbour; neither social sins nor sexual sins may be excused by attention to the other. The gravity of each act must be taught in its proper place within the whole moral life.","Lorsqu’un tel déséquilibre existe, il faut le corriger. L’Évangile unit la pureté du cœur à la véracité, à la justice, à la miséricorde et à l’amour du prochain ; ni les péchés sociaux ni les péchés sexuels ne peuvent être excusés au prétexte qu’on insiste sur les autres. Il faut enseigner la gravité de chaque acte à sa juste place dans l’ensemble de la vie morale."],
  bottom:["The Church should not be obsessed with sex. But misuse or overemphasis of a teaching does not establish that the teaching itself is false.","L’Église ne devrait pas être obsédée par la sexualité. Mais un mauvais usage ou une suraccentuation d’un enseignement ne prouve pas que cet enseignement soit faux."]
},
"CSE142":{
  opposition:["Freud's 1908 essay connected restrictive sexual mores with nervous suffering and questioned whether everyone could redirect sexual desire without harm. Today, prolonged singleness, loneliness and omnipresent explicit media raise a related objection: can a demanding Catholic ethic of chastity be lived without damaging psychological wellbeing?","Dans son essai de 1908, Freud reliait certaines normes sexuelles restrictives à la souffrance nerveuse et doutait que chacun puisse détourner sans dommage son désir sexuel. Aujourd'hui, le célibat prolongé, la solitude et l'omniprésence des contenus explicites nourrissent une objection voisine : peut-on vivre une chasteté catholique exigeante sans nuire à l'équilibre psychologique ?"],
  appeal:["The environment has changed in ways that genuinely increase exposure, temptation and the duration of unmarried adult life.","L’environnement a changé d’une manière qui augmente réellement l’exposition, la tentation et la durée de la vie adulte non mariée."],
  concession:["Chastity can be very difficult, and moral advice that ignores technology, loneliness, habit and delayed marriage can be practically useless.","La chasteté peut être très difficile, et des conseils moraux qui ignorent technologie, solitude, habitudes et mariage tardif peuvent être pratiquement inutiles."],
  breakpoint:["Difficulty does not establish impossibility or falsity. The further premise—that strong sexual desire must be expressed in order for a person to live a healthy human life—also requires proof.","La difficulté ne prouve ni impossibilité ni fausseté. La prémisse supplémentaire — selon laquelle un désir sexuel intense doit être exprimé pour qu’une personne puisse vivre sainement — doit elle aussi être démontrée."],
  catholicCase:["Catholic virtue ethics assumes appetites can be trained rather than merely obeyed. Practically, that means environment, routines, friendships, prayer, sacramental life, digital barriers and avoidance of predictable occasions—not a fantasy of effortless willpower.","L’éthique catholique des vertus suppose que les appétits peuvent être éduqués plutôt que simplement obéis. En pratique, cela signifie environnement, habitudes, amitiés, prière, vie sacramentelle, barrières numériques et évitement des occasions prévisibles — non un fantasme de volonté sans effort."],
  counter:["But repeated failure seems to prove the standard is beyond many people.","Mais les échecs répétés semblent prouver que la norme dépasse beaucoup de personnes."],
  response:["Pastoral teaching must not dismiss trauma, loneliness or compulsive behavior; those may need competent professional care. Aquinas II-II q.151 treats chastity as the governance of desire by reason, not a condemnation of desire itself. Freud's 1908 causal theory cannot, by itself, establish the health outcomes of contemporary Catholic chastity.","L'accompagnement pastoral ne doit pas minimiser traumatismes, solitude ou comportements compulsifs, qui peuvent réclamer des soins compétents. Saint Thomas (II-II, q.151) comprend la chasteté comme le gouvernement du désir par la raison et non comme sa condamnation. La théorie causale de Freud en 1908 ne démontre pas, à elle seule, les effets sanitaires de la chasteté catholique contemporaine."],
  bottom:["Modern conditions can make chastity harder. Harder is not the same as impossible or inhuman.","Les conditions modernes peuvent rendre la chasteté plus difficile. Plus difficile ne signifie pas impossible ni inhumain."]
},
"CSE143":{
  opposition:["Research and testimony describe some associations between restrictive religious sexual messages, shame and distress. This should be investigated seriously, but a reported association is not proof that every traditional norm causes the distress or that all religious formation is harmful.","Des études et des témoignages décrivent parfois une association entre messages religieux sexuels restrictifs, honte et détresse. Cela mérite une étude sérieuse, mais une association rapportée ne prouve ni que toute norme traditionnelle cause cette souffrance ni que toute formation religieuse soit nuisible."],
  appeal:["Religious shame can be real, and humiliating or obsessive instruction can cause genuine harm.","La honte religieuse peut être réelle, et un enseignement humiliant ou obsessionnel peut causer un véritable dommage."],
  concession:["Bad formation should be criticized. A person should never be taught that temptation, involuntary attraction or past sin makes him or her worthless.","Une mauvaise formation doit être critiquée. On ne doit jamais enseigner qu’une tentation, une attirance involontaire ou un péché passé rend une personne sans valeur."],
  breakpoint:["Moral guilt and toxic shame are not identical. Recognizing that one freely did something wrong does not require believing that one is disgusting or irredeemable.","La culpabilité morale et la honte toxique ne sont pas identiques. Reconnaître qu’on a librement fait quelque chose de mauvais n’exige pas de croire qu’on est répugnant ou irrécupérable."],
  catholicCase:["Christian repentance distinguishes a freely chosen wrong from a person's inherent dignity and capacity to seek forgiveness. Involuntary attraction, a distressing thought or a history of abuse is not proof of personal sin. Pastoral teaching that produces humiliation, despair or obsessive self-condemnation requires correction; the independent truth of a moral norm must be argued rather than inferred from either shame or its absence.","Le repentir chrétien distingue un mal librement choisi de la dignité personnelle et de la possibilité du pardon. Une attirance involontaire, une pensée pénible ou un passé de violence ne prouvent aucun péché personnel. Une formation qui engendre humiliation, désespoir ou auto-condamnation obsessionnelle doit être corrigée ; la vérité d'une norme morale doit être argumentée indépendamment de la honte ou de son absence."],
  counter:["But if the same teaching repeatedly generates shame across many communities, doesn’t that implicate the doctrine itself?","Mais si le même enseignement génère régulièrement de la honte dans de nombreuses communautés, cela n’implique-t-il pas la doctrine elle-même ?"],
  response:["Reports of distress deserve investigation, but an association between shame and religious instruction does not identify a cause on its own. Humiliating teaching methods, familial control and confusion between an involuntary thought and chosen sin must be distinguished from the normative claim itself; psychological findings should neither be dismissed nor turned into automatic proof against every moral norm.","Les témoignages de souffrance exigent une enquête sérieuse, mais une association entre honte et enseignement religieux ne démontre pas seule une causalité. Il faut distinguer les méthodes humiliantes, le contrôle familial et la confusion entre pensée involontaire et péché choisi de la proposition morale elle-même ; les résultats psychologiques ne doivent être ni écartés ni transformés en réfutation automatique de toute norme."],
  bottom:["Healthy guilt can call a person to repair a chosen wrong; toxic shame attacks the person’s worth. Catholic teaching should produce the first without cultivating the second.","Une culpabilité saine peut appeler à réparer un mal choisi ; la honte toxique attaque la valeur de la personne. L’enseignement catholique doit produire la première sans cultiver la seconde."]
},
"CSE145":{
  opposition:["'Love is love' expresses a serious appeal to equal human dignity, affection and commitment. If partners are sincerely devoted to each other's good, why should a moral tradition deny that their sexual relationship is good?","« L'amour, c'est l'amour » exprime un appel sérieux à l'égale dignité humaine, à l'affection et à l'engagement. Si deux partenaires recherchent sincèrement le bien l'un de l'autre, pourquoi une tradition morale refuserait-elle de juger bonne leur relation sexuelle ?"],
  appeal:["The slogan expresses an important truth: affection, loyalty, sacrifice and personal dignity matter, and relationships should not be dismissed with contempt.","Le slogan exprime une vérité importante : affection, loyauté, sacrifice et dignité personnelle comptent, et les relations ne doivent pas être rejetées avec mépris."],
  concession:["Sincere love is a real good. Catholic ethics does not need to deny genuine affection in order to evaluate a sexual act.","L’amour sincère est un vrai bien. La morale catholique n’a pas besoin de nier une affection authentique pour évaluer un acte sexuel."],
  breakpoint:["Sincere affection is a real good, but it cannot by itself establish the goodness of every act undertaken in its name. Veritatis Splendor §§78–80 distinguishes a person's further intention from the moral object freely chosen. Genuine love must also be evaluated in relation to truth, fidelity and the objective goods of the person.","Une affection sincère est un bien réel, mais elle ne démontre pas à elle seule la bonté de tous les actes accomplis en son nom. Veritatis Splendor (§§78–80) distingue l'intention ultérieure de la personne de l'objet moral librement choisi. L'amour véritable doit aussi être apprécié selon la vérité, la fidélité et les biens objectifs de la personne."],
  catholicCase:["Catholic morality asks whether love acts in truth toward the good of the beloved. Therefore intention matters greatly, but the chosen act must also respect the goods of sexuality, fidelity and marriage.","La morale catholique demande si l’amour agit dans la vérité envers le bien de l’être aimé. L’intention compte donc beaucoup, mais l’acte choisi doit aussi respecter les biens de la sexualité, de la fidélité et du mariage."],
  counter:["Who gets to define the “true good” of the beloved rather than the couple themselves?","Qui peut définir le « vrai bien » de l’être aimé plutôt que le couple lui-même ?"],
  response:["Human goods are not created entirely by preference. Catholic moral reasoning considers the nature of the person, the body's meaning, promises and fidelity; affection alone does not determine whether a sexual act respects those goods.","Les biens humains ne résultent pas entièrement des préférences. La morale catholique considère la nature de la personne, la signification du corps, les engagements et la fidélité ; l'affection seule ne suffit pas à établir qu'un acte sexuel respecte ces biens."],
  bottom:["Love matters enormously. The disagreement is whether love alone decides which sexual acts are good.","L’amour compte énormément. Le désaccord porte sur la question de savoir si l’amour seul décide quels actes sexuels sont bons."]
},
"CSE149":{
  opposition:["Psychological and medical research can overturn factual assumptions about sexuality, distress and treatment outcomes. Professional bodies such as the APA and ASRM also defend access to services they regard as clinically appropriate. If Catholic moral conclusions rely partly on empirical premises that change, must those conclusions be reconsidered as well?","Les recherches psychologiques et médicales peuvent démentir certaines prémisses factuelles sur la sexualité, la souffrance et les effets des traitements. Des organismes comme l'APA et l'ASRM défendent aussi l'accès à des soins qu'ils jugent appropriés. Si certaines conclusions morales catholiques dépendent de faits empiriques révisables, ne doivent-elles pas être réexaminées à leur tour ?"],
  appeal:["This is an essential warning. A moral argument resting on a false empirical claim must be corrected.","C’est un avertissement essentiel. Un argument moral reposant sur une affirmation empirique fausse doit être corrigé."],
  concession:["Science can overturn factual assumptions about fertility, development, voluntariness, mental health and medical outcomes. Catholic reasoning should use the best available evidence.","La science peut renverser des présupposés factuels sur la fertilité, le développement, le volontaire, la santé mentale et les résultats médicaux. Le raisonnement catholique doit utiliser les meilleures données disponibles."],
  breakpoint:["The leap occurs when descriptive findings are treated as complete moral conclusions. Science can tell us what happens and with what probability; it does not by itself establish which human goods ought to govern choice.","Le saut se produit lorsque des résultats descriptifs sont traités comme des conclusions morales complètes. La science peut dire ce qui se produit et avec quelle probabilité ; elle n’établit pas à elle seule quels biens humains doivent gouverner le choix."],
  catholicCase:["Psychology can inform whether an attraction is chosen, how compulsion affects freedom or what interventions relieve distress. Biology can explain fertility and embryonic development. Moral judgment then also asks questions about freedom, justice, marriage, bodily meaning and the value of human life.","La psychologie peut éclairer le caractère choisi ou non d’une attirance, l’effet de la compulsion sur la liberté ou les interventions qui soulagent une détresse. La biologie peut expliquer la fertilité et le développement embryonnaire. Le jugement moral pose ensuite aussi des questions sur liberté, justice, mariage, signification corporelle et valeur de la vie humaine."],
  counter:["Isn’t “science cannot decide morality” often used to protect a teaching from contrary evidence?","« La science ne décide pas la morale » n’est-il pas souvent utilisé pour protéger un enseignement contre des preuves contraires ?"],
  response:["Any empirical premise used to defend Catholic moral claims must be open to correction: a diagnostic classification, an observed treatment effect and a fertility outcome are matters for evidence. Such evidence can require revision of an argument's factual foundation without, by itself, establishing its ethical conclusion. Conversely, an appeal to doctrine cannot excuse falsifying scientific facts or ignoring clinical uncertainty.","Toute prémisse empirique invoquée à l'appui d'une affirmation morale catholique doit rester ouverte à la correction : classifications diagnostiques, effets observés des soins et résultats de fertilité sont des questions de preuve. Les données peuvent imposer de corriger le fondement factuel d'un raisonnement sans suffire, à elles seules, à établir sa conclusion morale. Inversement, la doctrine ne permet ni de déformer les faits scientifiques ni d'ignorer l'incertitude clinique."],
  bottom:["Science can falsify facts used in moral arguments. It cannot by itself convert facts into a complete account of what ought to be done.","La science peut falsifier les faits utilisés dans les arguments moraux. Elle ne peut à elle seule transformer les faits en une théorie complète de ce qui doit être fait."]
}
});
