export const CSE_DEBATES_001_031=Object.freeze({
"CSE006":{
  opposition:["A familiar liberty-based objection holds that adults should not face state coercion for private sexual choices that do not harm others. John Stuart Mill argues particularly against coercive social authority; a further argument is needed to claim that every unharming choice is morally good.","Une objection courante fondée sur la liberté soutient que les adultes ne devraient pas subir de contrainte étatique pour des choix sexuels privés qui ne nuisent pas à autrui. John Stuart Mill conteste surtout l’autorité sociale coercitive ; il faut un argument supplémentaire pour conclure que tout choix sans dommage est moralement bon."],
  appeal:["This is attractive because it protects liberty and correctly treats unjust harm as morally serious. It also guards against intrusive rules based only on disgust or convention.","Cette position séduit parce qu’elle protège la liberté et reconnaît à juste titre que le tort injuste est moralement grave. Elle protège aussi contre des règles intrusives fondées seulement sur le dégoût ou la convention."],
  concession:["Causing unjust harm is a major moral consideration, and not every private preference should be regulated.","Causer un tort injuste est une considération morale majeure, et toute préférence privée ne doit pas être réglementée."],
  breakpoint:["The illicit inference is from limits on public coercion to the claim that avoiding harm exhausts personal morality. Whether the state may prohibit an act is distinct from whether someone should choose it. Fidelity, self-mastery and freely assumed obligations require moral examination even where civil prohibition would be unjustified.","Le saut illégitime consiste à déduire des limites de la contrainte publique que l’absence de dommage épuise la morale personnelle. Que l’État puisse interdire un acte est distinct de la question de savoir si quelqu’un devrait le choisir. Fidélité, maîtrise de soi et obligations librement assumées demandent un examen moral même si une interdiction civile serait injustifiée."],
  catholicCase:["Catholic ethics asks not only who is harmed, but what kind of act is deliberately chosen and which human goods it respects or contradicts. Sexuality is judged in relation to chastity, marriage, fidelity and procreation, not by a harm test alone.","La morale catholique demande non seulement qui est lésé, mais quel type d’acte est délibérément choisi et quels biens humains il respecte ou contredit. La sexualité est jugée en relation avec la chasteté, le mariage, la fidélité et la procréation, non par le seul critère du dommage."],
  counter:["Mill himself allows persuasion and moral education without coercion. But why should a non-Catholic accept the specifically Catholic account of sexuality?","Mill lui-même admet la persuasion et l’éducation morale sans coercition. Mais pourquoi un non-catholique accepterait-il la conception spécifiquement catholique de la sexualité ?"],
  response:["Fidelity, rational self-mastery, marriage and care for children are intelligible human goods, not duties arising only from Church membership (Aquinas, I-II q.94 a.2). Whether a particular choice contradicts them depends on the moral object deliberately chosen (Veritatis Splendor §78). Even conduct judged morally wrong does not automatically warrant civil prohibition.","La fidélité, la maîtrise rationnelle de soi, le mariage et le soin des enfants sont des biens humains intelligibles, non des devoirs nés de la seule appartenance à l’Église (saint Thomas, I-II, q.94, a.2). Qu’un choix particulier les contredise dépend de l’objet moral délibérément choisi (Veritatis Splendor, §78). Même une conduite jugée moralement mauvaise ne justifie pas automatiquement son interdiction civile."],
  bottom:["Harm matters, but it is not the whole of morality. The decisive question is whether the chosen act respects the goods that make human sexuality intelligible.","Le dommage compte, mais il n’épuise pas la morale. La question décisive est de savoir si l’acte choisi respecte les biens qui donnent sens à la sexualité humaine."]
},
"CSE007":{
  opposition:["Consent is indispensable: without it, sexual activity is assault. Some infer that informed adults who freely consent need no further moral rules; why should the Church impose additional conditions?","Le consentement est indispensable : sans lui, une activité sexuelle est une agression. Certains en déduisent que des adultes informés et consentants n’ont besoin d’aucune règle morale supplémentaire ; pourquoi l’Église ajouterait-elle d’autres conditions ?"],
  appeal:["Coercive sex is gravely wrong, and free consent is indispensable in any just relationship.","La sexualité coercitive est gravement mauvaise, et le consentement libre est indispensable à toute relation juste."],
  concession:["Consent is necessary. Without it, the injustice can be severe.","Le consentement est nécessaire. Sans lui, l’injustice peut être grave."],
  breakpoint:["The invalid inference is from necessary to sufficient. Consent tells us that people chose an act; it does not tell us whether the act they chose was faithful, just, chaste, or compatible with duties they already have.","L’inférence invalide consiste à passer de nécessaire à suffisant. Le consentement indique que des personnes ont choisi un acte ; il ne dit pas si cet acte était fidèle, juste, chaste ou compatible avec des devoirs déjà assumés."],
  catholicCase:["Two people can consent to adultery, to an exploitative commercial arrangement, or to conduct that violates a prior promise. Catholic ethics therefore asks two questions: Was it freely chosen? And what exactly was chosen?","Deux personnes peuvent consentir à l’adultère, à un arrangement commercial exploiteur ou à une conduite qui viole une promesse antérieure. La morale catholique pose donc deux questions : l’acte a-t-il été librement choisi ? Et qu’a-t-on exactement choisi ?"],
  counter:["But those examples add betrayal or exploitation. What if two unattached adults consent and no other duty is violated?","Mais ces exemples ajoutent trahison ou exploitation. Et si deux adultes sans engagement consentent et qu’aucun autre devoir n’est violé ?"],
  response:["Then the dispute moves from consent to the nature of sexual union itself: whether sexual acts have goods and meanings that are not created solely by agreement. Catholicism says they do, especially through their relation to marriage and generation.","Le débat se déplace alors du consentement vers la nature même de l’union sexuelle : les actes sexuels ont-ils des biens et des significations qui ne sont pas créés uniquement par l’accord ? Le catholicisme répond oui, notamment en raison de leur rapport au mariage et à la génération."],
  bottom:["Consent is indispensable, but it cannot make every chosen act good. It answers who chose; it does not by itself answer whether the choice was good.","Le consentement est indispensable, mais il ne peut rendre bon tout acte choisi. Il répond à la question de savoir qui a choisi ; il ne suffit pas à dire si le choix était bon."]
},
"CSE008":{
  opposition:["Situation ethicists argue that agapeic love is the one unconditional norm: an action ordinarily forbidden by a rule could be morally required when it truly serves the neighbour's good in a particular situation. Why should an absolute negative rule override that loving judgment?","Selon la morale de situation, l’amour de charité (agapè) est la seule norme inconditionnelle : un acte normalement interdit par une règle pourrait être moralement requis si, dans une situation particulière, il sert véritablement le bien du prochain. Pourquoi une interdiction absolue devrait-elle prévaloir sur ce jugement d’amour ?"],
  appeal:["Intentions genuinely matter. The same outward behavior can have very different moral meaning depending on whether it is done from love, malice, fear or selfishness.","Les intentions comptent réellement. Le même comportement extérieur peut avoir une signification morale très différente selon qu’il procède de l’amour, de la malice, de la peur ou de l’égoïsme."],
  concession:["Catholic morality fully agrees that intention is one essential part of a human act and can increase or lessen responsibility.","La morale catholique reconnaît pleinement que l’intention est une dimension essentielle de l’acte humain et peut augmenter ou diminuer la responsabilité."],
  breakpoint:["The error is making intention the only source of moral goodness. A good end does not automatically make the chosen means good.","L’erreur consiste à faire de l’intention l’unique source de bonté morale. Une bonne fin ne rend pas automatiquement bon le moyen choisi."],
  catholicCase:["The tradition distinguishes the object chosen, the further intention and the circumstances. A person can sincerely seek a good end and still choose a means that contradicts another serious good.","La tradition distingue l’objet choisi, l’intention ultérieure et les circonstances. Une personne peut sincèrement rechercher une bonne fin tout en choisissant un moyen qui contredit un autre bien grave."],
  counter:["But in real life the object and intention are often inseparable. Isn’t this distinction artificial?","Mais dans la vie réelle, l’objet et l’intention sont souvent inséparables. Cette distinction n’est-elle pas artificielle ?"],
  response:["They are connected but not identical. The same desired end can be pursued by different means, and moral reasoning routinely distinguishes between them. Wanting to save a relationship, avoid pregnancy or relieve distress does not tell us which act was chosen to achieve that end.","Ils sont liés mais non identiques. La même fin désirée peut être poursuivie par des moyens différents, et le raisonnement moral les distingue constamment. Vouloir sauver une relation, éviter une grossesse ou soulager une détresse ne dit pas quel acte a été choisi pour y parvenir."],
  bottom:["Good intentions matter greatly, but they do not erase the moral character of the means deliberately chosen.","Les bonnes intentions comptent beaucoup, mais elles n’effacent pas le caractère moral des moyens délibérément choisis."]
},
"CSE010":{
  opposition:["Joseph Fletcher's situation ethics holds that agapeic love alone is an exceptionless moral norm. An act normally forbidden by a general rule might, in an unusual circumstance, be justified in the name of that love. Is it credible to claim that some kinds of chosen acts can never be justified?","La morale de situation de Joseph Fletcher considère l’amour de charité (agapè) comme la seule norme morale sans exception. Un acte normalement interdit par une règle générale pourrait, dans des circonstances particulières, être justifié au nom de cet amour. Peut-on soutenir de façon crédible que certains actes librement choisis ne puissent jamais être justifiés ?"],
  appeal:["Circumstances clearly matter, and simple rules can be applied badly when they ignore coercion, fear, ignorance or competing duties.","Les circonstances comptent manifestement, et des règles simples peuvent être mal appliquées lorsqu’elles ignorent la contrainte, la peur, l’ignorance ou des devoirs concurrents."],
  concession:["Catholic morality agrees that circumstances and culpability can radically change how responsible a person is.","La morale catholique reconnaît que les circonstances et la culpabilité peuvent modifier radicalement la responsabilité d’une personne."],
  breakpoint:["The mistake is moving from “circumstances affect responsibility” to “circumstances can make every object good.” Those are different claims.","L’erreur consiste à passer de « les circonstances affectent la responsabilité » à « les circonstances peuvent rendre bon tout objet ». Ce sont deux affirmations différentes."],
  catholicCase:["An intrinsically evil act is one whose chosen object is incompatible with the good of the person in every case. The doctrine concerns the act’s moral species, not a claim that every person who commits it is equally guilty.","Un acte intrinsèquement mauvais est un acte dont l’objet choisi est incompatible avec le bien de la personne dans tous les cas. La doctrine concerne l’espèce morale de l’acte, non l’affirmation que toute personne qui le commet est également coupable."],
  counter:["Doesn’t that simply define the answer in advance?","Cela ne revient-il pas simplement à définir la réponse d’avance ?"],
  response:["Only if no argument is offered for why the object is always incompatible with the good. The real work is identifying the moral object correctly and showing why it cannot be ordered to a good end. “Intrinsic evil” is the conclusion of that analysis, not a substitute for it.","Seulement si aucun argument n’est donné pour montrer pourquoi l’objet est toujours incompatible avec le bien. Le vrai travail consiste à identifier correctement l’objet moral et à montrer pourquoi il ne peut être ordonné à une bonne fin. « Intrinsèquement mauvais » est la conclusion de l’analyse, non son substitut."],
  bottom:["Absolute norms do not deny complexity. They distinguish the objective character of a choice from the often much more complex question of personal culpability.","Les normes absolues ne nient pas la complexité. Elles distinguent le caractère objectif d’un choix de la question, souvent bien plus complexe, de la culpabilité personnelle."]
},
"CSE012":{
  opposition:["The Gospels do not name contraception, IVF or many modern practices. If Christ did not discuss a technique expressly, why should Christians accept a later moral judgment about it?","Les Évangiles ne nomment ni la contraception, ni la FIV, ni bien des pratiques modernes. Si le Christ n’a pas évoqué expressément une technique, pourquoi les chrétiens devraient-ils accepter un jugement moral ultérieur ?"],
  appeal:["Later Christian formulations should not be presented as though Jesus had spoken those exact words in the Gospels.","Les formulations chrétiennes ultérieures ne doivent pas être présentées comme si Jésus avait prononcé exactement ces mots dans les Évangiles."],
  concession:["Many modern practices are not named in the Gospels, and a serious Christian argument cannot pretend otherwise.","De nombreuses pratiques modernes ne sont pas nommées dans les Évangiles, et un argument chrétien sérieux ne peut prétendre le contraire."],
  breakpoint:["The hidden premise is that Christian morality is limited to a list of behaviors explicitly named by Jesus. The New Testament itself does not work that way.","La prémisse cachée est que la morale chrétienne se limite à une liste de comportements explicitement nommés par Jésus. Le Nouveau Testament lui-même ne fonctionne pas ainsi."],
  catholicCase:["Jesus teaches on adultery, lust, divorce, marriage and sexual immorality; the apostles develop Christian moral teaching; and natural-law reasoning applies enduring principles to acts unknown in the first century. New technology can therefore raise a new case without requiring a new moral universe.","Jésus enseigne sur l’adultère, la convoitise, le divorce, le mariage et l’immoralité sexuelle ; les apôtres développent l’enseignement moral chrétien ; et la loi naturelle applique des principes durables à des actes inconnus au Ier siècle. Une nouvelle technologie peut donc créer un nouveau cas sans exiger un nouvel univers moral."],
  counter:["But how do we know later Christians are applying Jesus rather than importing their own prejudices?","Mais comment savoir si les chrétiens ultérieurs appliquent Jésus plutôt qu’ils n’importent leurs propres préjugés ?"],
  response:["A modern act must be assessed by tracing its moral features against Scripture, natural law and the relevant source chain. The absence of an exact modern term neither proves permission nor proves prohibition.","Un acte moderne doit être évalué en confrontant ses caractéristiques morales à l’Écriture, à la loi naturelle et à la chaîne de sources pertinente. L’absence d’un terme moderne exact ne prouve ni la permission ni l’interdiction."],
  bottom:["“Jesus never used this word” is not enough. The real question is whether the later norm follows from the moral principles Christianity actually received.","« Jésus n’a jamais utilisé ce mot » ne suffit pas. La vraie question est de savoir si la norme ultérieure découle des principes moraux réellement reçus par le christianisme."]
},
"CSE013":{
  opposition:["Paul was an ancient man shaped by Jewish and Greco-Roman assumptions. His sexual prohibitions may reflect his culture rather than permanent moral truth.","Paul était un homme de l’Antiquité façonné par des présupposés juifs et gréco-romains. Ses interdictions sexuelles peuvent refléter sa culture plutôt qu’une vérité morale permanente."],
  appeal:["Historical context matters, and Christians can misread ancient texts when they ignore language, genre and social assumptions.","Le contexte historique compte, et les chrétiens peuvent mal lire les textes anciens lorsqu’ils ignorent la langue, le genre et les présupposés sociaux."],
  concession:["Paul wrote in a particular culture, so exegesis must distinguish local custom from the reasons he gives for a moral norm.","Paul écrivait dans une culture particulière ; l’exégèse doit donc distinguer les usages locaux des raisons qu’il donne pour une norme morale."],
  breakpoint:["A cultural setting by itself does not make a moral teaching culturally relative. One must show that Paul’s stated reasons depend on a premise we now know to be false or merely local.","Un contexte culturel ne rend pas à lui seul un enseignement moral culturellement relatif. Il faut montrer que les raisons données par Paul dépendent d’une prémisse que nous savons aujourd’hui fausse ou purement locale."],
  catholicCase:["In key sexual texts Paul appeals to creation, the body’s belonging to Christ and God’s call to holiness, not merely to etiquette. Those reasons are presented as theological and moral claims, not as temporary social conventions.","Dans les principaux textes sexuels, Paul en appelle à la création, à l’appartenance du corps au Christ et à l’appel de Dieu à la sainteté, non à de simples convenances. Ces raisons sont présentées comme des affirmations théologiques et morales, non comme des conventions sociales temporaires."],
  counter:["But even theological reasoning can be shaped by mistaken ancient anthropology.","Mais même un raisonnement théologique peut être façonné par une anthropologie antique erronée."],
  response:["Yes; therefore the critic must identify the mistaken anthropology and show that the moral conclusion depends on it. “Ancient” is a historical description, not yet a refutation.","Oui ; le critique doit donc identifier l’anthropologie erronée et montrer que la conclusion morale en dépend. « Antique » est une description historique, pas encore une réfutation."],
  bottom:["Context must be studied, but culture alone does not dissolve an argument. The question is whether Paul’s reasons survive historical scrutiny.","Le contexte doit être étudié, mais la culture seule ne dissout pas un argument. La question est de savoir si les raisons de Paul résistent à l’examen historique."]
},
"CSE014":{
  opposition:["The Church has changed positions before, so current sexual teaching could change too. Appeals to “unchanging doctrine” often ignore real historical development.","L’Église a déjà changé de position ; l’enseignement sexuel actuel pourrait donc changer lui aussi. Les appels à une « doctrine immuable » ignorent souvent le développement historique réel."],
  appeal:["Formulations, disciplines and canonical rules have not always been identical; genuine historical development must be acknowledged.","Les formulations, les disciplines et les règles canoniques n’ont pas toujours été identiques ; un véritable développement historique doit être reconnu."],
  concession:["Terminology, discipline, canonical penalties, pastoral strategies and applications do change. Development is real.","La terminologie, la discipline, les peines canoniques, les stratégies pastorales et les applications changent. Le développement est réel."],
  breakpoint:["The missing distinction is between development and contradiction. Evidence of some change does not establish that the same moral object was once taught good and later taught intrinsically evil, or the reverse.","La distinction manquante est celle entre développement et contradiction. Le fait qu’il existe des changements ne montre pas que le même objet moral ait été enseigné comme bon puis comme intrinsèquement mauvais, ou inversement."],
  catholicCase:["The continuity chain is substantial: New Testament teaching on adultery, fornication and marriage; the Roman Catechism; and later papal teaching such as Casti Connubii. Newer documents often refine concepts or apply them to new technology rather than inventing the underlying norm.","La chaîne de continuité est substantielle : enseignement du Nouveau Testament sur l’adultère, la fornication et le mariage ; Catéchisme romain ; puis enseignement pontifical tel que Casti Connubii. Les documents plus récents précisent souvent les concepts ou les appliquent à de nouvelles technologies plutôt que d’inventer la norme sous-jacente."],
  counter:["But isn’t that just selecting examples that support continuity and ignoring difficult cases?","Mais cela ne revient-il pas à choisir des exemples favorables à la continuité et à ignorer les cas difficiles ?"],
  response:["A change in disciplinary penalties or pastoral practice does not reverse a moral norm. A genuine doctrinal contradiction requires the same moral act, under the same relevant conditions, to be taught as both intrinsically permissible and intrinsically wrong by authorities making comparable claims. A documented reversal cannot be inferred merely from historical variation.","Un changement des peines disciplinaires ou des pratiques pastorales ne renverse pas une norme morale. Une véritable contradiction doctrinale supposerait que le même acte moral, dans les mêmes conditions pertinentes, soit enseigné comme intrinsèquement licite et intrinsèquement mauvais par des autorités formulant des jugements comparables. Une variation historique ne prouve pas à elle seule un tel renversement."],
  bottom:["Historical development is real, but it does not make every moral norm provisional. The alleged contradiction must be demonstrated at the level of the same moral proposition.","Le développement historique est réel, mais il ne rend pas toute norme morale provisoire. La contradiction alléguée doit être démontrée au niveau de la même proposition morale."]
},
"CSE016":{
  opposition:["A person must follow conscience. Therefore if my sincere conscience tells me a sexual act is right, obeying the Church instead would mean betraying my own moral judgment.","Une personne doit suivre sa conscience. Donc si ma conscience sincère me dit qu’un acte sexuel est juste, obéir à l’Église signifierait trahir mon propre jugement moral."],
  appeal:["This argument takes conscience seriously and correctly rejects acting against what one presently judges to be morally obligatory.","Cet argument prend la conscience au sérieux et rejette à juste titre le fait d’agir contre ce que l’on juge présentement moralement obligatoire."],
  concession:["A person should not deliberately act against a certain judgment of conscience.","Une personne ne doit pas agir délibérément contre un jugement certain de conscience."],
  breakpoint:["The false inference is that conscience is therefore infallible or creates moral truth. Conscience is a judgment about truth, and judgments can be mistaken.","L’inférence fausse est que la conscience serait donc infaillible ou créerait la vérité morale. La conscience est un jugement sur la vérité, et un jugement peut être erroné."],
  catholicCase:["Catholic teaching therefore joins two duties: follow conscience and form conscience. Formation includes seeking evidence, understanding authoritative teaching, examining motives and remaining willing to correct an error.","L’enseignement catholique unit donc deux devoirs : suivre sa conscience et former sa conscience. Cette formation comprend la recherche des preuves, la compréhension de l’enseignement autoritatif, l’examen des motifs et la disposition à corriger une erreur."],
  counter:["Doesn’t “form your conscience” just mean “make it agree with the Church”?","« Former sa conscience » ne signifie-t-il pas simplement « la faire coïncider avec l’Église » ?"],
  response:["The Church’s authentic moral teaching is not merely one private opinion for a Catholic. Understanding its authority and reasons, examining serious objections and continuing to seek truth are real obligations: Donum Veritatis §§23–31 permits responsible inquiry without making conscience an independent source of doctrinal truth. Sincere certainty can coexist with error.","L’enseignement moral authentique de l’Église n’est pas une simple opinion privée pour un catholique. En comprendre l’autorité et les raisons, examiner les objections sérieuses et rechercher la vérité sont des devoirs réels : Donum Veritatis (§§23–31) admet une recherche responsable sans faire de la conscience une source autonome de vérité doctrinale. La certitude sincère peut coexister avec l’erreur."],
  bottom:["Conscience binds, but conscience can err. The Catholic task is neither blind obedience nor private infallibility, but sincere judgment disciplined by truth.","La conscience oblige, mais elle peut se tromper. La tâche catholique n’est ni l’obéissance aveugle ni l’infaillibilité privée, mais un jugement sincère discipliné par la vérité."]
},
"CSE018":{
  opposition:["If qualified Catholic theologians disagree, ordinary Catholics cannot be expected to know which side is right. In practice, disagreement should create freedom to choose.","Si des théologiens catholiques qualifiés sont en désaccord, on ne peut attendre des fidèles ordinaires qu’ils sachent quel camp a raison. En pratique, le désaccord devrait créer une liberté de choix."],
  appeal:["Laypeople cannot independently master every technical theological dispute, so questions of authority and reliable guidance genuinely matter.","Les laïcs ne peuvent maîtriser indépendamment toute controverse théologique technique ; les questions d’autorité et de guidance fiable comptent donc réellement."],
  concession:["There are genuine open questions in Catholic theology, and expert disagreement can be evidence that a matter is not settled.","Il existe de véritables questions ouvertes en théologie catholique, et le désaccord d’experts peut indiquer qu’une question n’est pas tranchée."],
  breakpoint:["The mistake is assuming that disagreement itself determines doctrinal status. The relevant question is what authority has taught and whether the matter remains open within that teaching.","L’erreur est de supposer que le désaccord détermine à lui seul le statut doctrinal. La question pertinente est ce que l’autorité a enseigné et si la matière demeure ouverte dans cet enseignement."],
  catholicCase:["Catholic theology distinguishes disputed questions from authoritative moral teaching. Donum Veritatis explicitly allows serious difficulty and further inquiry while rejecting the idea that the Magisterium is merely one opinion among competing schools.","La théologie catholique distingue les questions disputées de l’enseignement moral autoritatif. Donum Veritatis reconnaît la possibilité de difficultés sérieuses et de recherches ultérieures tout en rejetant l’idée que le Magistère soit simplement une opinion parmi des écoles concurrentes."],
  counter:["But theologians sometimes challenge authoritative teaching precisely because they think the argument is defective.","Mais des théologiens contestent parfois un enseignement autoritatif précisément parce qu’ils jugent l’argument défectueux."],
  response:["Serious theological disagreement can create a real problem, but it does not make an authoritative teaching doctrinally optional by private vote. Its authority and reasons must be examined, while distinguishing legitimate difficulty from permission simply to contradict it.","Un désaccord théologique sérieux peut créer un véritable problème, mais il ne rend pas un enseignement autoritatif doctrinalement facultatif par vote privé. Il faut examiner son autorité et ses raisons, tout en distinguant une difficulté légitime de la permission de le contredire simplement."],
  bottom:["The number of dissenting theologians does not settle the issue. First determine whether the question is actually open and what authority the disputed teaching possesses.","Le nombre de théologiens dissidents ne tranche pas la question. Il faut d’abord déterminer si la matière est réellement ouverte et quelle autorité possède l’enseignement contesté."]
},
"CSE020":{
  opposition:["An entrenched habit can involve strong urges and reduced control. Does this diminish personal responsibility for a particular act, even when the act itself is morally wrong?","Une habitude enracinée peut s’accompagner d’impulsions fortes et d’un contrôle diminué. Cela réduit-il la responsabilité d’un acte particulier, même lorsque l’acte demeure moralement mauvais ?"],
  appeal:["Outwardly identical acts can involve very different degrees of freedom, deliberation and compulsion.","Des actes extérieurement identiques peuvent impliquer des degrés très différents de liberté, de délibération et de compulsion."],
  concession:["Compulsion, anxiety, immaturity and deeply rooted habits can diminish voluntariness and culpability in a particular act.","La compulsion, l’anxiété, l’immaturité et des habitudes profondément enracinées peuvent diminuer le volontaire et la culpabilité dans un acte particulier."],
  breakpoint:["The label “habit” does not prove that freedom has disappeared, and research on substance addiction does not establish a diagnosis of sexual addiction. Aquinas distinguishes passion diminishing voluntariness from an act knowingly chosen through established habit (I-II qq.77–78). Actual deliberation and earlier choices must be considered separately.","Le terme « habitude » ne prouve pas la disparition de la liberté, et les recherches sur la dépendance aux substances n’établissent pas un diagnostic de dépendance sexuelle. Saint Thomas distingue la passion qui diminue le volontaire de l’acte choisi sciemment sous l’effet d’une habitude (I-II, qq.77–78). La délibération effective et les choix antérieurs doivent être considérés séparément."],
  catholicCase:["Traditional moral analysis therefore asks about actual knowledge and freedom in the concrete act, while also considering how the habit developed and whether the person resists or reinforces it.","L’analyse morale traditionnelle examine donc la connaissance et la liberté effectives dans l’acte concret, tout en considérant comment l’habitude s’est formée et si la personne y résiste ou la renforce."],
  counter:["Isn’t that impossible to measure reliably?","N’est-ce pas impossible à mesurer avec fiabilité ?"],
  response:["Often it is difficult, which is why categorical judgments about another person’s mortal guilt are unsafe. Difficulty of measuring culpability, however, does not change the objective moral character of the act.","C’est souvent difficile, raison pour laquelle les jugements catégoriques sur la culpabilité mortelle d’autrui sont imprudents. Mais la difficulté de mesurer la culpabilité ne change pas le caractère moral objectif de l’acte."],
  bottom:["Habit can reduce responsibility, but not automatically. Objective act and subjective culpability must remain distinct.","L’habitude peut réduire la responsabilité, mais pas automatiquement. L’acte objectif et la culpabilité subjective doivent rester distincts."]
},
"CSE021":{
  opposition:["In his 1908 essay Freud associates restrictive sexual morality with nervous suffering. If restraint can produce distress, why regard chastity as a virtue rather than unhealthy repression?","Dans son essai de 1908, Freud associe une morale sexuelle restrictive à des souffrances nerveuses. Si la retenue peut provoquer la détresse, pourquoi voir dans la chasteté une vertu plutôt qu’une répression malsaine ?"],
  appeal:["The criticism has force when chastity is taught as shame, disgust toward the body or constant anxiety about temptation.","La critique est forte lorsque la chasteté est enseignée comme honte, dégoût du corps ou anxiété constante devant la tentation."],
  concession:["Bad formation can become repressive. Sexual desire is part of human nature and is not itself sinful.","Une mauvaise formation peut devenir répressive. Le désir sexuel appartient à la nature humaine et n’est pas en lui-même pécheur."],
  breakpoint:["Restraint of desire is not equivalent to repression. Mature human agency includes ordering powerful desires rather than simply expressing them whenever they arise.","La maîtrise du désir n’équivaut pas à la répression. L’action humaine mûre implique d’ordonner des désirs puissants plutôt que de les exprimer chaque fois qu’ils surgissent."],
  catholicCase:["In Catholic virtue ethics, chastity is integration under reason: married and unmarried people both learn to direct sexuality according to their state and duties. The goal is not numbness but freedom from being ruled by appetite.","Dans l’éthique catholique des vertus, la chasteté est une intégration sous la raison : mariés et célibataires apprennent à orienter la sexualité selon leur état et leurs devoirs. Le but n’est pas l’insensibilité, mais la liberté à l’égard de la domination de l’appétit."],
  counter:["But suppression of desire can still cause psychological harm.","Mais la suppression du désir peut tout de même causer un dommage psychologique."],
  response:["Shame, fear and indiscriminate suppression can cause suffering requiring pastoral or clinical attention. Chastity instead orders desire to the good through temperance (Aquinas, II-II q.151 a.1) without declaring desire evil. Freud’s criticism of the sexual mores of his period does not establish that every practice of chastity is psychologically harmful.","La honte, la peur et une suppression indiscriminée peuvent entraîner des souffrances exigeant une attention pastorale ou clinique. La chasteté ordonne plutôt le désir au bien par la tempérance (saint Thomas, II-II, q.151, a.1), sans déclarer le désir mauvais. La critique freudienne des mœurs de son époque n’établit pas que toute pratique de la chasteté soit psychologiquement nocive."],
  bottom:["Chastity is not the denial of sexuality. Properly understood, it is the discipline by which sexuality serves the good of the person rather than governing the person.","La chasteté n’est pas la négation de la sexualité. Bien comprise, elle est la discipline par laquelle la sexualité sert le bien de la personne au lieu de la gouverner."]
},
"CSE029":{
  opposition:["A qualitative study of 15 US priests documented both benefits and psychological difficulties associated with celibacy and obedience. Can lifelong celibacy involve distress or isolation that defenders should take seriously?","Une étude qualitative auprès de quinze prêtres américains a relevé des effets bénéfiques comme des difficultés psychologiques liés au célibat et à l'obéissance. Le célibat perpétuel peut-il entraîner des souffrances ou un isolement qu'il faut prendre au sérieux ?"],
  appeal:["Celibacy can indeed be lived badly, and human beings genuinely need intimacy, friendship and belonging.","Le célibat peut réellement être mal vécu, et l’être humain a véritablement besoin d’intimité, d’amitié et d’appartenance."],
  concession:["Celibacy is not automatically healthy. Isolation, poor formation, emotional immaturity or lack of community can seriously damage a person.","Le célibat n’est pas automatiquement sain. L’isolement, une mauvaise formation, l’immaturité affective ou l’absence de communauté peuvent gravement nuire à une personne."],
  breakpoint:["The need for intimacy and attachment does not establish that sexual activity itself is a psychological necessity.","Le besoin d’intimité et d’attachement n’établit pas que l’activité sexuelle elle-même soit une nécessité psychologique."],
  catholicCase:["Catholic tradition treats continence as humanly possible while insisting on friendship, community, prayer and disciplined life. It distinguishes the need for love and relationship from a supposed necessity of sexual expression.","La tradition catholique considère la continence comme humainement possible tout en insistant sur l’amitié, la communauté, la prière et une vie disciplinée. Elle distingue le besoin d’amour et de relation d’une prétendue nécessité d’expression sexuelle."],
  counter:["But even if possible, why call it a higher vocation?","Mais même si c’est possible, pourquoi l’appeler une vocation supérieure ?"],
  response:["That is a theological question distinct from psychological health. Catholicism values consecrated virginity because of its undivided dedication to God, not because marriage or sexuality are dirty.","C’est une question théologique distincte de la santé psychologique. Le catholicisme valorise la virginité consacrée en raison de son dévouement sans partage à Dieu, non parce que le mariage ou la sexualité seraient impurs."],
  bottom:["A 15-person qualitative study cannot establish the prevalence or cause of psychological distress among all celibates. Celibacy is not a psychiatric diagnosis; each person's health, relationships and support need individual assessment.","Une étude qualitative de quinze personnes ne permet d'établir ni la prévalence ni la cause de la détresse chez tous les célibataires. Le célibat n'est pas un diagnostic psychiatrique ; la santé, les relations et le soutien de chacun exigent un examen individuel."]
},
"CSE031":{
  opposition:["If two people sincerely love each other, are committed and intend to marry, requiring a wedding before sex looks like making a ceremony more important than the relationship.","Si deux personnes s’aiment sincèrement, sont engagées et ont l’intention de se marier, exiger le mariage avant les relations sexuelles semble donner plus d’importance à une cérémonie qu’à la relation."],
  appeal:["Love, commitment and serious intention matter morally; a merely casual encounter is not the same relational reality as a devoted couple.","L’amour, l’engagement et l’intention sérieuse comptent moralement ; une rencontre occasionnelle n’est pas la même réalité relationnelle qu’un couple profondément engagé."],
  concession:["A loving engaged couple possesses genuine goods that a casual sexual relationship may lack.","Un couple fiancé et aimant possède de véritables biens qu’une relation sexuelle occasionnelle peut ne pas avoir."],
  breakpoint:["The missing step is the claim that intention to marry already creates marriage. It does not create the public, exclusive and binding covenant or its present rights and duties.","L’étape manquante est l’idée que l’intention de se marier crée déjà le mariage. Elle ne crée ni l’alliance publique, exclusive et obligatoire, ni ses droits et devoirs présents."],
  catholicCase:["Matrimonial consent establishes the present covenant rather than a mere promise of future marriage (CIC can. 1057); Catholics ordinarily must also observe the canonical form required by law (can. 1108). The wedding is therefore not a decorative formality. Even a sincere and exclusive engagement is not yet marriage, and sexual union belongs to the covenant actually established.","Le consentement matrimonial établit l’alliance présente, et non une simple promesse de mariage futur (CIC, can. 1057) ; les catholiques doivent normalement aussi respecter la forme canonique requise (can. 1108). La célébration du mariage n’est donc pas une formalité décorative. Même des fiançailles sincères et exclusives ne sont pas encore le mariage : l’union sexuelle appartient à l’alliance réellement conclue."],
  counter:["But modern contraception separates sex from parenthood, so why must the legal or sacramental bond come first?","Mais la contraception moderne sépare la sexualité de la parentalité ; pourquoi le lien juridique ou sacramentel doit-il venir d’abord ?"],
  response:["That argument assumes contraception changes the moral meaning of sex rather than merely reducing the likelihood of conception. Catholicism rejects that premise: intercourse remains the kind of act naturally connected to generation and therefore to stable parental responsibility.","Cet argument suppose que la contraception change la signification morale de la sexualité au lieu de simplement réduire la probabilité de conception. Le catholicisme rejette cette prémisse : l’union demeure le type d’acte naturellement lié à la génération et donc à une responsabilité parentale stable."],
  bottom:["Love matters, but love alone does not create marriage. The Catholic claim is that sexual union belongs to the covenant that makes permanent fidelity and parenthood its objective framework.","L’amour compte, mais l’amour seul ne crée pas le mariage. L’affirmation catholique est que l’union sexuelle appartient à l’alliance qui fait de la fidélité permanente et de la parentalité son cadre objectif."]
}
});
