
(()=>{
 'use strict';
 const AO=window.AO=window.AO||{};
 const profile=AO.MassProfile?.id||document.body.dataset.massProfile||'low';
 const isLow=profile==='low',isMC=profile==='mc-simple'||profile==='mc-incense',isSolemn=profile==='solemn',isIncense=profile==='mc-incense'||isSolemn,isRequiem=!!AO.RequiemOverlay?.active;
 const gate=document.getElementById('aoFormGate'),pill=document.getElementById('aoProfilePill'),heading=document.getElementById('canonicalMassHeading'),reader=document.getElementById('reader'),shell=document.querySelector('.top-shell');
 const baseLabel=isLow?'LOW MASS':(isSolemn?'SOLEMN MASS':(profile==='mc-incense'?'MISSA CANTATA · INCENSE':'MISSA CANTATA · SIMPLE')),riteLabel=({requiem:'REQUIEM',nuptial:'NUPTIAL','holy-thursday':'HOLY THURSDAY','good-friday':'GOOD FRIDAY','easter-vigil':'EASTER VIGIL'})[AO.MassProfile?.rite],label=riteLabel?`${riteLabel} · ${baseLabel}`:baseLabel;
 if(pill){pill.textContent=label;pill.addEventListener('click',()=>{gate?.classList.add('open');gate?.setAttribute('aria-hidden','false')})}
 if(heading)heading.textContent=isRequiem?`Requiem · ${baseLabel}`:(isLow?'Canonical Low Mass':(isSolemn?'Canonical Solemn Mass':'Canonical Missa Cantata'));
 document.title=`Ad Orientem · v1.75 · ${label}`;
 let remembered=null;try{remembered=localStorage.getItem('ao-mass-profile')||localStorage.getItem('ao-mass-form')}catch(_){}
 const p=new URLSearchParams(location.search),explicit=p.get('form');
 if(gate&&!explicit&&!remembered){gate.classList.add('open');gate.setAttribute('aria-hidden','false')}
 gate?.querySelectorAll('[data-ao-form]').forEach(btn=>btn.addEventListener('click',()=>{const v=btn.dataset.aoForm;try{localStorage.setItem('ao-mass-profile',v);localStorage.removeItem('ao-mass-form')}catch(_){}const u=new URL(location.href);u.searchParams.set('form',v);u.searchParams.delete('mc_profile');location.replace(u.toString())}));
 function syncShellHeight(){if(!shell)return;const h=Math.ceil(shell.getBoundingClientRect().height);if(h>0){document.documentElement.style.setProperty('--ao-shell-h',`${h}px`);document.documentElement.style.setProperty('--header-h',`${h}px`)}}
 if(shell&&window.ResizeObserver)new ResizeObserver(syncShellHeight).observe(shell);window.addEventListener('resize',syncShellHeight,{passive:true});requestAnimationFrame(syncShellHeight);
 function syncCardLifecycle(){if(!reader)return {active:0,cards:0};const cards=[...reader.querySelectorAll('.mass-card')];let active=cards.filter(c=>c.classList.contains('is-active'));if(active.length>1){active.slice(1).forEach(c=>c.classList.remove('is-active'));active=active.slice(0,1)}if(!active.length&&cards.length){cards[0].classList.add('is-active');active=[cards[0]]}cards.forEach(card=>{const on=card===active[0];card.toggleAttribute('inert',!on);card.setAttribute('aria-hidden',on?'false':'true');if(!on)card.querySelectorAll('.active,.near,.focus-context,.focus-current,[aria-current="true"]').forEach(el=>{el.classList.remove('active','near','focus-context','focus-current');el.removeAttribute('aria-current')});card.querySelectorAll('.flow-unit,[tabindex]').forEach(el=>{if(!on)el.tabIndex=-1;else if(el.classList.contains('flow-unit'))el.tabIndex=0})});return {active:active.length,cards:cards.length}}
 const mo=reader&&new MutationObserver(syncCardLifecycle);if(mo)mo.observe(reader,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});window.addEventListener('ao:focus-unit-changed',syncCardLifecycle);setTimeout(syncCardLifecycle,0);setTimeout(syncCardLifecycle,250);
 const schola=document.getElementById('scholaDock');if(isLow&&schola){schola.setAttribute('aria-hidden','true');schola.setAttribute('inert','');schola.classList.remove('show')}
 function rectOverlap(a,b){return Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top))}
 function audit(){const cards=[...document.querySelectorAll('#reader .mass-card')],active=cards.filter(c=>c.classList.contains('is-active')),inactive=cards.filter(c=>!c.classList.contains('is-active')),stale=inactive.reduce((n,c)=>n+c.querySelectorAll('.active,.focus-current,[aria-current="true"]').length,0),interactive=inactive.filter(c=>!c.hasAttribute('inert')||c.getAttribute('aria-hidden')!=='true').length,L=document.querySelector('.rail.left')?.getBoundingClientRect(),R=document.querySelector('.rail.right')?.getBoundingClientRect(),S=schola?.getBoundingClientRect(),scholaOverlap=(S&&schola?.classList.contains('show'))?((L?rectOverlap(S,L):0)+(R?rectOverlap(S,R):0)):0,focus=(AO.FocusAudit?.run?.()||null),missalPairs=document.querySelectorAll('body[data-mode="read"] .flow-unit.missal-pair').length,sermonInterstitial=!!document.querySelector('body[data-mode="read"] .pause-unit.missal-interstitial');return {build:'v1.75_R14_INTEGRATION_CANDIDATE',profile,activeCards:active.length,totalCards:cards.length,staleFocusNodes:stale,inactiveInteractiveCards:interactive,shellHeight:Math.round(shell?.getBoundingClientRect().height||0),scholaRailOverlapPx2:Math.round(scholaOverlap),focus,missalPairs,sermonInterstitial,pass:active.length===1&&stale===0&&interactive===0&&scholaOverlap===0&&(!focus||focus.pass)}}
 AO.UnifiedAudit=Object.freeze({run:audit,syncCardLifecycle});
})();
